Fix issue #1077
openwebwork/webwork2 pull request #1153
Opened 2020-11-02 07:49 UTC by cucucucumber

I fixed the issue #1077 by forcing UTF-8 encoding to read and write configuration files.

Warning: Because of the Windows text file saving mechanism, some unexpected situations may occur on Windows Server 2012/Windows 8.1 and earlier versions. But this problem does not appear after Windows 10 Build 19041 and forced UTF-8 file encoding is turned on.

2020-11-02 16:52 UTC, Alex-Jordan commented
Following up on #1152, this pull request looks good. One or more people will test it out before merging, and it's a variable how long it takes for people to get around to that. Thanks for working on the issue, and welcome!

2021-03-17 20:37 UTC, taniwallach requested changes

2021-04-23 07:14 UTC, robert-marik commented
Another attempt to solve the issue in another way: https://github.com/robert-marik/webwork2/commit/939fe2b1d86c54011c3dd28b709efb7ae4040ce4
The main idea is to put conf file in English. See my comments in the original issue https://github.com/openwebwork/webwork2/issues/1077 for an explanation.

2021-05-03 10:01 UTC, taniwallach commented
A better fix to https://github.com/openwebwork/webwork2/issues/1077 is in https://github.com/openwebwork/webwork2/pull/1352.

2021-05-03 10:01 UTC, closed without merging