Add configuration options for parsing alternative input tokens and full-width unicode character support.
openwebwork/webwork2 pull request #1174
Opened 2021-01-13 16:57 UTC by dpvc

This is the companion PR to openwebwork/pg#518 that addresses the issues in openwebwork/pg#517.  This PR adds the needed course configuration parameters to allow course-wide control of the new features.

2021-01-16 18:16 UTC, drdrew42 requested changes
Trivial changes needed. Typos 'copyihng' and 'Fullk' in both changed files.

2021-01-16 21:37 UTC, dpvc commented
@drdrew42, thanks!  I have fixed the typos.

2021-01-16 22:57 UTC, drdrew42 approved these changes

2021-01-19 21:23 UTC, taniwallach approved these changes
I tested this with https://github.com/openwebwork/pg/pull/518 and these settings work as intended, as far as I tested in terms of enabling/disabling support for:
  - Unicode minus and Unicode infinity
  - Full width open/close parenthesis (https://github.com/openwebwork/pg/issues/517#issuecomment-757404101)

Thanks @dpvc !!!

2021-01-19 21:25 UTC, dpvc commented
@taniwallach, thanks for the review.

2021-01-20 04:11 UTC, drgrice1 approved these changes
This looks good.

2021-01-27 22:16 UTC, Alex-Jordan approved these changes

2021-01-27 22:24 UTC, Alex-Jordan commented on conf/defaults.config
> +
Good idea. I added a commit with that.

2021-01-27 22:25 UTC, Alex-Jordan commented
Everyone approved this, and nearly everyone approved the corresponding https://github.com/openwebwork/pg/pull/518. So I'm going to merge. I'm trying to make a dent in the PR backlog this week.

2021-01-27 22:25 UTC, merged