Allow UTF-8 in achievement export/import/score
openwebwork/webwork2 pull request #1206
Opened 2021-02-20 21:46 UTC by robert-marik

Without this patch

- UTF-8 characters in the name or description of achievements produce error "Wide character in print at /usr/lib/x86_64-linux-gnu/perl/5.30/IO/Handle.pm line 418." The file is created fine, anyway.
- The UTF-8 characters in the names of students are broken when exporting score table for achievements
- The import of achievements with UTF-8 in name or description fails. Only the first non-UTF-8 lines are imported, the rest is silently ignored.

The patch solves these problems. Replaces previously submitted (and closed) pull request https://github.com/openwebwork/webwork2/pull/1196

2021-04-15 17:35 UTC, robert-marik commented
This is related to the issue reported at https://github.com/openwebwork/webwork2/issues/1158

2021-06-02 22:14 UTC, taniwallach requested changes
It looks like all you meant to change was `lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm` but additional commits were added to try to bring your branch in sync with WeBWorK-2.16.

There are now merge conflicts, so it seems that it would be easier to test if you rebased from the current head of WeBWorK-2.16 or just redid the change from there, and force pushed to the new branch.

2021-06-03 18:27 UTC, robert-marik commented
Rebased. Thank you.

2021-06-08 15:34 UTC, taniwallach requested changes
At present there is a bug, and the generated `coursename_achievement_scores.csv` has Mojibake instead of the student names in UTF-8. This is a result of a double encoding as the `print SCORE` line calling `Encode::encode("UTF-8", ... )` when the file is already being opened using `':encoding(UTF-8)'` based on the `use` line at the top of file.

Dropping the extra encoding in the `print SCORE` line fixes the problem for me.

Fixed in https://github.com/robert-marik/webwork2/pull/3 to @robert-marik's branch.


After that change - the student names appear properly in a score file, the achievement name and description appear properly in an "export file" and an import of a file with UTF-8 data works properly.

2021-06-08 15:34 UTC, taniwallach commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
> +	    print SCORE Encode::encode("UTF-8","$user_id, $userRecord->{last_name}, $userRecord->{first_name}, $userRecord->{section}, ");
The `Encode` call in this line needs to be dropped. It caused a double encoding which leads to mojibake.

2021-06-08 15:37 UTC, taniwallach commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
> +	    print SCORE Encode::encode("UTF-8","$user_id, $userRecord->{last_name}, $userRecord->{first_name}, $userRecord->{section}, ");
Fixed in https://github.com/robert-marik/webwork2/pull/3 to @robert-marik's branch.

You can merge, and then rebase so the PR will be nice and clean.

2021-06-08 16:48 UTC, robert-marik commented
Fixed, thank you for catching this bug.

2021-06-08 17:44 UTC, taniwallach approved these changes
Works as expected with this version of the PR.
Merging.

2021-06-08 17:45 UTC, merged