Update mathjax to version 3
openwebwork/webwork2 pull request #1215
Opened 2021-02-24 20:14 UTC by drgrice1

2021-02-24 20:53 UTC, dpvc requested changes

2021-02-24 20:53 UTC, dpvc commented on conf/defaults.config
> +$webworkURLs{MathJax}       = "$webworkURLs{htdocs}/mathjax/es5/tex-mml-chtml.js";
I would just load `tex-chtml.js` rather than `tex-mml-chtml.js` unless you really want MathML support.  I'm assuming the reason that `TeX-MML-AM` was uses was to get the AsciiMath, and there were not combined files that were just TeX and AsciiMath.  It would be possible to build a custom combined component (the tools are part of the mathjax-full npm package) that includes just TeX and AsciiMath, together with CommonHTML output.  It's not hard to do that, but would be additional steps in the Dockerfile.

2021-02-24 20:53 UTC, dpvc commented on htdocs/js/apps/ProblemGrader/problemgrader.js
> +			MathJax.typeset([ '.popover-content' ]);
If you don't load `tex-chtml-full.js`, then you can run into issues here if the math needs to load any extensions (e.g., uses `\color` or `\verb` or a bunch of other things).

Otherwise, you might want to use `MathJax.typesetPromise(['.popover-content'])` instead, or better yet

``` javascript
MathJax.startup.promise = MathJax.startup.promise.then(() => MathJax.typesetPromise(['.popover-content']));
```
so that you don't accidentally end up calling `MathJax.typesetPromise()` twice concurrently.

2021-02-24 20:53 UTC, dpvc commented on htdocs/js/apps/ProblemSetDetail2/problemsetdetail2.js
> +				MathJax.typeset();
Again, this may want to be

``` javascript
MathJax.startup.promise = MathJax.startup.promise.then(() => MathJax.typesetPromise());
```

2021-02-24 20:53 UTC, dpvc commented on htdocs/js/apps/SetMaker/setmaker.js
> +              MathJax.typeset([ el ]);
Similarly

``` javascript
MathJax.startup.promise = MathJax.startup.promise.then(() => MathJax.typesetPromise([el]));
```

2021-02-24 20:53 UTC, dpvc commented on htdocs/js/vendor/other/knowl.js
> +            MathJax.typesetPromise([ $output[0] ]).then(function() { $knowl.slideDown("slow"); });
In keeping with using `MathJax.startup.promise` as a quing mechanism, this might want to be

``` javascript
MathJax.startup.promise = MathJax.startup.promise.then(() => MathJax.typesetPromise([$output[0]]));
MathJax.startup.promise.then(function () {$knowl.slideDown("slow")});
```

(Here, the next MathJax doesn't have to wait for the knowl, so you don't need to save the promise for that.)

2021-02-24 20:53 UTC, dpvc commented on htdocs/js/vendor/other/knowl.js
> +            MathJax.typesetPromise([ $output[0] ]).then(function() { $knowl.slideDown("slow"); });
Same here as previous comment.

2021-02-24 20:53 UTC, dpvc commented on lib/WeBWorK/Utils/AttemptsTable.pm
> +		return '<span>\['.$tex.'\]</span>';
Yo don't really need the `<span>` element, here and below, but I guess it doesn't hurt.  (A `<div>` might be better, since the content is display style, so block level).

2021-02-24 20:53 UTC, dpvc commented on htdocs/themes/math4/gateway.template
> +<script type="text/javascript" src="<!--#url type="webwork" name="MathJax"-->" id="MathJax-script" async defer></script>
If you want to support IE11 (the oldest IE that v3 supports), you will need to include 

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
```

as well.  It could be inside an IE if-then comment:

``` html
<!--[if IE 11]>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<![endif]-->
```

This will need to be included in all the templates and the WeBWorK clients that load MathJax.

I don't think you want both `async` and `defer`.  Both cause the script to be loaded asynchronously, but `async` will have it run as soon as it is loaded, while `defer` puts it off until the page is fully parsed.  I would say `defer` is probably a reasonable choice.  If you put the polyfill script before the MathJax one, you would also be able to use `defer`, since `defer` preserves the order of execution (while `async` doesn't).

2021-02-24 21:29 UTC, drgrice1 commented
Thanks for the comments.  I will look into the needed changes.

2021-02-24 21:59 UTC, drgrice1 commented on lib/WeBWorK/Utils/AttemptsTable.pm
> +		return '<span>\['.$tex.'\]</span>';
I'll just remove the span then.  Or would it be better to have it wrapped in a div?

2021-02-24 22:00 UTC, dpvc commented on lib/WeBWorK/Utils/AttemptsTable.pm
> +		return '<span>\['.$tex.'\]</span>';
I don't think it needs either one.

2021-02-24 22:11 UTC, drgrice1 commented on htdocs/themes/math4/gateway.template
> +<script type="text/javascript" src="<!--#url type="webwork" name="MathJax"-->" id="MathJax-script" async defer></script>
I didn't know about this `<!--[if IE 11]>...<![endif]>` construct.  Is that an html thing, or is that a webwork template implementation?

2021-02-24 22:13 UTC, drgrice1 commented on htdocs/themes/math4/gateway.template
> +<script type="text/javascript" src="<!--#url type="webwork" name="MathJax"-->" id="MathJax-script" async defer></script>
Never mind.  Google searching is a bit tedious for this sort of thing, but I found it.

2021-02-24 22:17 UTC, drgrice1 commented
I have noticed with the content that is typeset after the page loads (knowls, grader comments, and such) that the rest of the page content flickers.  It seems as if mathjax is re-typesetting the entire page.  This is with (or without) the changes you suggested to the typesetPromise code.  Is it set up right to only typeset the new elements?

2021-02-24 22:20 UTC, dpvc commented on htdocs/themes/math4/gateway.template
> +<script type="text/javascript" src="<!--#url type="webwork" name="MathJax"-->" id="MathJax-script" async defer></script>
It's an HTML thing (actually, an IE thing).  To all other browsers, it looks like a comment (between `<!-- and -->`), but IE interprets it and only does the HTML in between if the condition is met.

When I was looking up the reference for it, it turns out that it is no longer supported in IE 11 (who knew?), so don't bother with it.  Here's the [Wikipedia page](https://en.wikipedia.org/wiki/Conditional_comment) for it.  The Microsoft pages have all been taken down.

2021-02-24 22:25 UTC, drgrice1 commented on htdocs/themes/math4/gateway.template
> +<script type="text/javascript" src="<!--#url type="webwork" name="MathJax"-->" id="MathJax-script" async defer></script>
Okay, I will just add the polyfill unconditionally.  Presumably polyfill.io is smart enough to load only what is needed.

2021-02-24 23:22 UTC, pstaabp commented
I just pull this down (even the new couple that you just posted).  I'm getting the following javascript errors:
```
tex-chtml.js:1 Uncaught RangeError: Maximum call stack size exceeded
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
    at o (VM594 tex-chtml.js:1)
```

this is on a problem with about 10 [math] boxes on the page.  I just updated MathJax, so I'm running 3.1.2 of MathJax.

Wondering if I have some configuration problem.

2021-02-24 23:27 UTC, drgrice1 commented
I am not sure.  I am not seeing that.

I don't think this would give the issues that you are seeing, but did you change the line in localOverrides.conf to `$webworkURLs{MathJax} = "$webworkURLs{htdocs}/mathjax/es5/tex-chtml.js";`

2021-02-24 23:31 UTC, drgrice1 commented
@pstaabp:  Also, just to make sure... You have checked out both this pull request and the corresponding pg pull request, right?

2021-02-24 23:44 UTC, drgrice1 commented
@dpvc: Does MathJax 3 no longer allow selections?  I can't seem to copy and paste MathJax stuff anymore.  This isn't a problem for me as I didn't do this before, but I am just curious.

2021-02-25 00:14 UTC, pstaabp commented
I had missed the pg branch.  Those errors went away.

2021-02-27 10:58 UTC, pstaabp approved these changes

2021-02-27 18:42 UTC, dpvc commented
> I have noticed with the content that is typeset after the page loads (knowls, grader comments, and such) that the rest of the page content flickers. It seems as if mathjax is re-typesetting the entire page. This is with (or without) the changes you suggested to the typesetPromise code. Is it set up right to only typeset the new elements?

Yes, but typesetting new content can cause MathJax to change the stylesheet that it uses.  It may be that that is causing the flicker you are seeing.  What browser are you using.  I haven't tried this branch yet, but will see if I get the same result.  If that is the cause, then switching to the sag output might be a way to avoid it (as the SVG output doesn't need to update the CSS as often).

> Does MathJax 3 no longer allow selections? I can't seem to copy and paste MathJax stuff anymore.

You are correct, you can't select the math in v3.  This is due to the way the CommonHTML output uses CSS `content` styles to insert the characters, and it turns out that `content` can't be selected.  This will probably change in the next major release this summer, but for now, that is true.  I did work out a [couple of alternatives](https://groups.google.com/g/mathjax-users/c/1BzTQFINbqY/m/xGYAlhDNAwAJ) that would allow copying and pasting.  One of these could he added to the `mathjax-config.js` file if you wanted to add that.  (I haven't looked carefully to see if they would need any updating since those were written, but you could give it a try if you wanted.)

I will try out the branch, but your changes look good.

2021-02-27 20:02 UTC, dpvc approved these changes
I've tested out the branch, and it works for me.  I don't see the flickering you indicate.  There is a bug in Safari that causes it to sometimes clip the expressions incorrectly, however, and perhaps that is part of what you are seeing, if you are using Safari.  For that reason, you may want to use the SVG output rather than CHTML.  We are hoping to address that issue during the font update this summer.

2021-02-27 20:20 UTC, drgrice1 commented
Not being able to select the MathJax is fine with me.  If others want that, then we can see about implementing that.

I am using the Firefox browser on linux.  However, I just noticed something with the flickering.  It only occurs if the developer tools are open when the page loads.  If the developer tools are not open when the page loads (even if they are opened after the page loads) this flickering does not occur.  I tested this with Google Chrome as well, and the same behavior is exhibited there.

I almost always have the developer tools open, but students (and most other people) of course will not.  So this is not an issue.

2021-02-27 20:26 UTC, drgrice1 commented
I guess this is an issue if there is a problem on Safari.  I don't have Safari to test, but we can make the switch if that is needed.

2021-02-28 13:13 UTC, dpvc commented on htdocs/js/apps/ProblemGrader/problemgrader.js
> +			MathJax.startup.promise = MathJax.startup.promise.then(() => MathJax.typesetPromise(['.popover-content']));
I just remembered:  the `=>` construct will not work in IE11 (I'm too used to using Typescript and down-compiling to es5).  To support IE11, replace

``` javascript
() => MathJax.typesetPromise([...])
```

with

``` javascript
function () {return MathJax.typsetPromise([...])}
```

here and the other places it is used.

2021-02-28 16:34 UTC, drgrice1 commented on htdocs/js/apps/ProblemGrader/problemgrader.js
> +			MathJax.startup.promise = MathJax.startup.promise.then(() => MathJax.typesetPromise(['.popover-content']));
Yeah, stupid on my part. I should have seen that. I will fix it.

2021-03-03 05:54 UTC, Alex-Jordan commented
I tested this and it works for me. I also tried Safari and I couldn't see any clipping. But it sounds like it only happens in certain circumstances. With 2 approvals, plus Glenn's I assume, I will merge this now. (And the pg counterpart.)

2021-03-03 05:54 UTC, merged

2021-03-28 07:00 UTC, Alex-Jordan commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
This configuration essentially says that if `\color` is used in some math, load the `colorV2` extension, not the `color` extension. And so `\color` will be the version from `colorV2`.

If you don't know, the difference is that the `colorV2` version is targeted. So you use it like `\color{blue}{this is blue}`. If you use it like `\color{blue}this is blue` then only the "t" will be blue. With the `color` extension, it works like in LaTeX affecting the color of all that follows within some scope. So with the `color` version, `\color{blue}this is blue` will make all of "this is blue" be blue.

When I put `This is \(\color{blue}blue\)` or `This is \(\color{blue}{blue}\)` into a problem, it doesn't work. MathJax does not recognize `\color` as a macro. 

When I return the configuration to use `color` tor the `\color` macro instead of `colorV2`, then it works.

I have two questions. Am I right that this appears to be a MathJax bug?

And are we sure that we want WeBWorK's default to use `colorV2`? That keeps the behavior from before this version of WW, when MathJax 2 is supposed to be used. But it also makes the `\color` macro behave differently in HTML and hardcopy.

2021-03-28 11:39 UTC, drgrice1 commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
When I chose these options, I chose them to conform to the set up of webwork before the transition to MathJax v3.  The colorV2 extension does this.  As to if this is what we want or not, I don't know.

Previously there was no choice, but now that we have the choice, I agree that it would be better to choose consistency between HTML and hardcopy.

2021-03-28 11:43 UTC, drgrice1 commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
I am seeing the issue you see as well.  If I add `\(\color{blue} ...\)` I don't get color.  I noticed you can do `\(\require{color}\color ...\)` or `\(\require{colorv2}\color ...\)` and it takes effect from there on in the page, but that isn't really what we want.

@dpvc:  Is the configuration not correct to make `\color` work without having to call `\require` first, or is this a MathJax bug as @Alex-Jordan suggests?

2021-03-28 12:29 UTC, dpvc commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
It should be `colorv2` not `colorV2`.  We normalized all the names to lower case in the last release.  I did make compatibility translations in most places, but apparently missed the autoload options.

2021-03-28 12:30 UTC, dpvc commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
PS, the LaTeX-color extension was available in v2 as well, but was not the default.  Now it is in v3.

2021-03-28 12:35 UTC, drgrice1 commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
I see. I misread or misunderstood the documentation.

2021-03-28 12:58 UTC, dpvc commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
You may have been looking at an older version of the documentation from before we made the change.

2021-03-28 18:02 UTC, Alex-Jordan commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
I don't object to keeping it default to `colorv2` instead of `color`.

Is it important for this configuration file to live where it lives instead of in `webwork2/conf/`?

2021-03-28 18:06 UTC, drgrice1 commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
> Is it important for this configuration file to live where it lives instead of in `webwork2/conf/`?

I think we should just use the MathJax v3 default.  I think that consistent behavior between HTML and hardcopy output is better.

We could make a link from its current location to the conf dir, but it is javascript, and can't directly be used in the conf dir.

2021-03-28 18:14 UTC, drgrice1 commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
Another option is to move this code into the math4.js file, and then you can use a custom theme and override that file.  Or even just use the math4-overrides.js file to do this.  You lose the `defer` attribute, but that would still work as by the time the MathJax javascript loads it would be defined.

2021-03-28 18:15 UTC, drgrice1 commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
Actually, since math4.js is `defer`ed we may need to `defer` the math4-overrides.js loading as well for that to work right.

2021-03-28 18:16 UTC, drgrice1 commented on htdocs/js/apps/MathJaxConfig/mathjax-config.js
> +			autoload: { color: [], colorV2: ['color'] },
Although, then the above suggestion for the MathJax config won't work.

2021-03-28 18:43 UTC, drgrice1 commented
There is yet another option.  If we stick with `colorv2` then you can do `{\color{blue}{5x+3}}`, and this will work the same both in HTML and in hardcopy.