scaffold numbering
openwebwork/webwork2 pull request #1383
Opened 2021-05-28 22:42 UTC by Alex-Jordan

This is a companion PR for a `pg` PR that is coming up.

2021-05-28 23:47 UTC, drdrew42 commented
Linked PR openwebwork/pg#579

2021-05-29 01:09 UTC, drgrice1 requested changes
There are a few changes needed to make this look better.

2021-05-30 16:05 UTC, Alex-Jordan commented on htdocs/js/apps/Scaffold/scaffold.css
> +	padding-right: 0;
I lost mental track of this and didn't see it yesterday while working on the pg counterpart. Will tend to this soon.

2021-06-01 23:40 UTC, Alex-Jordan commented
With @drgrice1's styling commit merged now, this is ready for a review alongside openwebwork/pg#579

2021-06-05 02:20 UTC, drgrice1 approved these changes
This is okay.

2021-06-16 10:03 UTC, merged