Gateway enhancements
openwebwork/webwork2 pull request #1407
Opened 2021-06-13 00:45 UTC by Alex-Jordan

There are two commits here. The first is more or less trivial, inserting some space characters in between Gateway status messages so they don't come out like:

Your recorded score on this test (version 1) is 0/5.You exceeded the allowed time.

The second commit rebuilds the page/problem navigation table. There was a lot of excess things in the navigation table like nbsp characters for spacing and entire cells using `[` and `]` for delimiting pages. With this, all the excess stuff is cleared away and a table cell with a colspan is used for a page with multiple problems in it.

Then I also added a third row to the navigation table with problem scores. As an instructor with a 20-question quiz with 4 questions on each page, it can help to know that the student's only incorrect answer is on page 3, or something like that. Also if you are permitting students to see scores on previously graded submissions, this is good. I've had students complain that they graded a test and it told them a few were wrong. They went to preview some answer and that cleared the display of what was right/wrong and they didn't know how to get that info back. I was only allowing one additional graded submission, so they had a fair complaint.

Once scores are printed, it makes sense to list all of the problem numbers, even for problems on other pages. But I did not make them into links.

I put classes, colgroup elements, and col elements into the table to do better styling. Also I put an "active" class on the cell for the current page. All I did for now with styling was to put left/right borders on the colgroups, give everything some padding, highlight the active page cell, and style the row headers with CSS instead of how they had been styled with a `b` tag. I think more attention to styling would be great, but I don't know what direction to take it in.

More broadly, this could be improved upon. But it is an improvement from what is there now.

2021-06-13 01:06 UTC, Alex-Jordan commented
Here are some screen shots to get a visual. Styling is of course up for changes.

## Multiple questions per page

<img width="721" alt="Screen Shot 2021-06-12 at 6 00 00 PM" src="https://user-images.githubusercontent.com/4732672/121792377-d4332d00-cba8-11eb-867b-ffcdc295c349.png">

## One question per page

<img width="707" alt="Screen Shot 2021-06-12 at 6 00 20 PM" src="https://user-images.githubusercontent.com/4732672/121792379-d72e1d80-cba8-11eb-85f6-a0b631219e6a.png">

## All questions on one page

<img width="684" alt="Screen Shot 2021-06-12 at 6 00 32 PM" src="https://user-images.githubusercontent.com/4732672/121792382-ddbc9500-cba8-11eb-8159-23298dfba845.png">

2021-06-13 13:49 UTC, drgrice1 approved these changes
This looks much better than before.

There are a couple of things that I notice though.

First, would it be possible to only show the score row after the quiz has been graded?

The second thing is really an existing problem that this doesn't fix, and would probably take a complete restructuring to fix.  So this is probably something that is not to be done now.  The issue is with narrow screens, quizzes with a large number of problems, quizzes with a large number of pages, or those factors combined.  In these cases the table goes off the screen to the right, and you have to scroll to reach those far right problems or pages.  This is always an issue when using tables for layout.

2021-06-13 13:55 UTC, drgrice1 requested changes
Actually, there is more to the first issue I listed that makes this something that needs to be changes.  That ignores the `can showScore` settings.

2021-06-13 13:56 UTC, drgrice1 commented
Furthermore, my initial issue was enough to require changes.  The scores should not be shown until the quiz is graded.  That is consistent with how it was before.

2021-06-13 13:59 UTC, drgrice1 approved these changes
Wait, I missed line 2030 where it does check the canShowProblemScores setting.  My bad.

2021-06-13 14:04 UTC, drgrice1 requested changes
Wait once more.  Something is still not right though.  The score row is shown for a student before the quiz is graded.  The scores are all zeros, but that could be confusing for a student.  The score row shouldn't be shown at all until after the quiz is graded with at least one submission.

2021-06-13 14:35 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
>  				my $pn = ($i == $pageNumber) ? $i :
This looks better to me if the `&nbsp;` is also added for the current page number.  Then the colums all have uniform spacing.  Although, perhaps even better would be to drop the `&nbsp;` for both cases, and modify the `.gwNavigation colgroup.page` rule in gateway.css (of the math4 theme) by adding `padding: 0 0.25rem;`.  You can twiddle the actual padding setting if you like.  `0.25rem` is a little less than the `&nbsp;` gives.

2021-06-13 14:57 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
>  				my $pn = ($i == $pageNumber) ? $i :
Looking closer I see that you already have a padding of `0.5rem` that applies (and my suggested rule is preempted by that).  So ignore the styling changes I suggested.  Just drop the `&nbsp` and this looks better already.

2021-06-13 15:04 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
> +				push(@$probRow, "$pn");
There shouldn't be quotes on `$pn` on lines 2000 and 2002.  I realize that they were there before, but that was incorrect.  Single variables should not be interpolated.  That is an inefficiency to avoid in Perl.

2021-06-13 16:09 UTC, Alex-Jordan commented on lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
> +				push(@$probRow, "$pn");
Got it in an upcoming commit.

2021-06-13 16:12 UTC, Alex-Jordan commented on lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
>  				my $pn = ($i == $pageNumber) ? $i :
Thanks, I had missed those nbsps in the links surrounding the number. Removed in an upcoming commit.

2021-06-13 16:14 UTC, Alex-Jordan commented
> The score row shouldn't be shown at all until after the quiz is graded with at least one submission.

Agreed. I'll change this later today.

2021-06-13 20:01 UTC, Alex-Jordan commented
>     The score row shouldn't be shown at all until after the quiz is graded with at least one submission.

OK, it is behaving this way now.

2021-06-14 02:17 UTC, drgrice1 approved these changes
This looks good now.  Much nicer than before.

It would still be nice to do something about the case that the page/problem nav is so wide that it make scrolling necessary to see the right part of it.

2021-06-14 02:54 UTC, Alex-Jordan commented
Without rebuilding the table structure, we could:

* Remove the `Move to ` and `Jump to ` from the row headers
* Shrink the padding

I think it could support up to about a 15-question quiz on a phone screen that way without needing to scroll. And on a regular screen, more than 3x as many. Is this worth doing? Or not, if you'd like to try something more responsive like with flex boxes or something?

2021-06-14 03:12 UTC, drgrice1 commented
I think for now this is good.  It would take switching to a flex box layout to make it responsive.  It would probably better to put this off until we have a newer version of bootstrap.  Bootstrap versions 4 and 5 use flex box for their responsive layouts and make this sort of thing much easier to accomplish.

2021-06-14 03:16 UTC, drgrice1 commented
I just noticed that on narrower screens the `Move to` and `Jump to` text wrap anyway.  So removing those won't help.

The changes in this pull request make the page/problem nav narrower than before, so this does help at least.

2021-06-16 01:34 UTC, Alex-Jordan commented on htdocs/themes/math4/gateway.css
> +.gwNavigation th, td {
```suggestion
.gwNavigation th, .gwNavigation td {
```

2021-06-30 20:35 UTC, drdrew42 approved these changes

2021-06-30 20:46 UTC, merged