Ww216 patches admincourse
openwebwork/webwork2 pull request #1423
Opened 2021-06-16 22:16 UTC by mgage

if admin course is added then its tables are also updated and  user: admin with password: admin are added to the admin course.

2021-06-17 11:00 UTC, taniwallach commented
I have never needed to do anything to have the `admin` user created. It seems to be handled by the load from the class list file in
```
$WEBWORK_ROOT/bin/addcourse admin --db-layout=sql_single --users=$WEBWORK_ROOT/courses.dist/adminClasslist.lst --professors=admin
```
My guess is that you may have manually needed to fix the DB if the DB connection was not working when the course was created.

2021-06-17 15:23 UTC, mgage commented
I'll try it again to double check and report back before this is checked in.  I don't think it was because of a bad connection to the database.

2021-06-23 12:50 UTC, mgage commented
@taniwallach I think you are right, if the addcourse admin script runs completely the admin user and its credentials are also installed.

2021-07-01 22:28 UTC, taniwallach requested changes
As noted, I think the extra lines to make a second attempt to fix the admin course tables and to add the admin user are not needed.

2021-07-01 22:28 UTC, taniwallach commented on docker-config/docker-entrypoint.sh
> +                    -e 's/^\$database_password ='\''passwordRW'\''/$database_password =$ENV{"WEBWORK_DB_PASSWORD"}/' \
This line is a mission critical correction, as the line in `site.conf.dist` was changed to use single quotes.
The change on these 2 lines to match from the start of the line so it should only modify the active definition lines and not other lines is also good.

2021-07-01 22:28 UTC, taniwallach commented on docker-config/docker-entrypoint.sh
> +	$WEBWORK_ROOT/bin/upgrade_admin_db.pl
I have yet to be able to trigger a case where these extra lines are needed.
If I delete the course directory, but left the database tables alone - the course seems to work after being recreated by the prior call to `bin/addcourse`.
My impression is that these lines can be deleted (or commented out, if @mgage want's to retain them in case some special circumstances do make them necessary).

2021-07-07 20:03 UTC, mgage commented
this has been addressed in patch5

2021-07-07 20:03 UTC, closed without merging