modifications to allow 'Return-Path' to be specified to be used for r…
openwebwork/webwork2 pull request #1496
Opened 2021-08-29 18:40 UTC by mgage

…eporting bounce back messages
     $mail{set_return_path} is set in the SMTP configuration section of site.conf
	my $return_path_for_errors = $ce->{mail}->{set_return_path}; 
	# $set_return_path is the address used to report returned email. It is an argument 
	# used in sendmail() (aka Email::Simple::sendmail).
	# For arcane historical reasons sendmail  actually sets the field "MAIL FROM" and the smtp server then 
	# uses that to set "Return-Path".
	# references:
	#  stackoverflow: https://stackoverflow.com/questions/1235534/what-is-the-behavior-difference-between-return-path-reply-to-and-from
	#  Email::Simple: https://metacpan.org/pod/Email::Sender::Manual::QuickStart#envelope-information
	#

2021-08-29 19:13 UTC, mgage commented
Don't merge yet.  
To test :
1. Modify site.conf to contain the $mail{set_return_path} variable from site.conf.dist. 
2. send a Feedback message from your webwork course.
3. Inspect the message sent to the instructor by viewing all off the headers (I used the "raw" presentation in Apple Mail ).  You should see "Return-Path" with a value of noreply@.....

If you can determine whether this solves any issues you've had with spam filters on your smtp servers.

If all of this works there are three more places where modifications need to be made. 
after line 893 SendMail.pm
after line 949 SendMail.pm
after line 619 ProblemUtil.pm

2021-08-30 02:16 UTC, drgrice1 requested changes
This is good for a hotfix if there are those that need it.

There are some things that need to be fixed though.

2021-08-30 02:16 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Feedback.pm
>  	}
The else clause is still needed here.  The "Email Instructor" page now opens with no contents with this.

2021-08-30 16:14 UTC, mgage commented on lib/WeBWorK/ContentGenerator/Feedback.pm
> +	#
ok

2021-08-30 16:14 UTC, mgage commented on lib/WeBWorK/ContentGenerator/Feedback.pm
>  	}
I'd already caught that.

2021-08-30 16:17 UTC, mgage commented on conf/site.conf.dist
> +$mail{set_return_path}="noreply\@your.school.edu"; # or to read bounce errors set to  $mail{smptSender}
ok for text entry.  You'll need to use \@  and double quotes for "noreply\@$mail{smptServer}"

2021-08-30 16:31 UTC, drgrice1 commented on conf/site.conf.dist
> +$mail{set_return_path}="noreply\@your.school.edu"; # or to read bounce errors set to  $mail{smptSender}
That is true.  You will also need to escape the @ in that case.

2021-08-30 16:45 UTC, mgage commented
The modifications at 
after line 893 SendMail.pm
after line 949 SendMail.pm
after line 619 ProblemUtil.pm
have been made.
Some clean up of comments and indenting have been done.

2021-08-30 17:24 UTC, drgrice1 commented on conf/site.conf.dist
> +$mail{set_return_path}='noreply@math.rochester.edu'; #discards error messages
I think that by default this should probably be commented out.  Either that or it should be set to the empty string like the `$mail{smtpSender}` variable.  Your code will handle that correctly either way.

2021-08-31 12:00 UTC, pstaabp commented
Question about testing:  on a dev machine, how do you set an smtp server?  I was trying to use google, but got errors probably due to lack of authentication.

2021-08-31 12:01 UTC, pstaabp requested changes

2021-08-31 16:49 UTC, mgage commented
I'd also like to know how to set up an smtp server locally. -- I was using UR smtp server.

2021-08-31 17:07 UTC, dlglin commented
It looks like postfix is the recommended SMTP server on a linux box.

2021-08-31 17:16 UTC, drdrew42 commented
I've used postfix, but only as a relay to the campus SMTP server... I was having issues with the campus server timing out and running my own postfix allowed me to queue emails instead of having them dropped by the remote SMTP and being lost without any notification.

2021-08-31 21:32 UTC, pstaabp commented
There is a docker image on docker hub for postfix: https://hub.docker.com/r/mailu/postfix

2021-09-02 22:00 UTC, drgrice1 approved these changes
This looks good now.

2021-12-09 18:19 UTC, merged