Codemirror editor improvements.
openwebwork/webwork2 pull request #1577
Opened 2022-02-04 04:22 UTC by somiaj

The codemirror editor has addons to extend functionality, such as providing find and replace. These were meant to be enabled, but due to using local copies (and missing loading the corresponding css files) were only partly functional.

This removes the local copy of the addons, and uses the addons from the codemirror source directly and loads the required CSS files for the addons to fully function. It also creates a `htdocs/css/codemirror.css` file needed for some addons that don't include the required CSS.

In addition this enables the ability to allow browsers to spellcheck the contents of the codemirror editor as mentioned in #1539.

This was initiated due to trying to improve syntax highlighting as mentioned in <https://github.com/openwebwork/pg/issues/649>. It turns out that the syntax highlighter was already configured to show trailing white spaces at the end of lines in PGML blocks, but due to the barely functioning addons, just wasn't working. This now underlines trailing whitespace in PGML blocks without the need to load the trailing whitespace module mentioned in the issue.

2022-02-04 04:33 UTC, drgrice1 requested changes
I haven't looked closely at this at all yet, but I see one change that should be made already.  Move `htdocs/css/codemirror.css` to `htdocs/js/apps/PGCodeMirror`.

2022-02-04 04:34 UTC, somiaj commented
Note: See https://codemirror.net/demo/search.html for the key bindings for the search and find and replace features.

2022-02-04 04:40 UTC, somiaj commented
@drgrice1 done. I just wasn't sure if css should go in the js directory or not. Thanks.

2022-02-04 04:42 UTC, drgrice1 commented
Sorry, I should explain the expected layout and the reason for my request.  The `htdocs/css` directory is for generic css that is not associated with javascript.  The css that is associated with javascript should go with it in the `htdocs/js/apps` directory.  That keeps the associated code and style together, and makes it easier to find.

Thanks for moving it.

2022-02-04 04:47 UTC, drgrice1 commented
Actually, I want to delete the css directory.  All css should either be associated with javascript or be part of the theme.  The `rtl.css` was added by @taniwallach, and needs to be deleted.  Right-to-left styles should be done correctly, and should be in math4.scss using the `[dir="rtl"]` selector.

2022-02-04 04:48 UTC, somiaj commented
Note the commit comment doesn't list the actual path, a very minor inconstancy I can try to update if you like.

2022-02-04 04:49 UTC, drgrice1 commented
That is fine.  No need.

2022-02-04 06:05 UTC, somiaj commented
Opps. I had done some local editing in testing the trailing whitespace highlight and overlooked that the required CSS was missing to highlight trailing whitespace in PGML blocks. Added in previous commit.

2022-02-05 02:32 UTC, somiaj commented
Note: The ability to resize the codemirror div (last commit) doesn't work with safari in my testing, It appears to be something with the way safari handles scroll bars, and you can't click on the resize icon in the bottom right corner which is under the scroll bar.

The resize option works well in firefox and chrome, is supported by codemirror, and I think is worth enabling even if safari users can't use it. All other aspects of the editor seem to work in safari and this doesn't cause any issues I have found.

2022-02-05 15:10 UTC, pstaabp commented
A few comments here:
- I am also seeing the same issue in Safari about resizing, but not that big a deal. I don't see it as an issue on Codemirror github. 
- The search/replace works great.
- Is there a way to get jump to line on MacOS? I tried to test that.
- I'm not seeing in spellchecking on Safari.  It's working in Chrome.

2022-02-05 17:05 UTC, somiaj commented
@pstaabp The jump to line is another addon. This wasn't one of the addons that was originally meant to be enabled, so I didn't add it. If you think it is worthwhile I can also load that addon (that is why it wasn't working).

2022-02-05 22:50 UTC, pstaabp commented
> The jump to line is another addon.

I guess I was playing with a code mirror demo that had both enabled.  Most pg files are small enough that I don't think this is needed. 

About Safari, it's fine.  If we can verify that spell checking is not available in Safari, we can make a note in the release notes.

2022-02-05 22:51 UTC, pstaabp approved these changes
Looks like a nice addition.  We should make sure this get documentation/in the release notes.

2022-02-14 13:14 UTC, drgrice1 reviewed
There is a CodeMirror css style override in `htdocs/themes/math4/math4.scss`.  Either add that to your new `htdocs/js/apps/PGCodeMirror/codemirror.css` file, or instead of adding that file put those styles into `htdocs/themes/math4/math4.scss`.

Adding the spellcheck option is **not** a good idea.  You may be accustomed to ignoring its suggestions, but if there is a lot of code the suggestions are quite pervasive.  Don't assume that others are accustomed to this.  Please remove this option.  One way that this could be done is to add a checkbox below the CodeMirror textarea that when checked activates spell checking, and is not checked by default.  It could also be made so that its status is saved, and anytime the page loads it has the status it had before (check if it was, unchecked if it wasn't).  There are other options that could also be done this way.

2022-02-14 13:14 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +
Both here and in lib/WeBWorK/ContentGenerator/Instructor/AchievementEditor.pm there is some clean up needed.

First, do not add `type="text/css"` to css links.  That is not needed in modern html, and its usage is discouraged.

Now for css links, use `CGI::Link` instead of using `qq` and piecing this together.  I don't think that the previous WeBWorK developers knew about the `CGI::Link` method (I just recently found it myself), and that is why it was not used.  See the merge conflicts that this branch has to see the correct usage of that.

For the script tags, don't use `print CGI::start_script({ ... }), CGI::end_script();`.  Instead use `print CGI::script({ ... }, '');`.  It is much more succinct.  Also see the merge conflicts this branch has for the correct usage here.

If you can run perltidy on a code section in a file, then please do that to the `output_JS` methods here and in the other file.

2022-02-16 11:13 UTC, drgrice1 approved these changes
This looks good now.

The spell checking option would be nice.  I think that there are other things that could be made optional too.  For example, one could be allowed to change the Codemirror theme.  Many prefer dark backgrounds, rather than white for example.  But these things can wait for another pull request.

I will go ahead and merge this.

2022-02-16 11:13 UTC, merged