Login status show name instead of user id
openwebwork/webwork2 pull request #1647
Opened 2022-04-06 01:45 UTC by drgrice1

Make the login status next to the login button show the user's first and last name, instead of the user id.

This is also done for the effective user when an instructor is acting as a student.

2022-04-06 11:58 UTC, taniwallach requested changes
Student names are not necessarily unique.

As a result, I think that `$prettyEUserName` for the "Acting as" setting should include the `$eUser->user_id` so it provides something which cannot be ambiguous.

2022-04-06 11:58 UTC, taniwallach commented on lib/WeBWorK/ContentGenerator.pm
> +				? join(' ', $eUser->first_name, $eUser->last_name)
I would add the `$eUser->user_id` into the `join` to avoid potential uncertainly if multiple users had the same name infomation.

2022-04-06 12:00 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator.pm
> +				? join(' ', $eUser->first_name, $eUser->last_name)
Good point.  I will add the user id in parentheses for the effective user.

2022-04-06 12:10 UTC, drgrice1 commented
@taniwallach:  The user_id is now shown in parentheses after the student name for the effective user.

2022-04-06 17:56 UTC, taniwallach approved these changes

2022-04-07 12:19 UTC, pstaabp commented
Looks good.

2022-04-07 12:19 UTC, merged