Manual problem grader update scores in quizzes
openwebwork/webwork2 pull request #1709
Opened 2022-05-26 22:35 UTC by somiaj

Add the functionality for the manual problem grader to update both problem
  score tables (above and below the problems) and update the hidden score field
  when saving a new score in gateway quizzes.

2022-05-26 23:14 UTC, drgrice1 requested changes
The code that you added should be in the `success` callback of the first post request.  So after what is currently line 107 with this pull request (after line 97 in the WeBWorK-2.17 branch).  This should not occur if the saving of the score fails.

This code fails to take into account problem randomization.  If I enter a quiz that has problem randomization enabled, and then change the score for a problem using the problem grader, I see the score on some other problem number change.  Not the one that I changed the score for.  I think the only way to do this and reliably obtain the correct score for the problem is to add an `id` or identifying data attribute to the `td.score` elements in the GatewayQuiz.pm file.

2022-05-26 23:36 UTC, drgrice1 commented
@somiaj:  I added a pull request to this one that makes my suggested changes.

2022-05-27 00:37 UTC, somiaj commented
@drgrice1 thanks for the updates. Would you prefer I merged the two commits into a single commit before the final merge?

2022-05-27 00:59 UTC, drgrice1 commented
For this it is best if they are left as two.

2022-05-27 02:21 UTC, drgrice1 approved these changes
This looks good now.  Thanks.

2022-05-27 11:19 UTC, pstaabp approved these changes

2022-05-27 11:19 UTC, merged