Do not UTF-8 encode email body text.
openwebwork/webwork2 pull request #1817
Opened 2022-10-21 13:40 UTC by drgrice1

The Email::Stuffer package tries to automatically detect if the body needs to be UTF-8 encoded (either that or it just does so by default), and so if you UTF-8 encode the message first, then Email::Stuffer does it again resulting in "Mojibake".

I am putting this in as a hotfix.  I am sure @taniwallach will agree.

2022-10-22 19:15 UTC, taniwallach requested changes
@drgrice1 Thanks!

Tested and this current patch already fixes the Feedback messages. It also fixes the "report message" from the Email generation tool (such as when the course is in Hebrew so `maketext` will use Hebrew strings in the report message).

However, there is still Mojibake in the emails generated by the "Email" generation tool from the menu when Hebrew text is put in the message box. Fixing line 972 of `lib/WeBWorK/ContentGenerator/Instructor/SendMail.pm` to drop the call the `Encode::encode` seems to fix that. Could you force push the branch with that change?

I did not try to figure out how to test the message from `jitar_send_warning_email` from `lib/WeBWorK/Utils/ProblemProcessing.pm` but the code change certainly seems correct.

Thanks for figuring this out and fix the issue.

2022-10-24 15:26 UTC, drgrice1 commented
@taniwallach:  I missed the second instance of the encoding in the same file.  Thanks.  That is fixed now.

2022-10-24 17:14 UTC, taniwallach approved these changes

2022-10-25 10:42 UTC, pstaabp approved these changes
Didn't test (no email on develop machine), but code looks good.

2022-10-29 10:37 UTC, merged