Pgeditor, option to backup up files when saving.
openwebwork/webwork2 pull request #1918
Opened 2023-03-23 22:32 UTC by somiaj

When saving a file with the PG editor, a backup can be made that could be reverted to if desired. This is done by first setting the number of backups to keep. Then each time a problem is saved there is an option to create a backup of the previous saved file (defaults to yes). Backups are numbered 1, 2, 3, ..., with 1 being the most recent. Backups are saved in the `tmpEdit` directory next to the temp files.

The revert tab then has an additional option to allow users to revert to either the current live version or one of the backups. If a user selects to revert to a backup, only the temporary file is reverted, and the user will still need to save the file to make it available to students.

In addition rename "Update" as "Save" and "New Version" as "Save As" to be more standard.

2023-03-23 23:58 UTC, drgrice1 requested changes
This implementation is quite confusing and needs more work.

One of the things that is not helpful is to use a mere count to identify backups.  Adding a timestamp as suggested would help with that as it gives a more meaningful point of reference for the user to pick which backup to choose from.

Another thing that is extremely confusing is that once a backup is made, the revert form is always there.  I saved the file I was working on with a backup, and then reverted to the original file.  After doing so, not only is the revert form still there, but listed in the form is the option to revert to the original file.  Wait, I just did that.

There also needs to be some way to get rid of backups you no longer want.  Once the backups are made you get this list of backups, but no way to clean them up other than going to the file browser (or admin access file deletion of course).

2023-03-23 23:58 UTC, drgrice1 commented on templates/ContentGenerator/Instructor/PGProblemEditor/revert_form.html.ep
> +			</div>
There is a missing level of indentation here.

2023-03-23 23:58 UTC, drgrice1 commented on templates/ContentGenerator/Instructor/PGProblemEditor/save_form.html.ep
> +				class => 'form-check-label' =%>
These two lines don't need to be wrapped.  They fit into the 120 character limit without wrapping.

2023-03-23 23:58 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +sub saveFileChanges ($c, $outputFilePath, $backup) {
Add a default value for `$backup` so that you don't need to pass the argument `0` below in the cases that a backup is not provided.  Something like
```suggestion
sub saveFileChanges ($c, $outputFilePath, $backup = undef) {
```
I prefer `undef` to `0` in this case.  It is a more logical alternative to a string value that is not passed.  It doesn't change the usage in this method if it is undefined rather than zero.

2023-03-23 23:58 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +	$c->saveFileChanges($c->{tempFilePath}, 0);
No need to pass `0` if the suggested default is added.

2023-03-23 23:58 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +		$c->saveFileChanges($outputFilePath, 0);
And here also.  No need to pass `0` if the suggested default is added.

2023-03-23 23:58 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +	return unless $numberOfBackups > 0;
This return statement should be immediately after line 564 where `$numberOfBackups` is defined.  The other variables aren't needed to return.

2023-03-23 23:58 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +}
This is a convoluted scheme and involves excessive disk access.  It would be better to use a time stamp in the file name, rather than a simple number.  Something like `20230323-184633.2356` perhaps.  Then that time stamp could also be displayed in the ui select to give the user a more meaningful reference as to which backup to restore than a number that only gives an indication of order.

2023-03-23 23:58 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +		$c->saveFileChanges($c->{editFilePath}, $backup);
There is not need for the intermediary variable that is only used once.  This should be
```suggestion
		$c->saveFileChanges($c->{editFilePath}, $c->param('backupOldFile'));
```
Note there is also no need for the `|| 0` as undefined (or even the empty string) will still be logically false, and so will work the same in the `saveFileChanges` method.

2023-03-23 23:58 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +		$c->addgoodmessage($c->maketext('Deleted temporary file "[_1]".',    $c->shortPath($c->{tempFilePath})));
This reports that a temporary file is deleted even if no temporary file was deleted.  This wasn't an issue previously because the revert form was only shown if a temporary file existed.  That is not longer the case.  So more care is needed to accurately report what has happened.

2023-03-24 16:21 UTC, somiaj commented
Applied the suggested changes. Backups now use a timestamp to order them. There are now two options on the Revert tab for backups, either restore a backup or delete it. Backups are identified using the date of the timestamp formatted using the `studentDateDisplayFormat`. I did think about making a new Backup Tab for this, though unsure if one would be needed, as it does fit under the Revert tab. Maybe rename it to Revert/Backups.

When updating the message output and adding the logic of when to delete the oldest backup, I first went with changing the 'Create backup' option to 'Create backup and delete oldest backup' when the desired number of backups were reached to inform the user a backup would be deleted. I then morphed this into two options on the Save tab, that is both 'Create backup' and 'Delete oldest backup'. Where 'Delete oldest backup' is checked once the desired number of backups are reached, but the user can uncheck it if wanted.

I need to figure out how to set the param's for checkboxes and radiobuttons so they are rest to defaults when the take action (form is submitted) occurs, otherwise they keep their previous selected values.

2023-03-24 16:23 UTC, somiaj commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +		$c->addgoodmessage($c->maketext('Deleted temporary file "[_1]".',    $c->shortPath($c->{tempFilePath})));
I have fixed it so the Revert option will not show up if there isn't a temp file like the way it use to be for the revert tab. Though the only time there isn't a temp file is before the user clicks view. Should the Revert tab and/or option to revert appear when the temp file is created by viewing/reloading the file (otherwise you have to reload the page to see it)?

2023-03-24 16:38 UTC, drgrice1 commented
I think one tab is all that is needed.  This is better.  If there are backups or a temporary file is in use, then then the revert tab is shown.  Now that you have made what is shown more accurate it is less confusing.

2023-03-24 17:17 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +		$c->addgoodmessage($c->maketext('Deleted temporary file "[_1]".',    $c->shortPath($c->{tempFilePath})));
That is not quite true.  There will also not be a temporary file if the user has just reverted.  That is the case that was confusing before.

I almost implemented making the revert tab appear when viewing/reloading the file when I revising the PG problem editor.  I didn't because it is troublesome to do so.  It isn't as easy to do as you might think.

2023-03-24 17:33 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +	$c->{backBasePath}  = '';
Please change this to `backupBasePath` throughout this file.  That is a really bad shortening of `backup`.

2023-03-24 21:36 UTC, drgrice1 commented
@somiaj:  I think if you merge the two pull request I have put in to this branch, change `backBasePath` to `backupBasePath` as already mentioned, and remove the course configuration option, then this pull request is good.

I think the course configuration option is really not needed with the check boxes that give the user direct control of when a backup is made, and allows the user to delete backups.

2023-03-25 01:19 UTC, somiaj commented
@drgrice1 Accepted pull requests and fixed the variable naming. Two things:

First there is a small issue with disabling the revert radio button, is that the revert option is still selected after reverting from the temporary file. Thus if a user hits take action again it will do the revert action again before a temporary file has been selected. I think this can be fixed by moving the selected option to restore backup in this case.

Second, just to clarify on your suggestion on removing the course configuration. Do you mean just remove the ability to set the `$options{editorNumberOfBackups}` in the UI? So, keep this variable to control the number backups to keep before recommending deleting old backups, but don't give any option to modify it in the UI? Or do you mean remove this variable altogether, and let the user check when they want to delete old backups?

2023-03-25 01:30 UTC, drgrice1 commented
> > First there is a small issue with disabling the revert radio button, is that the revert option is still selected after reverting from the temporary file. Thus if a user hits take action again it will do the revert action again before a temporary file has been selected. I think this can be fixed by moving the selected option to restore backup in this case.
> 
> Hmm... I will look into that. It should not be switched to restoring a backup either. It should be set to the default view/reload.

Actually, now that I test this I see that this is not actually happening.  After reverting from the temporary file the view/reload action is enabled.  So I am not sure what you mean?

2023-03-25 01:34 UTC, somiaj commented
> Actually, now that I test this I see that this is not actually happening. After reverting from the temporary file the view/reload action is enabled. So I am not sure what you mean?

After a revert, go back to the revert tab the radio button for revert from temporary file is disabled, but still selected. So if u click Take Action from this tab, you do another revert even though there is no temporary file. Which is why I suggested to change what is selected on that tab in this case.

2023-03-25 01:35 UTC, drgrice1 commented
Yeah, I figured out what you meant.  I am looking into it.

2023-03-25 01:52 UTC, drgrice1 commented
@somiaj: I added a pull request that switches the checked radio to the backup radio after reverting the temporary file.

2023-03-25 12:47 UTC, pstaabp approved these changes
I think this looks good. This will save some of those overwrite mistakes.

2023-03-25 14:07 UTC, somiaj commented
Does anyone else have an opinion on if there should be a configuration option to control when we suggest deleting old backups like it is now, or should this just removed, and let the user manage backups fully from the editor? My original thought was something that would help keep the backups from piling up. Another option might be delete them after they are X-time old.

2023-03-25 14:14 UTC, pstaabp commented
> Does anyone else have an opinion on if there should be a configuration option to control when we suggest deleting old backups like it is now, or should this just removed, and let the user manage backups fully from the editor? My original thought was something that would help keep the backups from piling up. Another option might be delete them after they are X-time old.

Although I didn't test this.  Let's say you select 2 automatic backups.  If you have saved a file 3 times, that there is the current file and two backup files.  If you save another time, the oldest is deleted.  Is this not how the current branch works?

2023-03-25 14:26 UTC, somiaj commented
> Although I didn't test this. Let's say you select 2 automatic backups. If you have saved a file 3 times, that there is the current file and two backup files. If you save another time, the oldest is deleted. Is this not how the current branch works?

Correct, currently if you set it to 2 backups, and you currently have 2 (or more) backups, the editor will automatically check the 'delete oldest backup' option when saving, which will make it so you when you save a file you can both create and delete a backup, thus keeping the number of backups from piling up if you save a lot.

@drgrice1 suggested just removing this altogether, since the backups can be manged and deleted from the editor, which will no longer automatically delete any and require the user manually delete old backups.

I do like the idea of not letting backups build up, but the simple 'keep N backups' has its flaws if someone saves and backups the file a lot. So the suggestion is to remove that whole feature (including the 'delete oldest backup' check box) and just let users delete backups when they want (which my guess is most won't and they will pile up).

2023-03-25 15:55 UTC, drgrice1 commented
I did not say to remove the delete oldest backup checkbox. I only said to remove the limit on the number of backups which is completely misleading. The point is that when you have the delete oldest backup checkbox which gives the user the option to override the limit the option is rather pointless. That option is a soft limit.  If one wants to limit backups they only need to keep the save back up and delete oldest back up checkboxes both checked.

2023-03-25 16:03 UTC, Alex-Jordan commented
My two cents. Go with the simple 'keep N backups' model. It's already
infinitely many times more backups than we currently do. And I think we
could replace this with a versioning approach, given more time to develop
it. And then some issues go moot, since versioning can be way more
efficient than backup copies.

On Sat, Mar 25, 2023, 8:56 AM Glenn Rice ***@***.***> wrote:

> I did not say to remove the delete oldest backup checkbox. I only said to
> remove the limit on the number of backups which is completely misleading.
> The point is that when you have the delete oldest backup checkbox which
> gives the user the option to override the limit the option is rather
> pointless. That option is a soft limit. If one wants to limit backups they
> only need to keep the save back up and delete oldest back up checkboxes
> both checked.
>
> —
> Reply to this email directly, view it on GitHub
> <https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3132feb7-454455535732-be3223ebd5dc7af2&q=1&e=b58f8697-a197-4f66-a499-bca6d629903e&u=https%3A%2F%2Fgithub.com%2Fopenwebwork%2Fwebwork2%2Fpull%2F1918%23issuecomment-1483856413>,
> or unsubscribe
> <https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3132feb7-454455535732-bde8b2fafdcb4a56&q=1&e=b58f8697-a197-4f66-a499-bca6d629903e&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABEDOAABQLYGLUTG4VSXVBDW54IRFANCNFSM6AAAAAAWF2AHOM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-03-25 16:26 UTC, drgrice1 commented
The thing is that the 'editorNumberOfBackups' option is not a 'editorNumberOfBackups' option.  It should be renamed to 'editorNumberOfBackupsBeforeSuggestingALimit' option.  The option does NOT limit the number of backups.  I am saying remove the option, and let the user choose the number of backups to keep.  Once the user reaches the number of backups they want, then they check the 'Delete oldest backup' check box.  That truly does limit the number of backups.  On the other hand, if a user wants no limit, the user simply needs to not check that check box.  If the user doesn't want any backups, then uncheck the 'Save backup' check box, and no backups will be saved.  The check boxes will stay in the state the user sets them to.  Everything can be done with the check boxes as implemented, and the course config option is redundant.

Implementing an actual versioning system would be better in any case.  One way this can be done is by using local a git repository that is created and updated automatically by the server when saving.

2023-03-26 14:10 UTC, drgrice1 commented on conf/defaults.config
> +					. 'the problem editor, backup previous file and delete oldest backup. This sets the number of backups '
This line exceeds the 120 character limit.  I added a pull request that fixes this.  See https://github.com/somiaj/webwork2/pull/8.  Either merge that, or just fix it yourself if you like.

2023-03-26 19:50 UTC, somiaj commented
I removed the course configuration option, and users can just manage the backups from the editor page.

2023-03-26 23:54 UTC, drgrice1 reviewed
Something isn't right now.  Now no backups are saved regardless of if 'Create backup' is checked or not.

2023-03-26 23:54 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +		my $backupTime       = @backupTimes[$#backupTimes];
This should be
```suggestion
		my $backupTime       = $backupTimes[-1];
```
`@backupTimes[$#backupTimes]` gives a warning.
Changing that to `$backupTimes[$#backupTimes]` will work without warning, but perlcritic will complain and say you should use -1 for the index.

2023-03-26 23:56 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
> +}
This method does not end with return.

2023-03-27 00:55 UTC, somiaj commented
Okay, it should work now. I missed adding a file to the previous commit, but it was working for me since I still had the old variable in my simple.conf file. Now that I added removing the check for the option it is working again.

2023-03-27 01:21 UTC, drgrice1 approved these changes
Everything seems to be working now.  Looks good.

2023-03-30 18:11 UTC, merged

2023-07-11 19:55 UTC, Alex-Jordan commented
Recent work with hardcopy themes has me poring over the editor interface. I noticed that it is a little weird that when you want to delete backups, you choose the radio button for deleting a backup and then you click the `Revert` button. (Maybe at the time this was written, the button still said `Take Action!`.)

I can't think of a quick and easy way to make this more smooth (or I would just do it an open a PR). We could live with it, or maybe someone else has an idea.