Header footer
openwebwork/webwork2 pull request #2049
Opened 2023-06-13 21:36 UTC by Alex-Jordan

This is on top of #2032.

It removes `hardcopySetFooter.pg`, so the only PG problem associated with a hardcopy infrastructure is the header file. It's replaced with a tex file for the footer of a set.

It brings back `hardcopySetHeader.tex`, which I think @drdrew42 recently retired. But read on...

Now `Hardcopy.pm` writes LaTeX macros for various environment variables you might want to call in the LaTeX infrastructure. So for example `hardcopySetHeader.tex` can use things like `\webworkFirstName` to get the first name of the user. And we don't need a lot of tex-specific stuff in the PG header file.

This also allows `hardcopySetHeader.tex`  to start two column mode after the PG header file is run, so the header content can still be in the one-column portion of the PDF. Then `hardcopySetFooter.tex` closes two column mode, if needed.

I haven't tested against the XeLaTeX themes, but I tested with oneColumn and twoColumn.

Here is a screenshot to see a sample. Maybe I was too radical rearranging header and footer items, but it's a starting point.
<img width="1059" alt="Screen Shot 2023-06-13 at 2 32 50 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/db18a8d6-8eb7-4319-ac25-e065b260cdd3">

This also changes the text of the copyright footer and makes it a running footer, not just a footer for the last page/problem.

<img width="1070" alt="Screen Shot 2023-06-13 at 2 35 46 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/265245e4-1fcf-4b20-8b41-d0a145bcc483">

2023-06-13 23:56 UTC, Alex-Jordan commented
I'm trying to test this out with the xelatex themes. But something is either broken with how hardcopy themes are handled, or I need help identifying user error.

I have changed localOverrides to have:
```
$externalPrograms{pdflatex} ="/usr/local/texlive/2023/bin/x86_64-linux/xelatex --no-shell-escape";

# Available Hardcopy themes (located in snippets)
# (their "internal" name and their pretty name for end users)
$hardcopyThemeNames = {
        #oneColumn => 'One Column',
        #twoColumn => 'Two Columns',
        XeLaTeX-oneColumn => 'English - one Column',
        XeLaTeX-twoColumn => 'English - two Columns',
        XeLaTeX-Hebrew-oneColumn => 'Hebrew/English - one Column',
        XeLaTeX-Hebrew-twoColumn => 'Hebrew/English - two Columns',
};

# This is needed to enforce an order that the options are presented when making a hardcopy
$hardcopyThemes = [
        #'oneColumn',
        #'twoColumn',
        'XeLaTeX-oneColumn',
        'XeLaTeX-twoColumn',
        'XeLaTeX-Hebrew-oneColumn',
        'XeLaTeX-Hebrew-twoColumn',
];


# Change default Hardcopy theme
# Be sure to choose one that is enabled!
$hardcopyTheme = "XeLaTeX-oneColumn";
```

For good measure I ran `npm ci` and restarted `webwork2`, although I wouldn't think that should matter for config files. I checke that my course's `course.conf` and `simple.conf` have nothing to do with the config settings above. And yet I see this in Course Config:
<img width="752" alt="Screen Shot 2023-06-13 at 4 51 59 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/1937507d-f37d-4eec-8827-64f61e4b5a9e">

where it only wants to offer me the two options from `defaults.config`, which  Ih ave commented out in `localOverrides.conf`.

And if I go to a screen where I would build a hardcopy, I see:
<img width="602" alt="Screen Shot 2023-06-13 at 4 53 52 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/c0b5d248-6cce-4722-a6ca-f3d72e5c79ef">

With no labels on the four options.

2023-06-14 00:05 UTC, Alex-Jordan commented
Thanks, that fixes the second issue. I'll add quotes to the distro config files where they are needed for this.

But this is not affecting the dropdown menu I see in Course Config.

2023-06-14 00:12 UTC, drgrice1 commented
Hmm, there does seem to be an issue there.  If I uncomment the lines in defaults.config, then the other themes show up, but it doesn't get the definition from localOverrides.conf.

2023-06-14 00:22 UTC, Alex-Jordan commented
> Thanks, that fixes the second issue. I'll add quotes to the distro config files where they are needed for this.

Looks like you already did that, but I still had a `localOverrides.conf` from earlier. I did change it in the commented out place in `defaults.config` though.

2023-06-14 00:29 UTC, Alex-Jordan commented
I tested the hardcopy with XeLaTeX options. I had no trouble with the English options, but the Hebrew has a few problems. However it could just be that I'm missing the right fonts. @taniwallach, would you test them when you have a chance?

2023-06-14 17:48 UTC, Alex-Jordan commented
I should explain more about what this would change. There are reasons to object that I respect. The current model in 2.18 is:

```
 harcopyPreamble.tex
---- now loop over all set+user combinations being processed -----
set header PG file (not part of the theme)
the problem file
hardcopySetFooter.pg
--------------------------------------------------------------------
 harcopyPostamble.tex
```

I think it is a sign that the model is not great that there is a footer _PG file_ which only serves the purpose of providing something that TeX output needs (the distribution version is only providing the copyright statement).

Also because `harcopyPreamble.tex` ends by starting two-column mode, now if you want the header PG content to be one-column, you have to be aware of this when writing that header file and using things like `$BEGIN_ONE_COLUMN`. Ideally the set header author would just be writing information about the problems in the set and a pedagogical description of the set, etc., not having to thing about how the theme could affect what they are writing.

This PR changes the model to:
```
 harcopyPreamble.tex
---- now loop over all set+user combinations being processed -----
set header PG file (not part of the theme)
hardcopySetHeader.tex
the problem file
hardcopySetFooter.tex (note tex, not pg)
--------------------------------------------------------------------
 harcopyPostamble.tex
```

And the theme's `hardcopySetHeader.tex` and `hardcopySetFooter.tex` handle entering/exiting two-column mode if that is what the theme wants to do. The header PG file will  always be one-column.

Additionally, the theme file `hardcopySetHeader.tex` can handle some things that have traditionally gone into the header PG file, but are not really part of giving information about the exercises in the set. I mean things like the user's name, the set's due date, etc. That framework can now go into the theme file `hardcopySetHeader.tex`. This is possible because of a change where you no longer need PG to access things like the user's name or the due date. Those things are now written as LaTeX macros like `\webworkFirstName`, etc., redefined with each loop over the set+user combinations. So the tex files in the theme can just call them that way.

This leaves things such that the set header PG file can focus on only describing the nature of the exercises or the set as a whole, independent of output format. (It can still be used to make changes to the PDF, by overriding things from `harcopyPreamble.tex` if that is desired. How to do this is left, commented out, in `ASimpleCombinedHeaderFile.pg`.)

One thing with the new themes that is a visually apparent change, is that I put the copyright line at the end of every page, as a running footer defined in `harcopyPreamble.tex`. If that is not wanted, it could be moved to `hardcopySetFooter.tex`.

Another thing with the new themes that is a visually apparent change, is that I rearranged things you will see in the header. This was in part to accommodate printing the section and recitation when they exist. But can be changed of course

Another thing people may object to: if you use the new two-column theme here together with an old set header file that uses `$BEGIN_ONE_COLUMN`, `$END_ONE_COLUMN`, then you it does not come out well in several ways. This would mean some work for people who have set headers that use `$BEGIN_ONE_COLUMN`, `$END_ONE_COLUMN` and need to update them. If it is a bigger problem than I realized, I can understand that.

2023-06-14 21:37 UTC, drgrice1 requested changes
I am not certain that I like moving the header definitions into the hardcopyPreamble.tex file.  It certainly seems out of place there.  You can override some of those things in the set header PG file, but that is messy.  The resulting TeX file is really a mess with the changes introduced in this pull request, and if an instructor overrides the headers it only adds to the kludge.

Note that eventually PG will no longer honor any of the things that are being passed in for set headers only.  The standalone renderer does not support them, and neither will webwork3.  One approach would be to take the approach of writing things as LaTeX macros as you have done here much further and instead of having a PG set header at all, have a tex set header.  Something separate will need to be done for the HTML set header probably.

2023-06-14 21:37 UTC, drgrice1 commented on conf/snippets/hardcopyThemes/oneColumn/hardcopySetFooter.tex
> +% \webworkDueDate, \webworkAnswerDate, \webworkSetHeader, \webworkHardcopyHeader, \webworkDescription
I don't understand why these comments need to be added in all of these TeX files and thus added to the single hardcopy.tex file that is generated, and repeated for each set and student.  These comments are also in the default set header which is really the only place that this is needed.  Perhaps it is okay in the hardcopyPreamble.tex file.  Someone that uses the TeX source option can then see it still numerous times in the output.

2023-06-14 22:34 UTC, Alex-Jordan commented on conf/snippets/hardcopyThemes/oneColumn/hardcopyPreamble.tex
> +\ifdefined\nocolumns\firstpageheadrule\fi
> I am not certain that I like moving the header definitions into the hardcopyPreamble.tex file. It certainly seems out of place there. 

I don't see what you mean. The tex preamble is the usual place in a tex file to set up page headers and footers. Maybe you mean that it is weird to set them up in the preamble, beceause they should change their content as we enter new set+user combinations. But that works out since the macros like `\webworkFirstName` are employed, and they get redefined. It's like setting up a header and using `\thechapter` somehow if you were writing a book.

> You can override some of those things in the set header PG file, but that is messy.

That is how headers/footers are set, ever since moving to the exam class. The new (prior to this PR) `ASimpleCombinedHeader.pg` does that [here](https://github.com/openwebwork/webwork2/blob/2279ecca464c35ee303dd6f26be30d47d38fe252/conf/snippets/ASimpleCombinedHeaderFile.pg#LL88C1-L105C40). So prior to this PR, you either have to set headers and footers in the PG header file, or not have them at all.

Now with this change, you can either (a) not worry about headers and footers in your PG header file, and run with the theme's default for headers and footers. Or (b) customize them in the PG header file. But you would have to do that anyway prior to this.

> I don't like that this rule is here.

This is something taken from the current PG header file, without thinking about it enough. Since it can't be removed by customizing the PG header file, it should be removed.

2023-06-14 22:36 UTC, Alex-Jordan commented on conf/snippets/hardcopyThemes/oneColumn/hardcopySetFooter.tex
> +% \webworkDueDate, \webworkAnswerDate, \webworkSetHeader, \webworkHardcopyHeader, \webworkDescription
Yeah, it does make the tex file messy. I had a mind to help people create their own hardcopyTheme. So if you were creating a new `hardcopySetFooter.tex` in a new theme, you could copy this and the comments help you see what tools are available. But I could move that into some better place for guiding people who want to write a new hardcopyTheme.

2023-06-14 22:43 UTC, drgrice1 commented on conf/snippets/hardcopyThemes/oneColumn/hardcopyPreamble.tex
> +\ifdefined\nocolumns\firstpageheadrule\fi
> I don't see what you mean. The tex preamble is the usual place in a tex file to set up page headers and footers. Maybe you mean that it is weird to set them up in the preamble, beceause they should change their content as we enter new set+user combinations. But that works out since the macros like `\webworkFirstName` are employed, and they get redefined. It's like setting up a header and using `\thechapter` somehow if you were writing a book.

In the sense of setting headers and footers, you are correct that the usual place for that would be the preamble.  In the sense of its usage here for each set and student though, it is not.  Generally what is odd here is the usage of headers and footers in this way since switching to the exam class as you said.
 
> > I don't like that this rule is here.
> 
> This is something taken from the current PG header file, without thinking about it enough. Since it can't be removed by customizing the PG header file, it should be removed.

This is my biggest problem with this pull request at this point.

2023-06-14 22:48 UTC, drgrice1 commented on conf/snippets/hardcopyThemes/oneColumn/hardcopySetFooter.tex
> +% \webworkDueDate, \webworkAnswerDate, \webworkSetHeader, \webworkHardcopyHeader, \webworkDescription
Creating custom themes is something that should be documented on the wiki, but including these comments in each TeX file doesn't necessarily help that much.  Generally speaking if the themes are well designed to begin with there isn't a need to create custom themes.  I have never had the need to do so before for my usage.

2023-06-15 19:10 UTC, Alex-Jordan commented
@taniwallach Could you look at the files:

```
conf/snippets/hardcopyThemes/XeLaTeX-Hebrew-*/hardcopyPreamble.tex
conf/snippets/hardcopyThemes/XeLaTeX-Hebrew-*/hardcopySetFooter.tex
```

and look at these blocks in those respective files:
```
\pagestyle{headandfoot}
\firstpageheader%
{{\large\bfseries Assignment \webworkSetId{}\\}\ifx\webworkReducedScoringDate\empty\else{full credit by \webworkReducedScoringDate, }\fi closes \webworkDueDate\\{\href{\webworkCourseURL}{\scshape\webworkCourseTitle}}}%
{}%
{{\large\bfseries\webworkFirstName{} \webworkLastName\\}%
\ifx\webworkSection\empty{\ \\}\else{Section: \webworkSection\\}\fi%
\ifx\webworkRecitation\empty{\ }\else{Recitation: \webworkRecitation}\fi%
%\ifx\webworkSection\empty{\ifx\webworkRecitation\empty{\\}\fi}\fi%
}%
\runningheader{}{}{}
\footer{}{}{Page \thepage}
```

```
\footer{}{\small Generated by WeBWorK, \copyright The WeBWorK Project, https://openwebwork.org}{Page \thepage}
```

and there are words, phrases, punctuation, and ordering where we should have it right in Hebrew.

2023-06-15 19:10 UTC, Alex-Jordan commented on conf/snippets/hardcopyThemes/oneColumn/hardcopySetFooter.tex
> +% \webworkDueDate, \webworkAnswerDate, \webworkSetHeader, \webworkHardcopyHeader, \webworkDescription
I removed all these comments.

2023-06-15 19:11 UTC, Alex-Jordan commented on conf/snippets/hardcopyThemes/oneColumn/hardcopyPreamble.tex
> +\ifdefined\nocolumns\firstpageheadrule\fi
I removed this horizontal rule.

2023-06-15 20:14 UTC, Alex-Jordan commented
Questions for everyone. As I have the theme header now, the information provided is:

* User first and last name
* Section (if there is one)
* Recitation (if there is one)
* Assignment name
* Reduced credit date (if there is one)
* Close date
* Course Title, which is a hyperlink to the course address

1. Should the user ID be there too? Like `Alex Jordan (alex.jordan)`?
2. Should the link go to the course, or all the way to the assignment page?
3. Thoughts on branding? I could make these PDFs have a WeBWorK logo somewhere. Tastefully, I'm sure.

2023-06-18 19:59 UTC, Alex-Jordan commented
This has a few more things now. But two things are still needed:

- Hebrew translations for the Hebrew theme header and footer.
- The sets that come with modelCourse use PG set headers that still use `$BEGIN_ONE_COLUMN`, which then causes a problem if a two-column theme is used. I have in mind to replace those sets. There should be a demo set showing off some things WeBWorK/PG can do, but including one or two problems with very simple code. Together I think these would replace the functionality of the current four. I will probably do this in a separate branch built off of this one.

2023-06-18 23:16 UTC, Alex-Jordan commented
Here is what this looks like now. I'm going to stop tweaking it until people have time to review it. Except possibly for the Hebrew translations. If the user had a section or recitation, that would display under their name.

<img width="1045" alt="Screen Shot 2023-06-18 at 4 14 47 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/1b10f8b6-de3a-4c4e-bf30-2ffb38bd3abc">

----

<img width="1045" alt="Screen Shot 2023-06-18 at 4 09 44 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/7bca5e5c-0889-44c9-9e63-ba5d1fa65b86">

----

<img width="1045" alt="Screen Shot 2023-06-18 at 4 09 53 PM" src="https://github.com/openwebwork/webwork2/assets/4732672/e039a26d-94dc-4858-b215-ef6662d51d0e">

2023-06-20 11:05 UTC, drgrice1 approved these changes
I think this looks okay now.

2023-06-20 15:03 UTC, pstaabp approved these changes
Looks good now.

2023-06-20 15:04 UTC, merged

2023-06-20 16:26 UTC, Alex-Jordan commented
It's OK this is merged, but we still need Hebrew translations for a few things with the Hebrew hardcopy themes when @taniwallach can return to that.

2023-06-20 17:48 UTC, pstaabp commented
I just tried to do a hardcopy inside the PGeditor, and came up with errors such as 
```
! Undefined control sequence.
<argument> \scshape \webworkCourseTitle 
```
For all of these variables.  

I was thinking this may be correct in that this was from a library (the sample problems) and not associated with a set.  If so, we should have a simpler theme for single problems within the PGeditor.

2023-06-20 18:11 UTC, Alex-Jordan commented
Did you restart webwork2? The Hardcopy module now defines those macros as it writes the tex preamble. What does your tex file look like for a hardcopy?

2023-06-20 18:56 UTC, Alex-Jordan commented
OK, I see what you mean. I'll look into this.

On Tue, Jun 20, 2023 at 10:49 AM Peter Staab ***@***.***>
wrote:

> I just tried to do a hardcopy inside the PGeditor, and came up with errors
> such as
>
> ! Undefined control sequence.
> <argument> \scshape \webworkCourseTitle
>
> For all of these variables.
>
> I was thinking this may be correct in that this was from a library (the
> sample problems) and not associated with a set. If so, we should have a
> simpler theme for single problems within the PGeditor.
>
> —
> Reply to this email directly, view it on GitHub
> <https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3132feb7-454455535732-c2c934c032eac0f9&q=1&e=d92293a2-e121-464a-b791-0d9998b11b2d&u=https%3A%2F%2Fgithub.com%2Fopenwebwork%2Fwebwork2%2Fpull%2F2049%23issuecomment-1599248114>,
> or unsubscribe
> <https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3132feb7-454455535732-47f59cb1cf09f95c&q=1&e=d92293a2-e121-464a-b791-0d9998b11b2d&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABEDOAH6KDCS6XR3OYP7VJDXMHPAXANCNFSM6AAAAAAZFO3ODI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Alex Jordan
Mathematics Instructor
Portland Community College

2023-06-20 20:31 UTC, drgrice1 commented
I forgot to test this with this pull request.

The problem editor uses HardcopyRenderedProblem.pm for hardcopy generation.  It also uses the TeX preamble and postamble, and it does not write those TeX definitions.  It also won't really have most of the information for those, and shouldn't set the headers.  I don't think that the headandfoot.tex inclusion is going to work in the preamble.

This also breaks the two column theme with the pg problem editor hardcopies.  This is because two column mode is no longer set in the preamble, but in the set header.  The set header is not used by HardcopyRenderedProblem.pm.

2023-06-20 20:42 UTC, Alex-Jordan commented
Is there a reason to want to apply the usual hardcopy themes to a hardcopy-rendered-problem from the editor? Or was it just easier to plug into those? Could I change HardcopyRenderedProblem.pm to just use a stripped down "theme"?

2023-06-20 20:44 UTC, drgrice1 commented
Yes, then you can see what the problem would look like rendered in a single column of the page.  The UI is designed for this.  So you would also have to remove the select that chooses the theme.

2023-06-20 20:50 UTC, drgrice1 commented
I also don't like creating another custom stripped down theme for this.  There is already enough redundancy in files with the hardcopy theming system.

2023-06-20 21:13 UTC, Alex-Jordan commented
What if I add theme's tex header and tex footer to `HardcopyRenderedProblem.pm`, so that two-column is restored?

And add the definitions for `\webworkCourseTitle`, etc, there as well? (Writing them empty when the information is absent.)

2023-06-20 21:14 UTC, drgrice1 commented
See #2070 for a starting point for fixing things.

2023-06-20 21:16 UTC, Alex-Jordan commented
Oh I see you have done that. Do you prefer having all of the TeX commands be dummies? I could make the course-wide ones really work. And maybe the user-specific ones, using the problem author as the user.

2023-06-20 21:17 UTC, drgrice1 commented
To make set headers somewhat work, at least some of the macros should have actual values.