pick and choose permission levels to receive feedback
openwebwork/webwork2 pull request #2117
Opened 2023-07-16 07:29 UTC by Alex-Jordan

This is an alternative to #1598. It allows you to set `$permissionLevels{receive_feedback} = ['ta', 'professor']` so that only those specific roles can receive feedback. There is no change in behavior if you use a string: `$permissionLevels{receive_feedback} = 'ta'` still means "ta and above".

I copied `checkboxlist.pm` to `permission_checkboxlist.pm` and tweaked it to work specifically for the list of permissions. I am unsure if that left some things present that are not needed.

Perhaps this is a model for any other permissionLevels where it would be better to allow you to pick and choose the roles instead of going with one role and above. Off the top of my head I can't think of another permissionLevel where you'd want this though.

2023-07-16 20:36 UTC, Alex-Jordan commented
BTW, my thinking with making `permission_checkboxlist.pm` was that maybe this technique would be applied to more permissions in the future, and it would be useful to have that. But if this ends up only being good for `receive_feedback` then it is unnecessary and it could just use the existing `checkboxlist.pm`.

I'm interested in cleaning house with old PRs, and that led to this. #1598 has a reasonable underlying motivation, but I don't think it's best to have competing permissions like happens there. It's too easy to be confused when you change one and don't understand why you don't get the behavior you want, all because you are just unaware of the opposing permission.

2023-07-19 11:29 UTC, drgrice1 requested changes
This has some things that need to be changed.  See the comments in the code.

I certainly think this is a better approach than adding a conflicting permission as in #1598.

2023-07-19 11:29 UTC, drgrice1 commented on lib/WeBWorK/Utils.pm
> +	my ($c, $role) = @_;
It would probably be better to make the first parameter here the course environment directly, since that is all that is needed for this method.  That means it can not be called as a package method, and it instead will need to be called as `role_and_above($ce, $role)`.  Then `role_and_above` should not be imported into the `WeBWorK::ContentGenerator::Feedback` module.

Or perhaps even better and more direct would be to only pass in a reference to the course environment `userRoles` array since in reality that is all this method needs.

2023-07-19 11:29 UTC, drgrice1 commented on lib/WeBWorK/Utils.pm
> +	}
This should be changed to
```suggestion
	my @rolePermissionLevels = map { $ce->{userRoles}{$_} } grep { defined $ce->{userRoles}{$_} } @$roles;
	return unless @rolePermissionLevels;

	my $user_ids = [ map { $_->user_id } $db->getPermissionLevelsWhere({ permission => \@rolePermissionLevels }) ];
```
This is will get the same user ids from the datbase, and is more efficient as it is a single database query.

By the way, your original query could have been `$db->getPermissionLevelsWhere({ permission => $ce->{userRoles}{$role} })`.  Equality is the default, and does not need to be passed.  To go the other direction with my suggested query, it could also be `$db->getPermissionLevelsWhere({ permission => { '=' => \@rolePermissionLevels } })`.

2023-07-20 00:42 UTC, Alex-Jordan commented
Thanks for your review. I made all those changes and just pushed. I tested and it still works in both config page and actually sending emails to the right users.

2023-07-20 01:19 UTC, drgrice1 approved these changes
Looks good.  Thanks for making the changes.

2023-07-20 11:16 UTC, pstaabp commented on lib/WeBWorK/ConfigObject/permission_checkboxlist.pm
> +# Copyright &copy; 2000-2021 The WeBWorK Project, https://github.com/openwebwork
Update this copyright date.

2023-07-20 11:16 UTC, pstaabp approved these changes
Looks good.

2023-07-20 18:18 UTC, merged

2023-08-08 04:22 UTC, somiaj commented
I keep running into issues due to this change.  If you have a course which has set `$permissionLevels{receive_feedback}` in the course configuration page via `simple.conf` in the past (so the variable is a string) then this change makes it so the course configuration page errors out when trying to save any configuration tab except the email tab, because `$permissionLevels{receive_feedback}` is a string and not an `ARRAY`.  In essence, the course configuration page is broken until you update this configuration option to be an `ARRAY` in `simple.conf` if it is there.

It might be a bit late for this now, and now that I know what the issue is I can fix it with my courses, but it might be worth thinking about this for other users who may run across this issue.

2023-08-08 04:26 UTC, somiaj commented
To see the issue I just mentioned above, find a course and add a single line `$permissionLevels{receive_feedback} = 'nobody';`, then go to any configuration tab except the email tab and hit save changes, and you'll see an error about `'nobody'` not being an array reference.

2023-08-08 10:38 UTC, drgrice1 commented
@somiaj:  If the course configuration page errors out, then a hot fix is needed.  If you have a fix, then could you please make a pull request?

2023-08-08 11:40 UTC, drgrice1 commented
@somiaj: Nevermind, it seems that @Alex-Jordan has made a pull request to address this.