Send Email Notification for Achievements
openwebwork/webwork2 pull request #2214
Opened 2023-09-18 20:55 UTC by drdrew42

## New Achievement Feature

This PR enables email notifications on a per-achievement basis.

Each achievement can be paired with an email template that will be filled out and sent to the student when they earn the achievement.

The email template itself is a hybrid of `Mojo::Template` and our own email template system (as implemented on the Email page). A default template (default.html.ep) must be present in the `[TMPL]/achievements/` folder. This file is provided in courses.dist/achievements/

I have left the template as an HTML template, in case there is desire to support MIME::HTML email messages.

To enable an email notification:
* the site.conf (or course.conf, at least) must have nonempty `$mail{smtpSender}` or `$mail{set_return_path}`
* the default.html.ep must be copied from `courses.dist/achievements/` into the `[TMPL]/achievements` folder (I'm hoping that #2173 will help ensure this happens)
* achievements must be enabled in course config
* import and assign default_achievements.axp (or whatever else you might have)
* head to the Achievement List page and click "Enable Email Notification" (this should default to default.html.ep)
* make modifications to the template or "use existing template" default.html.ep

Once enabled, the email notification can be disabled by clicking into "Edit Email Template" and selecting the "Disable Notifications" tab.

2023-09-19 14:23 UTC, pstaabp commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
>  				$$data[$i] =~ s/^\s+//;
If you are checking if the length is 7, then the indices will be 0..6, so isn't `$$data[7]` undefined?

2023-09-19 14:38 UTC, drdrew42 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
>  				$$data[$i] =~ s/^\s+//;
Something was/is weird here. 

The old check used up to `$$data[7]`  if length was 9, and used up to `$$data[9]` otherwise.

I honestly think we should deprecate the use of 'old' achievement files for import and focus on using the current format. Shall we call for a vote? 😛

2023-09-29 11:31 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
>  				$$data[$i] =~ s/^\s+//;
Clearly the old code was messed up here.  A current achievement import file should have 10 fields in each row (prior to this pull request).  So if two fields were added (one for assignment_type and one for number), then previously there would have been 8 fields, not 9 or 7.  The code is consistent with this in terms of which indices of the `$data` array are accessed.  So clearly the check should be `if (@$data == 8) {`.

I am fine with deprecating the usage of the "old" achievement files.  The error in the conditional means that those files have not been working anyway.  With the previous condition of `@$data == 9` the code for dealing with the "old" files would never have been executed.  With the new condition of `@$data == 7` it will still not be executed.  This means that if one of these "old" files were imported all of the fields would have been put into the wrong achievement columns, and most likely there would be errors.  Since this has been this way since 2015, most likely no one has any of these "old" files anymore.  Just drop that code.

2023-09-29 13:38 UTC, drgrice1 reviewed
There is quite a bit of clean up needed.  Most of this is the result of copying the `AchievementEditor.pm` file and its related files which also need a lot of clean up.  Since these are new files, it would be good to add them already cleaned up.

2023-09-29 13:38 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementNotificationEditor.pm
> +		$c->{failure} = 1;
Delete `$c->{failure}` everywhere.  It is only used locally, and it will be true if and only if `$writeFileErrors` is true.  So it is not needed.

2023-09-29 13:38 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementNotificationEditor.pm
> +	my $achievementName = $c->{achievementID};
Delete these variables.  They are not used anywhere in this method.

2023-09-29 13:38 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementNotificationEditor.pm
> +		$ce->{courseDirs}{achievements} . "/$template_filename";
This should be one line.

2023-09-29 13:38 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementNotificationEditor.pm
> +use File::Copy;
Unless I am missing something, these modules are not used in this package.  So these lines should be removed.

2023-09-29 13:38 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementNotificationEditor.pm
> +use constant DEFAULT_ICON => 'defaulticon.png';
This constant is not used by this module.  So this line should be deleted.

2023-09-29 13:38 UTC, drgrice1 commented on templates/ContentGenerator/Instructor/AchievementList/default_table.html.ep
> +						) =%>
Rather than using an intermediate variable once, do
```suggestion
						<%= link_to $c->systemLink(
							url_for('instructor_achievement_notification', achievementID => $achievement_id)
						), begin =%>
							<%= $_->email_template
								? maketext('Edit Email Template')
								: maketext('Enable Email Notification') =%>
						<% end =%>
```
The existing code also had an indentation issue, and a line that exceeded the 120 character limit.

2023-09-29 13:38 UTC, drgrice1 commented on templates/ContentGenerator/Instructor/AchievementNotificationEditor/save_as_form.html.ep
> +% # You can replace the current achievement, use it in a new achievement, or not use it at all.
Either update these comments for the notification editor, or delete them.

2023-09-29 13:38 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementNotificationEditor.pm
> +WeBWorK::ContentGenerator::Instructor::AchievementNotificationEditor - edit an achevement evaluator file
This line should be updated for the notification editor instead of the evaluator editor.

2023-09-29 13:38 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementNotificationEditor.pm
> +		}
This is a good candidate for using the `die ... unless ...` syntax instead.

2023-10-06 17:00 UTC, drdrew42 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementEditor.pm
> +use WeBWorK::Utils qw(fix_newlines not_blank path_is_subdir x);
This is my mistake with the new `fix_newlines`, I thought I'd included "?" in the regex: `/\r\n?/\n/`

I'll update the util method.

2023-10-06 17:03 UTC, drdrew42 commented on templates/ContentGenerator/Instructor/AchievementList/default_table.html.ep
> +						) =%>
I had a tough time making this ternary work embedded in the link_to... thanks for finding the begin/end approach.

2023-10-06 20:31 UTC, drdrew42 commented
Okay, I think that all of the feedback has been resolved. In multiple places:
* extra dereferencing arrows are removed
* stash values are not duplicated on the controller
* ui messages are passed through maketext

Also, cleanup of conditionals (e.g. not checking conditions that already returned early); removal of unused variables and modules; and related template cleanup.

2023-10-12 02:30 UTC, drgrice1 reviewed
There are a few more things I observed in the code.   I also got to testing functionality, and I am seeing some warnings.

First, I am getting `Use of uninitialized value $val in pattern match (m//) at /usr/share/perl5/Email/MIME/Encode.pm line 36.` warnings anytime an email is sent by the `send_achievement_email` task.  I am not sure what is causing that exactly.  This does not happen with the `send_instructor_email` task.

2023-10-12 02:30 UTC, drgrice1 commented on lib/WeBWorK/AchievementEvaluator.pm
> +					nextLevelPoints => $nextLevelPoints,
I am getting the warning `Argument "" isn't numeric in subtraction (-) at /opt/webwork/courses/myTestCourse/templates/achievements/default.html.ep line 7.` when an achievement is earned that is not a level achievement.  It may also because in testing I have just reassigned all achievements, and the user does not have any achievement points yet.  In any case, I think this needs to be
```suggestion
					nextLevelPoints => $nextLevelPoints || 0,
```

2023-10-12 02:30 UTC, drgrice1 commented on templates/ContentGenerator/Instructor/AchievementNotificationEditor/existing_form.html.ep
> +	<%= label_for 'action.existing.target_file_id' => maketext('Use existing template:'), class => 'col-form-label col-auto' =%>
This line exceeds 120 characters.  Move the `class => ...` to the next line to fix this.

2023-11-04 11:13 UTC, drgrice1 reviewed
The achievement notification editor page needs a help file.  It should be `templates/HelpFiles/InstructorAchievementNotificationEditor.html.ep`.  One thing that is not immediately clear is how you actually enable email notifications, and what the "Use Existing Template" form is for.  I see that the "Use Existing Template" form activates sending emails for the achievement, but a help file to explain that would help.  Also, maybe it would be better if that were a `select` that shows the available templates to choose from.

2023-11-04 11:13 UTC, drgrice1 commented on lib/Mojolicious/WeBWorK/Tasks/AchievementNotification.pm
> +		->text_body($msg)->header('X-Remote-Host' => $mail_data->{remote_host});
The `$mail_data->{remote_host}` is guaranteed to be undefined.  This is never set in `AchievementEvaluator.pm` when this task is enqueued.  This is where the messages `Use of uninitialized value $val in pattern match (m//)` in the `Email/MIME/Encode.pm` module are coming from.  `SendMail.pm` sets this from the current request transaction.  See line 237 of that file.

2023-11-06 16:36 UTC, dlglin commented on lib/Mojolicious/WeBWorK/Tasks/AchievementNotification.pm
> +			$ce->{mail}{smtpSender} || $ce->{mail}{set_return_path};
Would it make sense to have a configuration variable for the from address on these messages?

2023-11-06 16:40 UTC, drgrice1 commented on lib/Mojolicious/WeBWorK/Tasks/AchievementNotification.pm
> +			$ce->{mail}{smtpSender} || $ce->{mail}{set_return_path};
I think that is needed.  This could use a course setting for this.

2023-11-21 13:54 UTC, drgrice1 approved these changes
This is looking pretty good now.  One minor issue needs to be fixed.

2023-11-21 13:54 UTC, drgrice1 commented on lib/WeBWorK/AchievementEvaluator.pm
> +					remote_host     => $c->tx->remote_host || "UNKNOWN",
This should be
```suggestion
					remote_host     => $c->tx->remote_address || "UNKNOWN",
```

2023-11-30 05:24 UTC, somiaj commented
Overall seems like a nice feature. Some things I noticed playing around with it.

First, the Achievement Notification editor still needs a help page (previously mentioned by @drgrice1).

Do you think instead of the link just saying, "Edit Email Template", it could state which template is being used and edited, since you can use the same template for multiple achievements? Maybe "Edit Email Template default" (the name of the template minus the .html.ep suffix). This way it is clear from the editor which template is being used.

Also when selecting a template in the "Use Existing Templates" form, do you think using a drop down menu that lists all .html.ep files in the templates/achievements directory would be nice (so a user doesn't have to know them by name)?

The Save As form doesn't select an option by default, and one needs to be selected to work (though I guess this is the same behavior as the Evaluator Editor, so if you decide to provide a default, that should be adjusted as well). I was just comparing this to the problem editor which selects an option by default under Save As.

The "Save As" form selecting "use in new achievement" both seems weird and doesn't work. If you enter in an achievement name that exist you get an error, "Achievement ID exists! No new achievement created. File not saved.", but if you enter in a new name you get the error "Don't recognize saveMode: |use_in_new|. Unknown error.", so this doesn't appear to do much. I don't think creating a new achievement here is the correct thing to do (since the best you can do is attach a email template to it). Maybe instead this should be add to existing achievement, and a drop down menu with all the current achievements you can add the email template to.

When using the achievement notification editor, a sub menu item for the achievement appears, but isn't fully clear what it is for, maybe call it "name evaluator" to make it clearer that links is for the evaluator editor. Would adding one for the email template editor be helpful too (just a thought, this will probably be too clunky)?

Also, for those who don't know mojolicious the suffix html.ep might be a bit odd for them to understand. Would it be helpful to hide this from the user and append it as needed? I guess they can see this in the file manager though, so this might just add useful info for some.

2023-12-01 23:27 UTC, drgrice1 requested changes
Unfortunately, I must revoke my approval of this pull request.  I started looking into things a little bit deeper after @somiaj's review.  I realized I didn't test some things very well when I say his comments.  Those things are not to bad.  I did quite a bit of work to fix those, and was going to put in a pull request to this branch to fix those things and some other issues I encountered along the way.  Then I found another problem, that can not be easily resolved.  That is the usage of Mojo::Template to render templates that are created by instructors.  That is a major security vulnerability, and unfortunately can't be allowed.  Any perl code can be executed in these templates.  Modules can be `use`d, any files that the server has permissions to modify or delete can be deleted, etc.  If the templates could be compiled in the safe zone, then perhaps this could be fixed, but I haven't found a way to do that yet.  It most likely can not be securely done.  So another approach for email templates is going to need to be found.

2023-12-01 23:33 UTC, drgrice1 commented
I went ahead and put the work that I had done to address @somiaj's comments and some other things that I saw into a pull request to this branch.  I will see what alternatives I can devise to using the `Mojo::Template` module.

2023-12-02 01:21 UTC, somiaj commented
Emails don't need to include any html, you could use a template method similar to what is being done on the email page.

2023-12-02 01:28 UTC, drgrice1 commented
Yes, that is obvious.  But that is a far more limited method.

2023-12-02 04:07 UTC, drgrice1 commented
@drdrew42:  The pull request now has been switched to using the basic interpolation method of `WeBWorK::Utils::processEmailMessage` again, and then interpolates a few other variables specific to achievements.  It no longer uses Mojolicious templates ... sigh.  There may be other variables that you might want interpolated in as well though.  If you merge that pull request, then this can pull request can proceed again.  I am still probably going to see if I can find a way to get Mojolicious templates to work in the safe zone, but it doesn't look likely.

2023-12-02 21:00 UTC, drgrice1 commented
@drdrew42:  I got Mojolicious template compilation to work in the safe zone!  I removed interpolation approach that I had added to the pull request to this branch, and switched it to using templates again with this approach.  So if you merge that pull request into this one, then this is good to go again.

2023-12-04 21:13 UTC, drgrice1 approved these changes
Looks good now!

2023-12-04 21:15 UTC, merged