option to 'clean' a course just after unarchiving it
openwebwork/webwork2 pull request #2291
Opened 2023-12-19 23:36 UTC by Alex-Jordan

This adds a checkbox to the unarchive course page, and if checked, then when the course is unarchived it will be "cleaned". Cleaning means:
* remove all student users and associated data from the database
* delete the log files
* delete any scoring files

Another small thing is that this removes the checkbox for giving a new course name. If you've entered something into the field for the new course name, that is enough, and the checkbox is redundant.

2024-01-04 15:13 UTC, pstaabp commented on lib/WeBWorK/ContentGenerator/CourseAdmin.pm
> +					"2>&1 $ce_new->{externalPrograms}{rm} -f " . shell_quote($ce_new->{courseDirs}{scoring}) . "/*";
We're trying to remove externalPrograms.  This can be done with `Mojo::File`.

2024-01-09 16:15 UTC, drgrice1 requested changes
There are some things that I see that need to be fixed.  I have implemented all of these in a pull request that I will submit to this branch.

2024-01-09 16:15 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/CourseAdmin.pm
> +			}
This can be switched to using `Mojo::File` quite succinctly with

```suggestion
				eval { Mojo::File->new($ce_new->{courseDirs}{scoring})->remove_tree({ keep_root => 1 }) };
				$c->addbadmessage($c->maketext('Failed to remove scoring files: [_1]', $@)) if $@;
```

Of course this presumes that `use Mojo::File` has been added to the beginning of the file.

Note this also should not `return` for the same reason as mentioned before.

2024-01-10 14:26 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/CourseAdmin.pm
> +			for my $student_id ($db_new->listPermissionLevelsWhere({ permission => 0 })) {
Sorry, one other thing that I missed before.  This shouldn't use a hardcoded permission value of 0.   It should use `$ce->{userRoles}{student}`.  So this should be
```suggestion
			for my $student_id ($db_new->listPermissionLevelsWhere({ permission => $ce->{userRoles}{student} })) {
```

2024-01-10 23:59 UTC, Alex-Jordan commented
I made the two edits that you caught, thanks.

2024-02-07 14:06 UTC, pstaabp approved these changes

2024-02-07 21:22 UTC, merged