Add filter action to achievements manager.
openwebwork/webwork2 pull request #2328
Opened 2024-02-17 18:04 UTC by somiaj

This adds a action to filter achievements as suggested by @Alex-Jordan.

2024-02-19 04:39 UTC, drgrice1 reviewed
There are a few details that need attention.

If a filter happens to filter out all achievements, then the message shown is "No achievements shown. Create an achievement!"  For example, in my test course all achievements are enabled.  So when I selected the "disabled achievements" filter, that gave me none.  That message is not appropriate anymore if there are achievements, but none are shown because of the filter.

2024-02-19 04:39 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
> +		$result = $c->maketext('Showing enabled achievements.');
I think this should be
```suggestion
		$result = $c->maketext('Showing disabled achievements.');
```
I was a little confused when I selected "disabled achievements" and clicked "Filter", and the message said "Showing enabled achievements".

2024-02-19 04:39 UTC, drgrice1 commented on htdocs/js/AchievementList/achievementlist.js
> +			const filter = filter_select?.selectedIndex || 0;
I know that we have used the `selectedIndex` in this way elsewhere, but it would be better to use `const filter = filter_select?.value || ''` instead.  Then you can use `if (filter === 'selected' && !is_achievement_selected()) {` below.  Of course replace the other places with their values instead of indices also.  There are two advantages to this approach.  First, instead of a meaningless index, you have a human readable string that makes it more clear which filter you are working with.  Second, if another filter is added at a later time and it is not the last in the select, then you don't have to change all of the later indices in the code to fix it.

I was going to comment on this for your earlier pull request that changed the action scope selects, but decided not to because that was the way it was done previously.

2024-02-19 04:39 UTC, drgrice1 commented on htdocs/js/AchievementList/achievementlist.js
> +				);
There is a lot of redundancy in the above code.  I was also going to comment on this in the other pull request.  I think there are better ways to achieve this without so much repetition.

You can leave this for now though since I let it go for the other pull request.

2024-02-19 15:48 UTC, somiaj commented on lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
> +		$result = $c->maketext('Showing enabled achievements.');
Thanks, overlooked this. Also fixed another bug with edit/export all achievements not working correctly if a filter was already applied.

2024-02-19 17:13 UTC, drgrice1 approved these changes
This looks good now.  Everything seems to be working in my tests.

2024-02-20 22:49 UTC, pstaabp commented
Overall, looks good.  Seems like the filter by category should be a dropdown/select list of categories, instead of requiring it to be typed in exactly.  The default list only has 6 categories, and this should be easy to pull out of the list.

2024-02-20 22:59 UTC, somiaj commented
@pstaabp I thought about that, but the only way I could think to get the list of all categories is to first pull all achievements from the database and cycle through them getting all categories. But once a filter is applied not all achievements are pulled from the database, only the filtered ones.

2024-02-23 12:29 UTC, drgrice1 commented on templates/ContentGenerator/Instructor/AchievementList/filter_form.html.ep
> +	</div>
There needs to be a div that contains lines 30 through 42, and that div should have the `filter_category_elements` id (which should be removed from the `row mb-2` div).

The same thing needs to be done with the `filter_text_elements` above.

Similar changes need to be made for all of the content generator modules that have a similar filter form.

Currently if you click the submit button without entering anything into the text input, and then you change the select to another filter, then the form validation message is still shown, even though it no longer applies.

2024-02-23 15:21 UTC, somiaj commented on templates/ContentGenerator/Instructor/AchievementList/filter_form.html.ep
> +	</div>
I am not seeing the behavior you describe. I click `Filter` when `Enter matching category below` is selected, and get an error message that I must enter a category to match. I then use the select to select any other filter option, and the validation message goes away along with the `is-invalid` matches on the form.

I can still add the extra divs, but currently I do not see any validation messages being left behind when they no longer apply (I'm assuming you updated the javascript?).

2024-02-23 15:27 UTC, drgrice1 commented on templates/ContentGenerator/Instructor/AchievementList/filter_form.html.ep
> +	</div>
Your right, the validation message does go away on the achievements page, but not on the accounts manager page and the sets manager page.

However, the structure I am asking for still should be done.  The `filter_category_err_msg` should be grouped structurally with the elements it applies to for accessibility reasons.

2024-02-23 15:41 UTC, drgrice1 commented on templates/ContentGenerator/Instructor/AchievementList/filter_form.html.ep
> +	</div>
Actually, never mind that last comment.  Divs don't really provide that kind of structural semantics for accessibility anyway.  So you can just leave it.

So the issue is that on the accounts manager page and sets manager page, the messages don't go away when they should.

2024-02-23 15:47 UTC, somiaj commented on templates/ContentGenerator/Instructor/AchievementList/filter_form.html.ep
> +	</div>
Thanks for the clarification, I'll go update those messages to correctly be hidden.

2024-02-23 15:55 UTC, drgrice1 commented
There are some real problems with the javascript that you are using.  This goes back to what you did in #2294.

You are repeatedly adding event handlers to various elements each time the form is submitted.  Those event handlers pile up.  Note that the `once: true` option makes the event handler go away if it is called, but each time the form is submitted while that has not been called another event handler is added.  Eventually all of those fire at the same time if the event does occur.

Also you `getElementById` in many cases where you have already obtained a reference to that element.  That is an expensive query.  Each time it is called, the entire DOM has to be searched until that element is found.  For example on line 24 of achievementlist.js you find the `filter_select` element (and even save a reference in a variable), and then on line 36 you search the DOM again, instead of just using the already found reference.  Several places you just blindly search the DOM each time without saving a reference.  For example, on line 43 you find the `filter_text_err_msg`, and then on line 49 you search for it again.

I mentioned the redundancy in the code before, but this is just a total kludge really.  The achievementlist.js file is 233 lines long, merely to validate a few form fields.  That is really excessive.

2024-02-23 17:20 UTC, somiaj commented
I have been thinking about ways to clean up the code and remove the redundancy, though unsure on the best approach here. My thought was to have helper functions do the work.

As for the change event methods, the reason I was calling `getElementById` again is I didn't realize that inside the event function I had access to the previously defined variables. Now that I know that I do have access, I'll update things to avoid calling `getElementById` multiple times when not needed.

I'm not quite sure the what to do about multiple events, it sounds like I should also be removing these events to avoid them piling up when one of the companion events fires?

2024-02-23 17:20 UTC, somiaj commented
I will have time to look at this and see what I can come up with this weekend.

2024-02-23 17:22 UTC, drgrice1 commented
I did a little with the multiple event thing for userlist.js in #2335.  Look at what I did there for a start.

2024-02-24 19:58 UTC, somiaj commented
@drgrice1 There is my approach at reducing the code duplication and adding/removing event listeners, so they don't pile up. If you prefer this, and any code cleanup you may see, I can apply this to the other two pages as well (though maybe I should leave userlist.js alone since you have gotten it in your PR).

2024-02-25 00:29 UTC, drgrice1 commented
Yeah, that looks considerably better.  Go ahead and do that for the other two pages as well.  I will work my changes to `userlist.js` into your scheme.

2024-02-25 01:32 UTC, somiaj commented
I have updated the other two action form validation location to match what was done here.

2024-02-25 03:07 UTC, somiaj commented
There was some achievement transition code that was suggested to remove around 2017....I can open another PR for that if preferred.

2024-02-25 03:16 UTC, drgrice1 commented
Deleting that code is fine.

The updated javascript is considerably better.  Perhaps in the future it would be nice to do this more uniformly for all pages that use action tabs (and the `actiontabs.js` file).  But this is good for now.

2024-02-25 03:47 UTC, drgrice1 requested changes
I missed a few things before.

I see that you removed the `{ once: true }` option to the error hiding event listeners.  That is needed.  Otherwise the handler will continue to be called even after the form validation messages have been cleared any time a checkbox is checked or unchecked.

2024-02-25 03:47 UTC, drgrice1 commented on htdocs/js/AchievementList/achievementlist.js
> +				element?.addEventListener('change', hide_errors([], elements));
This won't work.  This `removeEventListener` call won't remove the event listener added on lines 64-69 or on line 36.  The method returned by `hide_errors` here will not be literally the same method returned when `hide_errors` is called there.  This would fail even if `hide_errors` were called in both places with the same arguments, because the `removeEventListener` method needs to be called with a reference to the same function that `addEventListener` was called with to work.

2024-02-25 03:48 UTC, drgrice1 commented on htdocs/js/AchievementList/achievementlist.js
> +				element?.addEventListener('change', hide_errors([], elements));
The similar code in `achievementlist.js` and `problemsetlist.js` also needs to be fixed.

2024-02-25 03:56 UTC, drgrice1 commented on htdocs/js/AchievementList/achievementlist.js
> +				element?.addEventListener('change', hide_errors([], elements));
To see what I am talking about, add a `console.log` statement to line 17 (the beginning of the function returned by the `hide_errors` method) in `achievementlist.js`.  Then on the achievements list page, select the "selected achievements" option in the filter tab.  Then click on "Filter" several times with no achievements selected.  Now select an achievement.  You will see all of the console logs, and you will see all of those logs each time you select or unselect an achievement.

2024-02-25 03:58 UTC, drgrice1 commented on htdocs/js/AchievementList/achievementlist.js
> +				element?.addEventListener('change', hide_errors([], elements));
Really, what you need to do is call `removeEventListener` each time before you call `addEventListener`.  It is certainly not going to work to have the handler added by `addEventListener` try to remove itself.  The handler has to be called for that to happen, and it is not being called each time the event listener is added.  Look again at what I did in `userlist.js` in my pull request.

2024-02-25 04:51 UTC, somiaj commented on htdocs/js/AchievementList/achievementlist.js
> +				element?.addEventListener('change', hide_errors([], elements));
Thanks for catching that. I incorrectly thought the solution in the comments here would work. I should have read (tested it) deeper.

https://stackoverflow.com/questions/256754/how-to-pass-arguments-to-addeventlistener-listener-function#answer-45696430

It does appear that currying can work here (at least under my tests) if you save the curried functions to access later so you can remove them.  So I have updated the code to store the curried functions so the event listeners can be removed.

The reason I went with this approach vs `{ once: true }`, was I was adding event listeners to multiple objects, and wanted to remove them all, not just the one the fired. I couldn't see in your code how that was achieved (or missed it).

2024-02-25 05:09 UTC, somiaj commented on htdocs/js/AchievementList/achievementlist.js
> +				element?.addEventListener('change', hide_errors([], elements));
This also allowed me to not run any error hiding code when moving tabs if there are no event listeners saved when switching tabs, as any error will populate `event_listeners` and the events to fix the action should clear all error messages and listeners.

2024-02-25 11:56 UTC, drgrice1 approved these changes
This is better, and works to prevent handlers for events from piling up.

That stack exchange post you linked to is certainly not accurate.  You have to read the comments responding to it to really see what is needed.

In the code I was using in `userlist.js` I was only dealing with one handler being added, and so didn't need something more complicated.  Although, as mentioned in that #2335, there was more work needed.  I saw that there were other event listeners that would need similar handling.

2024-02-29 21:08 UTC, Alex-Jordan commented
Thanks for this. I was testing it, and I thought I would make the category selection be a dropdown. I opened a PR to your branch (@somiaj ):

https://github.com/somiaj/webwork2/pull/13

2024-03-01 00:15 UTC, somiaj commented
@Alex-Jordan updated this so the category filter is now a drop down menu instead of a text field.

2024-03-01 00:33 UTC, Alex-Jordan approved these changes

2024-03-02 17:25 UTC, drgrice1 commented
I will merge this with 2+1 approvals.

2024-03-02 17:25 UTC, merged

2024-03-02 17:45 UTC, drgrice1 commented on lib/WeBWorK/DB.pm
> +
@Alex-Jordan:  I realized I didn't look closely at your commit at the end of this.  I just saw this.  This is a nice.  A good new database method.