Move database and external program settings
openwebwork/webwork2 pull request #2338
Opened 2024-02-24 12:26 UTC by pstaabp

This PR
* moves database and external program settings in both `site.conf` and `defaults.config` to `webwork2.mojolicious.yml`
* moves code from `database.conf.dist` to `WeBWorK::DB::Utils` 
* loads these settings into the `CourseEnvironment`.

These settings will be loaded after `simple.conf` and `course.conf` so instructors will not be able to override these settings.

2024-02-25 02:28 UTC, drgrice1 requested changes
This needs a lot of work to be acceptable.

2024-02-25 02:28 UTC, drgrice1 commented on conf/defaults.config
> +	dvipng_depth_db => {}
This comment is not good enough.  These can be set here.  A site administrator may want to use a different database for this.  The options should be added back commented out with example defaults.  The comment needs to give a good explanation of how this works.

2024-02-25 02:29 UTC, drgrice1 commented on conf/defaults.config
>  	},
I forgot to mention that this line needs to be deleted.

2024-02-25 02:30 UTC, drgrice1 commented on conf/defaults.config
>  	},
That is line 1061.  It causes this file to fail to load.

2024-02-25 12:26 UTC, drgrice1 commented on lib/WeBWorK/CourseEnvironment.pm
> +	$ce->{dbLayoutName}                = 'sql_single';
Hmm.  Somehow my comment here did not make it into my review.  This is the comment that was most important, and that spurs my remark about this pull request needing a lot of work.

`dbLayoutName` needs to be deleted here, and all references to it removed from the code.  You have broken many things by not taking care of this.  The `adduser` script and several things in `CourseManagement.pm` (and probably other places too) access the previous `dbLayouts` hash using this name.  Since there is no `dbLayouts` hash anymore those things fail.

2024-02-26 11:35 UTC, drgrice1 commented on conf/webwork2.mojolicious.dist.yml
> +  password: ''
Another thing here.  Change this to
```suggestion
  password: passwordRW
```
There are two reasons this should be done.  First, this is the current default in `site.conf.dist`.  Second, this shows that the quotes are not needed.

Although, documentation in the comments is needed here similar but different than what was in site.conf.dist.  In many cases quoting will not be needed here.  However, there are some cases where it will be needed.  The comments here should make this clear.  See https://symfony.com/doc/current/reference/formats/yaml.html for when quoting is needed in a YAML file.

2024-02-26 11:56 UTC, drgrice1 commented on conf/webwork2.mojolicious.dist.yml
> +  git: /bin/git
This should be `/usr/bin/git` as it was in `site.conf.dist`.

2024-02-26 11:59 UTC, drgrice1 commented on conf/webwork2.mojolicious.dist.yml
> +  pnmtopnm: /usr/bin/pnmtopnm
You have dropped the `gif2eps`, `png2eps`, and `gif2png` external program definitions.  I don't think the first two are ever used anymore, but the last one is.

2024-02-26 15:53 UTC, somiaj commented on conf/webwork2.mojolicious.dist.yml
> +  git: /bin/git
With `usrmerge` now standard in the main distros, would it be worth updating all the paths to use `/usr/bin`. Not strictly necessary since `/bin -> /usr/bin`, but might be worth updating to the new standard location.

2024-02-27 11:29 UTC, pstaabp commented on conf/defaults.config
> +	dvipng_depth_db => {}
The database variables aren't available in defaults.config now, which is why I moved them to the CourseEnvironment.  I can provide some documentation in localOverrides to provide this.

2024-02-27 11:35 UTC, drgrice1 commented on conf/defaults.config
> +	dvipng_depth_db => {}
That is my point.  Either these DO need to be available in defaults.config (or really in localOverrides.conf), or a separate section in webwork2.mojolicious.dist.yml needs to be created for them.  The same for `$problemLibrary_db`.

2024-02-27 11:40 UTC, pstaabp commented on conf/webwork2.mojolicious.dist.yml
> +  pnmtopnm: /usr/bin/pnmtopnm
I meant to keep the code on old lines 156-158 of `site.conf.dist`.   Should I just include the `gif2png`?

2024-02-27 11:42 UTC, drgrice1 commented on conf/webwork2.mojolicious.dist.yml
> +  pnmtopnm: /usr/bin/pnmtopnm
You can just leave lines 156-158 of `site.conf.dist`.

2024-02-27 11:44 UTC, pstaabp commented on conf/defaults.config
> +	dvipng_depth_db => {}
I'll add to localOverrides

2024-03-02 12:34 UTC, pstaabp commented
This removes all references to dbLayoutName and cases where the dbLayouts hash is used. With this, there is only the standard dbLayout, which is now defined in `WeBWorK::DB::Layout`.

Also, removed the older style unarchive database archive file.  It was unclear when this was last in the codebase, probably > 10 years.

2024-03-22 17:03 UTC, Alex-Jordan commented
Note conflicts here now from a recent merge.

2024-03-23 11:53 UTC, pstaabp commented
Fixed now.

2025-08-05 15:01 UTC, closed without merging