Split up macros on PODViewer index page.
openwebwork/webwork2 pull request #2615
Opened 2024-11-06 06:19 UTC by somiaj

This splits up the macros on the PODViwer index page to be grouped by their location in the `pg/macros` directory. In addition macros are listed before the libraries. The two macros not in a subdirectory, `PG.pl` and `PGcourse.pl`, are grouped with the pod in `pg/doc`. This makes finding the POD for a specific macro easier.

2024-11-11 18:25 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/PODViewer.pm
> +		}
Using a substitution to find a match is a bit off.  I would suggest instead using a match instead, since that is what it is made for.
```suggestion
		if ($macroFiles->{$_} =~ m!^$pgRoot/macros/(.+)/.+$!) {
			push(@{ $macros->{$1} }, $macroFiles->{$_} =~ s!^$pgRoot/macros/$1/!!r);
		} else {
			push(@$docs, $macroFiles->{$_} =~ s!^$pgRoot/!!r);
		}
```

2024-11-11 21:21 UTC, drgrice1 requested changes
There are two issues with this pull request.

The first is that this changes how the POD is organized inconsistent with how the pod generated by the `bin/dev_scripts/generate-ww-pg-pod.pl` script is organized (that is the pod displayed at https://webwork.maa.org/pod/).

The second is that the reorganization of the files into sub directories was not intended to be a visible categorization of macros.  At least not initially.  It was done more for development purposes to keep the `pg/macros` directory from being a completely unorganized mess with one long list of files.  The organization that was done was not the most intuitive in terms of what macros are actually used for.  For example, all macros that started with "parser" were just put in the "parsers" subdirectory, and all macros that started with "context" into the "contexts" subdirectory.   Sorting purely by what the macro started with is not the best way to do that.  The intent was to sort things better eventually.  For example. the `parserGraphTool.pl` macro was later moved to the "graph" subdirectory.  I am not sure that the organization is ready to be publicized in this way.

So this needs discussion first.

2024-11-11 23:25 UTC, somiaj commented
I think we are already publicizing the macro organization this way. The macros are currently sorted by what directory they are in, further that directory is printed in the link name. So knowing what directory a macro is in helps one find it in the long list of macros on the POD index (this mostly just splits that list apart). Though I do welcome more discussion on this to have a way that users can easily find the POD of a macro they are using or find a new macro they may want to use.

2024-11-11 23:52 UTC, drgrice1 commented
We are currently listing them with their directory for ease of location.  The sorting will then list those in the same directory together.  That is not exactly the same thing as a categorization.  As I said, this needs discussion.  In any case, my first point is more pressing.  The dev script will need to be updated to match.  That is if we decide we want this organization.

2024-11-11 23:53 UTC, somiaj commented on lib/WeBWorK/ContentGenerator/PODViewer.pm
> +		}
Thanks, I updated the code here.

2024-11-22 06:37 UTC, somiaj commented
Updated `dev_scripts/generate-ww-pg-pod.pl` to match splitting up the macros link.

2024-11-24 03:50 UTC, drgrice1 commented on bin/dev_scripts/pod-templates/category-index.mt
> +			<h3><a href="#_podtop_" id="<%= $macro %>"><%= $macros->{$macro} %></a></h3>
Either `macro-` needs to be deleted from the `href` anchor, or `macro-` added to the `id` on line 34.  The links in the sidebar are not working.

2024-11-24 03:55 UTC, somiaj commented on bin/dev_scripts/pod-templates/category-index.mt
> +			<h3><a href="#_podtop_" id="<%= $macro %>"><%= $macros->{$macro} %></a></h3>
Thanks. Updated.

2024-11-24 04:10 UTC, drgrice1 commented on bin/dev_scripts/generate-ww-pg-pod.pl
> +		: [ bin => 'Scripts',       doc    => 'Documentation', lib => 'Libraries' ];
The scripts should appear on the PG POD page for the wiki.  This is one place that the POD in webwork2 differs from the wiki.

2024-11-24 04:12 UTC, drgrice1 commented on bin/dev_scripts/generate-ww-pg-pod.pl
> +		: [ bin => 'Scripts',       doc    => 'Documentation', lib => 'Libraries' ];
The POD in webwork2 is intended to be for problem authors working in the PG problem editor of webwork2.  The scripts don't need to be shown for that.  However, they are something that authors could use, and should be represented on the wiki.

2024-11-24 04:15 UTC, somiaj commented on bin/dev_scripts/generate-ww-pg-pod.pl
> +		: [ bin => 'Scripts',       doc    => 'Documentation', lib => 'Libraries' ];
Thanks again, I overlooked they were included on the wiki when I was comparing things.

2024-11-24 04:16 UTC, drgrice1 commented
I don't really like that the macro subdirectories are hard coded into this (in both `templates/ContentGenerator/PODViewer.html` and the `generate-ww-pod.pl` script.  That is a maintenance hassle.  Every time a directory is added, removed, or renamed, then this code has to be updated.

2024-11-24 04:16 UTC, somiaj commented on bin/dev_scripts/generate-ww-pg-pod.pl
> +		: [ bin => 'Scripts',       doc    => 'Documentation', lib => 'Libraries' ];
Do you have an opinion of if the scripts should go first or not. I felt doc should be first here, but can make this match current behavior.

2024-11-24 04:17 UTC, drgrice1 commented on bin/dev_scripts/generate-ww-pg-pod.pl
> +		: [ bin => 'Scripts',       doc    => 'Documentation', lib => 'Libraries' ];
They can be after the documentation.

2024-11-24 04:22 UTC, somiaj commented
I realized that, but also felt that alphabetical order wasn't the best way to order the macros by, so I went with this so the order can be better controlled. So to me the question is the hassle worth having a different ordering than alphabetical.

2024-11-24 04:29 UTC, drgrice1 commented
Actually, I think it would be better to go with alphabetical anyway.  I didn't realize you were ordering them in a particular way.  Why have you chosen that order anyway?  The only subdirectory that would be nice to move down is the "deprecated" directory.  There is no real reason to order the rest.

2024-11-24 05:09 UTC, somiaj commented
Okay, updated to not have a pre defined list for the order and macros included. There is still a hash of macro names that will include the translated and/or custom name, so "User Interface" is shown instead of "ui". Any new or renamed directory not included in that hash will still be included, just won't have a custom name attached to it.

2024-11-24 12:18 UTC, drgrice1 approved these changes
This is better now.  At least all directories will be represented.  I am still not sure of the benefits of providing alternate labels for the directories and even translating them. That tacitly assumes the directory categorization has more meaning than the haphazard sorting of macros that it mostly is at this point.

2024-11-24 12:18 UTC, drgrice1 commented on bin/dev_scripts/PODtoHTML.pm
> +	conf   => 'Config Files',
You can delete `conf` from this list.  At one point there was something in that directory that had POD (I think), but whatever it was is gone, and nothing in the `conf` directory should ever have POD again.

2024-11-24 12:18 UTC, drgrice1 commented on bin/dev_scripts/PODtoHTML.pm
> +			push @{ $macros->{$1} }, [ $html_rel_path, $2 ];
This could just be
```suggestion
			push @{ $self->{macros_hash}{$1} }, [ $html_rel_path, $2 ];
```

2024-11-24 17:03 UTC, somiaj commented on bin/dev_scripts/PODtoHTML.pm
> +			push @{ $macros->{$1} }, [ $html_rel_path, $2 ];
Suggested updates applied.

2024-12-16 23:40 UTC, Alex-Jordan approved these changes
I like that this gives you one level deeper of navigation in the left.

2024-12-16 23:40 UTC, merged