add controls for when grades are sent to the LMS
openwebwork/webwork2 pull request #2617
Opened 2024-11-08 23:15 UTC by Alex-Jordan

This is a reworking of #2614. Some discussion there may be helpful but imo this can be considered a new PR. As with that PR though, I can not test this with D2L until it's less risky, because for now I can only test in production. If anyone else can test in Canvas or Moodle, and things get to the point they are working, I will test with D2L. I apologize in advance for my mistakes! I can at least say I tested that `webwork2` starts, and nothing goes bad when I visit pages.

A few changes are packaged here. The big things are:

- `$LTISendScoresAfterDate` can be set, for example, to `"close_date"`.  It's described in the new `conf/authen_LTI.conf.dist`.
- `$LTISendGradesEarlyThreshold` can be set to a number from 0 to 1, or `'attempted'`. It's described in `conf/authen_LTI.conf.dist`.

There are 2x2 pathways to consider when implementing these. First, is it LTI 1.1 or 1.3? And then, is grade passback in `"course"` or `"homework"` mode? For `"homework"` passback, the work is almost entirely in the two `SubmitGrade.pm` files. Specifically in the `submit_set_grade` subroutines. There is a small reliance on three new utilities in `lib/WeBWorK/Utils/Sets.pm`.

For `"course"` grade passback, the work happens in `lib/WeBWorK/Utils/Sets.pm` with its `grade_all_sets` subroutine, where it always has. But now with parameters sent so that `grade_all_sets` can understand the two new config settings and act accordingly.

Additional changes concerning `$LTICheckPrior`:

- Add `$LTICheckPrior` to the list of LTI config options that could be enabled on the Config page
- Before this, if `$LTICheckPrior` is set and somehow an LMS score is like 0.9999, it would not update to 1 even when the WeBWorK score is now 1. So I changed it to ignore a small nonzero difference if the WW score is 1.
- Now if using `$LTICheckPrior`, suppose an LMS score is null and the corresponding WW score is 0. Previously, the LMS would not be updated to 0. Now it will be updated to 0 if we are past the new `$LTISendScoresAfterDate`.

2024-11-09 00:09 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +		}
Yeah, what @somiaj suggests is consistent with what is done elsewhere for determining the status of a test.

2024-11-09 00:11 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +		}
Right but it won't actually loop through them all. It returns on the first hit.

2024-11-09 00:12 UTC, somiaj commented
I suggest that the defaults should be `$LTISendScoresAfterDate = 'close_date'` and `$LTISendGradesEarlyThreshold = 'attempted'`. I don't think we need to keep behavior the same as it is here, and this seems reasonable, any attempt will be sent back, but no need to send non attempted zeros back early.

2024-11-09 00:15 UTC, somiaj commented on lib/WeBWorK/Utils/Sets.pm
> +		}
Ahh, I see. Yea it ends up doing the same thing. Is it possible to reduce the database call and just get a merged single problem. Seems there is a `$db->getMergedProblemVersion`.

2024-11-09 00:16 UTC, somiaj commented on lib/WeBWorK/Utils/Sets.pm
> +		}
(Though I guess that first requires getting the problem numbers, since they don't have to start at 1).

2024-11-09 00:16 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +		}
Are you suggesting I change those three lines to `return 1 if $problemRecords[0]->attempted;`?

If so, can anyone confirm the first problem is actually indexed 0? I'm nit sure what happens when problems get deleted from a set, that sort of thing.

2024-11-09 00:19 UTC, somiaj commented on lib/WeBWorK/Utils/Sets.pm
> +		}
ProblemSet.pm uses this:

```
my @ProblemNums = $db->listUserProblems($effectiveUser, $set->set_id);
my $Problem = $db->getMergedProblemVersion($effectiveUser, $set->set_id, $verSet->version_id, $ProblemNums[0]);
my $verSubmits = defined $Problem ? $Problem->num_correct + $Problem->num_incorrect : 0;
```

to determine the number of submits/attempts.

2024-11-09 00:27 UTC, drgrice1 commented
I just looked at your changes with `$LTIGradeOnSubmit` now incorporated, and if I understand things correctly I don't think I like the change.  What I want is when grades are submitted because `$LTIGradeOnSubmit` is true is that those are always sent (except the $LTICheckPrior case when the grades are the same).  However, when a mass grade pass back occurs, then I want that to not send zero scores.  Is that possible with what you have set up?

2024-11-09 00:27 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +		}
OK, thanks. I changed it to that, appropriately modified.

2024-11-09 00:29 UTC, Alex-Jordan commented
I don't think I intentionally changed anything with how/when `$LTIGradeOnSubmit` has effect. But I can think through what you described and try it.

2024-11-09 00:30 UTC, somiaj commented
@drgrice1 Wouldn't my suggested defaults above do just that? Grades will be sent once attempted (from the first time they hit submit), or after the closed date?

2024-11-09 00:33 UTC, Alex-Jordan commented
Do I understand this right? If there is a set of 10 questions, and `$LTIGradeOnSubmit` is true, and a student answers the first question (correctly or incorrectly) then you want the score (0% or 10%) passed back? That's what I am trying to avoid, although I do not have `$LTIGradeOnSubmit` set.

Just seeing Jaimos's post. Is the behavior you want achieved by using `$LTISendGradesEarlyThreshold = 'attempted'`?

This is reminding me that I will have to change the message students get about whether or not (and when) their score will be sent to the LMS. I hadn't considered that.

2024-11-09 00:34 UTC, somiaj commented
But I too found it confusing that `$LTIGradeOnSubmit` was linked into this, as I originally thought this was only about LTI mass update (from either the time interval or manually triggering it). But from my understanding the defaults I suggested would probably meet my use case.

2024-11-09 00:34 UTC, Alex-Jordan commented
Oh I see, you do not want the score passed back during mass grade passback, and using `attempted` would do that. I'll think about it more. Signing off for a while now though.

2024-11-09 00:35 UTC, Alex-Jordan commented
Did I change something with `LTIGradeOnSubmit`? I know I added to its documentation but I didn't think I changed its behavior. Just tried to improve the description.

2024-11-09 00:37 UTC, Alex-Jordan commented
OK, I read my own words and I see it. I was acting on the idea that whatever calls the routines in `SubmitGrade.pm` is what it is (on submit or a mass passback). And then its those routines that were modified.

So we will want to know if these routines were called my mass passback or by a passback upon submit.

2024-11-09 00:41 UTC, somiaj commented
@Alex-Jordan I almost commented on this, but then thought the defaults I suggested would work for me, so left it alone. I did find the wording a little confusing, "This is subject to the above settings." makes it sound like you meant that now the grade will only pass back if it meets the conditions set in `$LTISendScoresAfterDate` and `$LTISendGradesEarlyThreshold`. But I can't tell in the code if this is actually the case. Maybe you should put your new options after `$LTIGradeOnSubmit` as I'm still confused on if those settings affect that or not.

2024-11-09 00:46 UTC, somiaj commented
Okay, I just double checked, and yes these settings do affect `$LTIGradeOnSubmit` because the logic calls the `submit_course_grade` or `submit_set_grade` methods appropriately, which are now subject to these new constraints. So this can change its behavior (though the defaults `open_date` and `0` won't chance current behavior).

2024-11-09 00:49 UTC, somiaj commented
@Alex-Jordan ahh I see you answered your own question while I was typing and I missed it. One thing this already appears to do is make the configuration a bit more complicated.

2024-11-09 00:59 UTC, Alex-Jordan commented
Right, I set the defaults so that nothing should change.  [Technically, there are currently some unrealistic situations where a grade would be submitted before the set opens, and this PR _would_ change things in those unrealistic situations and no longer send grades.]

Three things can trigger grade passback:

- an exercise submission
- mass passback because the mass passback time interval has passed
- mass passback because someone used the LTI Grades update tool

They all call the subroutines in `SubmitGrades.pm` which is where the code modification for this PR starts. So there is no distinguishing those three triggers as of this time.

But I could make the three things behave differently and that won't be hard. The question is though, that what @drgrice1 is requesting is not what I would want, even if I were using `$LTIGradeOnSubmit`. So I'm not sure about hard coding anything to work as Glenn describes.

How about if `$LTIGradeOnSubmit` can be

- `0` for off
- `1` (or most other truthy things) for behaving like it does at the moment with this PR
- some third setting to behave as Glenn describes: always pass the grade when the trigger was a submission, even if the threshold has not been met.

I don't have a preference about defaults. For my purposes I'll just set the settings to what I would like them to be. So whether defaults preserve current behavior or move to a new better behavior, whatever people want is good.

2024-11-09 01:15 UTC, drgrice1 commented
> Do I understand this right? If there is a set of 10 questions, and `$LTIGradeOnSubmit` is true, and a student answers the first question (correctly or incorrectly) then you want the score (0% or 10%) passed back? That's what I am trying to avoid, although I do not have `$LTIGradeOnSubmit` set.

Yes, that is what I want. In fact, I realized that all I really want is when mass grade pushback occurs is a grade for a test that has no versions is not sent until after the due/course date.  The biggest issue that keeps happening is a student opens a test from the LMS but doesn't start it. So now Webwork has what it needs to pass back grades, but no version exists. Then mass pass back submits a zero, and I get an email from a student asking me to re open the test for them (they don't bother to check to see that they can still go into the test and take it).

Note that an empty score from the LMS is not zero, and for LTI 1.1, even $LTICheckPrior doesn't prevent grade pass back.

2024-11-09 01:26 UTC, drgrice1 commented
> So we will want to know if these routines were called my mass passback or by a passback upon submit.

As I mentioned in the previous pull request, this is already known in all of the SubmitGrade.pm methods (for both LTI 1.1 and 1.3).  If `$self->{post_processing_mode}` is set, then it is a mass pass back, and otherwise it is from a `$LTIGradeOnSubmit` submission.

2024-11-09 01:28 UTC, Alex-Jordan commented
I was somewhat surprised to find that:

```
$a;
$b = $a / 10;
```
does not cause an error. It results in `$b` being 0. The same happens with `$a = '';`.

With LTI 1.3 at least, I confirmed that `''` is passed back during a "CheckPrior" check when the LMS grade is null. It then becomes 0 like the above when it gets divided by the total weight of the LMS assignment. So it ultimately compares as 0 against a WW score of 0 with no issue. But we can still detect when `$priorData->[0]{resultScore}` is empty and distinguish that from when it is 0.

Yeah I don't know about LTI 1.1. I also wonder if the LMS might pass back different things for different LMSs when the grade is null in the LMS. I can't test that with our D2L instance anymore.

2024-11-09 01:34 UTC, drgrice1 commented
For LTI 1.1, the LMS returns XML containing `<textString/>` when it has no grade.  If it has a grade instead it returns `<textString>numeric score</textString>`.  The `$LTICheckPrior` code in `WeBWorK/Authen/LTIAdvanced/SubmitGrade.pm` has this analysis, and it translates `<textString/>` into the empty string.  Furthermore, in that case it doesn't even look at the score that webwork has, and it proceeds to submit the grade.  So it is not the same as what happens with LTI 1.3 at all.

2024-11-09 02:40 UTC, drgrice1 commented
So there is a bug in the LTI 1.3 submit_grade method in the case that a user has opened a test, but not started a test.  When mass grade passback occurs and `$LTICheckPrior` is set and `$LTIGradeMode = 'homework'`.  In this case there are no set versions (of course), and the `grade_gateway` method just returns `(0, 0)`.  Then the `submit_grade` method fails with a divide by zero error.  This is caused on line 277 of `WeBWorK/Authen/LTIAdvantage/SubmitGrade.pm` added in #2422.

2024-11-09 03:31 UTC, Alex-Jordan commented
Sorry about that. I just added a commit that I think addresses it.

I'll work on the `$LTIGradeOnSubmit` change now.

2024-11-09 03:32 UTC, drgrice1 approved these changes

2024-11-09 04:52 UTC, somiaj commented
I don't have a setup where I can test this, but I'm okay with additional configuration options (even if it is a bit confusing at first). As for `$LTIGradeOnSubmit`, it is possible to get the behavior I would use with the current setup, and maybe some users who want to not submit grades until most of the assignment is done may want to pair your changes with `$LTIGradeOnSubmit`. You could make it more configurable and have a `$LTIGradeOnSubmit` option that controls if it follow your new rules or not.

2024-11-09 04:52 UTC, somiaj approved these changes

2024-11-09 07:17 UTC, Alex-Jordan commented
I have a question about this. Suppose a person is using "course" grade passback mode. What I've done so far means that when an overall course grade is calculated to send to the LMS, it will only factor in those sets where the threshold ('attempted' or some score) has been reached, or for which it is past the `$LTISendScoresAfterDate`.

Note that during any mass passback, this is how the grade calculation will be made.

@drgrice1 has requested that possibly with the right configuration, that if a student submits an answer to a set or grades a test, then grades should be passed back regardless of that set's date or threshold being met. What does this mean for a set
* that has not met the threshold
* that has not reached its `$LTISendScoresAfterDate`
* and we are using "course" grade mode?

Either:

1. In that moment, the overall grade that is calculated still omits sets that have not met their threshold or reached the `$LTISendScoresAfterDate`.
2. In that moment, the overall grade that is calculated still omits most sets that have not met their threshold or reached the `$LTISendScoresAfterDate`, but includes the set where a submission triggered this passback.
3. In that moment, the overall grade that is calculated using all sets, regardless of meeting thresholds or reaching dates.

(1) is pointless because the score will omit the set that triggered the passback.

(2) and (3) will change the score in the LMS. But then later, suppose there is a mass update and this set has still not met its threshold or reached its `$LTISendScoresAfterDate`. The mass update may calculate a different score than was calculated from the problem/test submission. And then change the LMS score, which will be confusing.

So should this feature that @drgrice1 would like to have be unavailable for "course" passback mode?

2024-11-09 12:40 UTC, somiaj commented
I agree with your analysis, If you want to add a feature that `$LTIGradeOnSubmit` ignores these settings, it only makes sense to do so in `homework` mode.

Also, would it be worth while extending this beyond LMS passback. What about in the WeBWorK gradebook itself, these settings could control what sets are included in the total grade for users who show that to students (just a thought).

2024-11-09 20:36 UTC, Alex-Jordan commented
Here is my new write-up to document the intended behavior of all these variables. I'm looking for feedback before I return to checking the behavior matches this description.

```
# There are several controls for when to report grades to the LMS. Sometimes these controls
# interplay with each other, and the details of how they work may depend on whether
# $LTIGradeMode is set to 'course' or 'homework'. So it is recommended to understand all of
# them and then decide how to set them.

# If $LTICheckPrior is 1, then any time WeBWorK is about to send a grade to the LMS, it will
# first request from the LMS what that grade currently is. Then if there is no significant
# difference between the LMS grade and the WeBWorK grade, WeBWorK will not follow through with
# updating the LMS grade. This is to avoid frequent insignificant updates to a student's grades
# in the LMS. With some LMSs, some students receive notifications each time a grade is updated,
# and setting this variable will prevent too many notifications for them. This does create a
# two-phase process, first querying the current grade from the LMS and then actually updating
# the grade (if there is a significant difference).

# Additional details:
# - If the LMS score is not 100%, but the WeBWorK score is, then even if the LMS score is only
#   insignificantly less than 100%, it will be updated anyway.
# - If the LMS score is null and the WeBWorK score is 0, this is usually considered an
#   insignificant difference and the LMS score will not be updated to 0. However if it is after
#   the $LTISendScoresAfterDate (described below), then the null score will be updated to 0
#   anyway.
# - "Significant" means an absolute difference of 0.001, or 0.1%. At this time this is not
#   configrable.
$LTICheckPrior = 0;

# If $LTIGradeOnSubmit is set to 1, then  each time a user submits an answer or grades a test,
# that will trigger WeBWorK possibly reporting a score to the LMS. See $LTICheckPrior for one
# reason that WeBWorK might not ultimately send a grade. But there are other reasons too.
# - If $LTIGradeMode is 'homework', then WeBWorK will send that assignment's score to the LMS
#   only if either the assignment's $LTISendGradesEarlyThreshold (described below) has been met
#   or if it is past that assignment's $LTISendScoresAfterDate (also described below).
# - If $LTIGradeMode is 'course', then WeBWorK will send the overall course grade to the LMS
#   only if either the assignment's $LTISendGradesEarlyThreshold (described below) has been met
#   or if it is past that assignment's $LTISendScoresAfterDate (also described below).

# If $LTIGradeOnSubmit is set to 'homework_always', then
# - If $LTIGradeMode is 'homework', then WeBWorK will send that assignment's score to the LMS
#   regardless of having met the $LTISendGradesEarlyThreshold or being past the
#   $LTISendScoresAfterDate
# - If $LTIGradeMode is 'course', the behavior will be no different as if $LTIGradeOnSubmit were
#   set to 1.

# Sending grades frequently may put a strain on the server, so you might want to turn this off
# by setting $LTIGradeOnSubmit = 0;

$LTIGradeOnSubmit = 1;
#$LTIGradeOnSubmit = 'homework_always';
#$LTIGradeOnSubmit = 0;

# In addition to scores possibly being sent to the LMS upon submission, they can be sent by an
# instructor or admin user using the LTI Grades Update Tool. And thirdly, the system can
# periodically update student grades on the LMS on its own. For all three possible triggers for
# grades to be passed to the LMS, $LTISendScoresAfterDate and $LTISendGradesEarlyThreshold can
# affect what is sent. $LTISendScoresAfterDate can be set to 'open_date', 'reduced_scoring_date',
# 'close_date', 'answer_date', or 'never'. For a given assignment, if it is *after* the
# $LTISendScoresAfterDate, then WeBWorK will send grades.
# - For 'course' grade passback mode, the assignment will be included in the overall course
#   grade calculation.
# - For 'homework' grade passback mode, the assignemnt's score will be sent.

# If $LTISendScoresAfterDate = 'reduced_scoring_date' and an assignent has no reduced_scoring_date
# the fallback is to use the close_date.

# For a given assignment, if it is *before* the $LTISendScoresAfterDate, WeBWorK *may* send a
# score to the LMS depending on $LTISendGradesEarlyThreshold. This variable can either be the
# string 'attempted' or a number from 0 to 1. If this variable is 'attempted', a given set must
# have been attempted for the threshold to have been met, and then the score can be used even if
# it is before the $LTISendScoresAfterDate. For a regular or jitar set, 'attempted' just  means
# that some exercise in the set was attempted. For a test, 'attempted means that either there
# is one version with a graded submission, or there are at least two versions.

# If $LTISendGradesEarlyThreshold is a number from 0 to 1, the score for an assignment needs to
# have reached that number for the threshold to be met, and then the score can be used even if
# it is before the $LTISendScoresAfterDate.

#$LTISendScoresAfterDate = 'open_date';
$LTISendScoresAfterDate = 'reduced_scoring_date';
#$LTISendScoresAfterDate = 'close_date';
#$LTISendScoresAfterDate = 'answer_date';
#$LTISendScoresAfterDate = 'never';

$LTISendGradesEarlyThreshold = 'attempted';
#$LTISendGradesEarlyThreshold = 0;
#$LTISendGradesEarlyThreshold = 0.7;
#$LTISendGradesEarlyThreshold = 1;

# The system periodically updates student grades on the LMS. If it has been at least this many
# seconds since the last mass passback event and someone in the course does anything to load a
# page, then a new mass passback job will begin. Set this to -1 to disable mass passback.
$LTIMassUpdateInterval = 86400;
```

2024-11-09 20:51 UTC, somiaj commented
Overall sounds good, a few things I notice over my first quick read through.

* With `$LTIGradeOnSubmit=1` description, your `course` and `homework` descriptions are the same, you can probably combine them.
* "If $LTISendScoresAfterDate = 'reduced_scoring_date' and an assignent has no reduced_scoring_date the fallback is to use the close_date.", I think this might be incorrect behavior (and also means the code needs updated). I think it is possible for an assignment to have a `reduced_scoring_date`, but reduced scoring be disabled for that set or for the course. I think you need also check if reduced scoring is indeed enabled here.
* This document seems a bit overly detailed for being aimed at webwork admins (in the server configuration file file). Many users may only encounter these settings in the course configuration settings. So those should probably be updated to match.

2024-11-09 21:01 UTC, Alex-Jordan commented
Thanks for reading through all that.

> With $LTIGradeOnSubmit=1 description, your course and homework descriptions are the same, you can probably combine them.

There is a subtle difference. Do you have a suggestion for wording that part?

> "If $LTISendScoresAfterDate = 'reduced_scoring_date' and an assignent has no reduced_scoring_date the fallback is to use the close_date.", I think this might be incorrect behavior (and also means the code needs updated). I think it is possible for an assignment to have a reduced_scoring_date, but reduced scoring be disabled for that set or for the course. I think you need also check if reduced scoring is indeed enabled here.

I could have it also check for whether reduced scoring is enabled. But what do you mean by "incorrect behavior"? In spririt, the reduced scoring date is the "due date" from a student perspective. If there were no reduced scoring date, or if there is but reduced scoring is disabled, I would want the natural "due date" to the the fallback.

> This document seems a bit overly detailed for being aimed at webwork admins (in the server configuration file file). Many users may only encounter these settings in the course configuration settings. So those should probably be updated to match.

Writing it all here in one place (authen_LTI.conf) helps me code the rest to follow through and check that the code is trying to match this description. Similar descriptions with go into `ConfigValues.pm` but it will be harder there, because the descriptions are supposed to be more isolated to the variable being described. I'll do that at the end.

2024-11-09 21:17 UTC, somiaj commented
> There is a subtle difference. Do you have a suggestion for wording that part?

The only subtle difference I see is between what `course` and `homework` grade do, I don't really see any difference about if the grade is sent, which is what I assumed it was pointing out when it was split into two different conditions, so that is why I though it could be combined. What about something like:

```
# - WeBWorK will send the grade (the assignment's score if $LTIGradeMode is 'homework' or
#   the overall course grade if $LTIGradeMode is 'course') to the LMS only if either the
#   assignment's $LTISendGradesEarlyThreshold (described below) has been met
#   or if it is past that assignment's $LTISendScoresAfterDate (also described below).
```

> But what do you mean by "incorrect behavior"?

To me the incorrect behavior would be using the reduced scoring date if reduced scoring is disabled for the set (or course) but the setting is `reduced_scoring_date` and for some reason that reduced scoring date exists. So it should fall back to `close_date` if reduced scoring is disabled not if the date doesn't exist. (I don't think it is possible for reduced scoring to
be enabled and the date not existing, that sounds like it would cause issues elsewhere as well).

> Similar descriptions will go into ConfigValues.pm

What I thought, I was just double checking mostly.

2024-11-09 21:21 UTC, drgrice1 commented
I think that what you have written seems generally correct.  I also think that the documentation should be in the config file (as you have it), and matching it in documentation show on the course configuration page (as @somiaj suggests).

There is one comment you have that was essentially there before, but that needs to be clarified I think.  That is the comment that "Sending grades frequently may put a strain on the server, so you might want to turn this off
# by setting $LTIGradeOnSubmit = 0;".  Note that the `$LTIGradeOnSubmit` option will cause much less stress on a server than a mass grade pass back.  The grade submission that occurs when a student submits an answer for a homework assignment or even when a student completes a test will not even begin to tax the weakest server.  In the case of a test, the grade submission becomes a completely negligible process compared to the server's chore of grading the test itself.  These are one or two (with $LTICheckPrior) minor network requests made and responses processed that are extremely low in resource usage.  A general mass grade pass back is the real strain on a server.  When that occurs the server must compute the grades for all students and assessments and make all of these requests and process all of the requests at one time.

2024-11-09 21:23 UTC, drgrice1 commented
Something when wrong when I cut and pasted the comment from before.  Sorry about that.

2024-11-09 21:24 UTC, drgrice1 commented
Okay, it wast the `#` symbol that I didn't delete.  It is fixed.

2024-11-09 21:24 UTC, somiaj commented
My, what a long header you had there.

2024-11-09 21:37 UTC, drgrice1 commented
What we really need is for mass grade pass back not to be triggered by some user accessing the course as it is currently done.  With that approach mass grade pass back is guaranteed to occur when at least one user is active.  Instead it should be something that could be scheduled at a particular time.  That way a system administrator could schedule mass grade pass backs to occur outside of peak server usage times.  Furthermore, mass grade pass back for different courses could be scheduled to occur at different times.  Currently mass grade pass back for different courses could all be queued at the same time.  The job queue prevents them from all happening at the same time, but in that case they will happen one after the other.  As soon as one job completes the next one starts (with up to 60 seconds in between).  Meaning that the server could be busy for quite a while if several large courses are queued at once.

2024-11-09 21:43 UTC, somiaj commented
Could we use a systemd `.timer` unit for this?

2024-11-09 21:47 UTC, somiaj commented
Though if using a timer unit, this would be something an admin would have to setup, and there would need to be an option in the course configuration that just enables or disables mass updates, no longer letting users configure the time. But it could be an optional approach to configuring mass updates.

2024-11-09 21:56 UTC, Alex-Jordan commented
Thanks both, I took @somiaj's wording in that one place, and changed the language around "server strain" where @drgrice1 pointed to.

I suggest that further changes about how LTIMassUpdateInterval works be made after this PR is settled.

2024-11-10 18:21 UTC, Alex-Jordan commented
I just pushed a bunch here to help me migrate it to my test server from my development server. The difference is the test server is linked to PCC's test D2L instance. I will test things out there, possibly make edits, and report here.

2024-11-10 19:12 UTC, somiaj commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
Should `status` be `grade` or `score`. I don't think most users know we call this `status` in the database.

2024-11-10 19:27 UTC, Alex-Jordan commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
"status" here is not the thing we know internally that status means. Here, it is meant to mean "regardless of whether or not the set has met its LTISendGradesEarlyThreshold. Do you have a suggestion for changing that? I don't want to literally use variable names like "LTISendGradesEarlyThreshold" in the short doc.

2024-11-10 19:46 UTC, Alex-Jordan commented
I manually assigned myself 100% on all exercises in a set. I was confused when this was not being passed to the LMS. Then I realized I had not "attempted" an exercise from that set. (No exercises in the db had the `attempted` column set.) So I had not met the "attempted" threshold.

Should I update the check for "attempted" to also look if problem status is greater than 0?

2024-11-10 19:47 UTC, somiaj commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
My initial thought was just to use "grade", though I guess here that includes "attempted" as well, so I do see why status was chosen now. What about something that doesn't try to reference the conditionals below, so along the lines of "Date to always send scores to the LMS."

2024-11-10 19:51 UTC, somiaj commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
Looking at the options closer below, I think "When to always send scores to the LMS." would be clear, description can clarify.

Also looking at the options below, I think they need to be wrapped in `x()`, so `x('After the open date')`, for translation. But looking around no labels are translated, so this is probably something that should be addressed in another PR.

2024-11-10 19:54 UTC, somiaj commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
Just double checked, `($c->maketext($self->{labels}{$val})`, the labels are translated so `x()` will flag them for translation. This isn't done consistently, so that could be a future PR.

2024-11-10 19:56 UTC, somiaj commented
This does sound like an edge case, as even manual graded problems should have a single attempt. But I guess it won't hurt just in case someone decides to override grades this way (vs just doing it in the LMS which I would think would be more common to give students credit for a non attempted assignment).

2024-11-10 20:00 UTC, somiaj commented
Though I guess one reason to override the grade in webwork vs the lms is once the always send after date is passed, to keep zeros from being sent (if for some reason an instructor wanted to give credit for a non-attempted assignment due to some unforeseen issue). I can't see why anyone would want the other behavior, score > 0, but not attempted not getting sent back.

2024-11-10 20:06 UTC, drgrice1 commented
We don't need to concern ourselves with an instructor setting grades in the LMS instead of webwork. The correct place to set a grade override is at the source which is Webwork.

2024-11-10 20:07 UTC, Alex-Jordan commented
Right but what about like a student uses an achievement item to give themselves 100% on an assignment? I think that case alone justifies making a nonzero score on a problem also qualify as "attempted".

2024-11-10 20:08 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
The `x()` should be added now in this pull request. If there are any missing as those.

2024-11-10 20:08 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
Add those I mean.

2024-11-10 20:08 UTC, Alex-Jordan commented
This was not about me setting a score in the LMS. I used Instructor Tools to award myself 100% on an assignment within WeBWorK. And then that was not enough to qualify as "attempted" for the new threshold condition for sending a grade to the LMS.

2024-11-10 20:09 UTC, somiaj commented
I had overlooked achievements, so that is even more reason to add the check IMO.

2024-11-10 20:10 UTC, Alex-Jordan commented
How do I get something from `lib/WeBWorK/Utils/Sets.pm` to write a log entry into `webwork2.log`? Things I'm trying are not working even though I am certain a subroutine is being called.

2024-11-10 20:10 UTC, drgrice1 commented
I was referring to @somiaj's comment.

2024-11-10 20:13 UTC, Alex-Jordan commented
Oh I see. And it's worse than that. If you override a score in the LMS, the next time there is a passback it will overwrite your override.

2024-11-10 20:18 UTC, drgrice1 commented
What log are you trying to write to from Sets.pm?

2024-11-10 20:20 UTC, Alex-Jordan commented
I just want to be able to generate debugging messages from there. For example in `sub grade_all_sets`, it loops through all of a user's sets. Some sets will be included in the calculation and some not, now that there is the threshold and the critical date to consider. I'd like to log which sets are included/excluded just for debugging while I work on this. But I don't meant to keep any such logging here once I am done.

2024-11-10 20:23 UTC, Alex-Jordan commented
I have brought back to life an old WW test server that connects to PCC's D2L test instance. I got single sign-on working with LTI 1.1 so far. So I'll actually be able to test this all before I ask you to test with Canvas or Moodle. But debugging within that module would help and I'm missing something fundamental about how to do that.

2024-11-10 20:27 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
Wait, you are talking about labels specifically here.  I will need to check if those can be translated.  None of them currently are in this file.  Adding `x()` may not even do anything unless `maketext` is called on the values later when used.  So that should wait for another pull request probably.

2024-11-10 20:31 UTC, somiaj commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
@drgrice1 I double checked this, in `ConfigObject/popuplist.pm` the only call of the labels I see is

```
return $c->c($c->maketext($self->{labels}{$val}))->join($c->tag('br')) if ($self->{labels}{$val});
```

and

```
map { [ $c->maketext($self->{labels}{$_} // $_) => $_, $default eq $_ ? (selected => undef) : () ] }
```

So they are being translated there, just not flagged.

2024-11-10 20:32 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
Okay, so `maketext` is called on those values.  So the labels should have the `x` on them.  You can do that here if you want to.  Probably the `pg{ansEvalDefaults}{reducedScoringValue}` labels don't need it, but the rest should have it.

2024-11-10 20:38 UTC, drgrice1 commented
A `debug` call should work from the `Sets.pm` file if you add `use WeBWorK::Debug`.   Make sure to set `debug` to log to a file with the `logfile` option in webwork2.mojolicious.yml.

A `warn` statement will not work when run from the job queue, as you have probably observed.

You can also run a minion worker directly from the command line to see more.  In that case a `warn` statement will work.  Just run `/opt/webwork/webwork2/bin/webwork2 minion worker`.

2024-11-10 20:49 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
So it seems that these labels have never been inside the `x` call.  So it is an old oversight.

2024-11-12 22:50 UTC, Alex-Jordan commented
I think this is ready to look at. It has the changes we discussed in the meeting today.

2024-11-12 22:53 UTC, Alex-Jordan commented
I just made a force push; it was only for perltidy though.

2024-11-14 05:06 UTC, drgrice1 requested changes
I haven't tested this thoroughly yet, but i found a few issues that I commented on.

Then I looked a little closer at the structure of this, and I have a real problem with it.  This more than triples the computational complexity of grade pass back in some cases when `$LTIGradeOnSubmit` is used, and more than doubles the computational complexity when mass grade pass back occurs.  The `can_submit_LMS_score` method is really expensive because it can call `grade_set` (either directly or via `grade_gateway`), and can end up being called three times.  In addition `grade_set` will be called again if using "homework" grade pass back mode.

This much increase in the complexity is certainly not acceptable.  The set grading methods simply can't be called that many times.  Their complexity is already high to begin with.

2024-11-14 05:23 UTC, Alex-Jordan commented on conf/authen_LTI.conf.dist
> +#$LTISendScoresAfterDate = 'close_date';
This was inadvertent. An earlier version used `close_date` everywhere and apparently I missed a place to change it to `due_date`. Probably because this is in `conf` and I only searched `lib`.

There's no problem with it being 'reduced_scoring_date' because if that is not defined, it is designed to fallback to the `due_date`. A student will consider a reduced scoring date to be the "due date" and that's when they will expect to see grades appear in the LMS.

2024-11-14 06:00 UTC, Alex-Jordan commented
> Then I looked a little closer at the structure of this, and I have a real problem with it. This more than triples the computational complexity of grade pass back in some cases when $LTIGradeOnSubmit is used, and more than doubles the computational complexity when mass grade pass back occurs. The can_submit_LMS_score method is really expensive because it can call grade_set (either directly or via grade_gateway), and can end up being called three times. In addition grade_set will be called again if using "homework" grade pass back mode.

I'll think about ways to mitigate this. There is already one thing to do. The real reason that `can_submit_LMS_score` is used in `ContentGenerator/GatewayQuiz.pm` and `Utils/ProblemProcessing.pm` is because of `course` grade passback mode. You grade one set (the current set) and possibly save the server from calculating an entire course grade. So that is actually there to reduce complexity when in `course` grade mode. For the times when `can_submit_LMS_score` comes back true, the cost is effectively grading n+1 sets instead of just n and that seems like a good trade. But this could be specifically assessed if we are in course grade mode only, and that cuts one of the calls that you counted with "homework" grade mode.

I'll make that change first and then see what more could be done.

2024-11-14 06:18 UTC, Alex-Jordan commented
OK, next up will be to make `can_submit_LMS_score` be more than just a boolean. If it would return true, I will change it to actually return the score of the set it was applied to. Then this score can be used by whatever called it instead of rescoring.

2024-11-14 06:20 UTC, Alex-Jordan commented
> OK, next up will be to make can_submit_LMS_score be more than just a boolean. If it would return true, I will change it to actually return the score of the set it was applied to. Then this score can be used by whatever called it instead of rescoring.

It will have to do something special to distinguish between returning false and returning a 0 score that should be scored. But that will be doable.

But none of it tonight :)

Is this heading in a direction that will address things?

2024-11-14 14:31 UTC, drgrice1 commented
Sorry, this is a bit unorganized (probably because my thoughts on this are not entirely sorted out yet), but this is a start on attempting to convey issues in this pull request and more generally that I am seeing in the code.

There is a problem that is emphasized by pull request #2455, and again emphasized with this pull request, but goes all the way back to the initial implementation of the `GatewayQuiz.pm` module.  That is the module was implemented by copying a lot of the `Problem.pm` code, and making little changes here and there instead of breaking out into a shared module to prevent code duplication and make later maintenance convenient.  So now every time that we update code in one module, we need to check the other module to make sure that it gets updated appropriately.  The problem is that when #2455 occurred that didn't happen.  As such, when grades are submitted in a homework set, a student gets the messages added in #2455, but when grades are submitted in a test the student only gets the old submitted or not submitted message even though the same logic applies.  Now this pull request is making more changes to this duplicated code (at least in this case the change is being made consistently between the two modules at this point).

What really needs to happen is that lines 253-288 of ProblemProcessing.pm need to become something like
```perl
if ($ce->{LTIGradeMode}) {
    my $passBackMessage = update_grade_on_submit($c);
    $scoreRecordedMessage .= $c->tag('br') . $passBackMessage if $passBackMessage;
}
```
and lines 1027-1043 of GatewayQuiz.pm need to become something like
```perl
$c->{passBackMessage} = update_grade_on_submit($c)
    if $c->{submitAnswers} && $will{recordAnswers} && $ce->{LTIGradeMode};
}
```
and then the appropriate change made in the GatewayQuiz.html.ep file to display that message if set.  (Note that the controller is the only argument passed to the `update_grade_on_submit` method and actually has everything that is needed.  More on that later.)

Then all of the processing done in lnes 254-287 of ProblemProcessing will be done in the `update_grade_on_submit` method which is a method exported from a module shared between the two LTI authentication modules and shared between the GatewayQuiz.pm and Problem/ProblemProcessing.pm modules.  I realized there already is a utility region shared between the two LTI authentication modules.  That is the `WeBWorK/Authen/LTI` directory/name space.  Either a new file should be added in that directory that will contain all of these utility methods added in this pull request (including the `update_grade_on_submit` method suggested here), or the MassUpdate.pm file renamed to something more generic like GradePassback.pm and it should include these new methods as well as the `mass_update` method.  (I think I prefer renaming the MassUpdate.pm file.)

Now as to the issue of making both the `submit_course_grade` and `submit_set_grade` methods efficient, clearly we need to get to point that the `grade_set` or `grade_gateway` method is only called once.  That needs to be inside the methods themself (or with care in a method only called once from within those methods as you suggested).  Now "course" grade passback mode needs to know the current merged set being graded in the case of `$LTIGradeOnSubmit` being true.  The `$c` controller already has that.  Both the GatewayQuiz.pm and Problem.pm modules set `$c->{set}` to the needed merged set (it is even a versioned set for tests).  So that can be obtained and passed to the `can_submit_LMS_score` method so that method does not need to get it from the database.

In general, one of the primary issues with this pull request is the all of the redundant database queries that are being made.  This is really a continual problem through out the webwork2 code.  It seems that many developers see the simplicity of calling `$db->getWhatIsNeeded` and just do it all over the place without thinking about the consequences.  Database queries are expensive.  A worst case scenario is in a loop, but a more obscure case is when these calls are in utility methods that end of getting called numerous times.

As mentioned above, the GatewayQuiz.pm and Problem.pm modules have already obtained the merged set from the database, but then this gets it directly from the database again in `can_submit_LMS_score` and then maybe again in `set_attempted`.  Instead of passing the `set_id` pass the database set record obtained from `$c->{set}` to avoid that.

Now the `grade_set` and `grade_gateway` methods are another problem in that they always obtain the merged problems from the database.  This is something that has been on my radar for a while now.  This is the primary inefficiency of those methods.  In many of the cases that they are called, those merged problems have also already been obtained from the database elsewhere before they are called.  In other cases (like the grade_all_sets method or in the Grades.pm module or generally anytime sets are graded) it would massively speed up things if the caller obtained all problems from the database in one query before calling these methods.  I also note that the `set_attempted` method added in this pull request adds to this redundancy by once again getting all merged problems for the set.  Most likely there needs to be an optional argument passed to `grade_set` or `grade_gateway` that is an array reference containing these merged problem records.  If the optional argument is passed, then the methods just use the problems in the array, and otherwise it gets them from the database.

2024-11-15 01:41 UTC, Alex-Jordan commented
I understand what you are saying. I'm not coming up for air for anything serious for a few days, as I have a mound of grading. (I may do some less time-intensive PR reviews though.) When I come back, are you recommending that I *not* follow through with changes that would minimize database calls for this specific PR, because you are planning a larger scale rewrite anyway? I could either pause this until future notice or push through with the basic idea I mentioned yesterday.

I do want to eventually have two aspects of this in production that are relevant at PCC. One is letting null scores become zero in a mass passback following a critical date. The other is not passing scores that are lower than 70% prior to the critical date. (I think you and Jaimos would prefer the "attemtped" setting, but my sense is that PCC faculty would want to wait until the score is not jarringly low.)

2024-11-15 01:49 UTC, drgrice1 commented
I think I will try to work on it when I have time, but you can go ahead and try to minimize the database calls when you have time.

2024-11-16 04:01 UTC, Alex-Jordan commented
I pushed with some changes. It is a force push because I also rebased off develop.

Now the database calls concerning problem scoring are close to optimized.
* The real work is done in `grade_set`
* `grade_set` is called by some things that have nothing to do with this PR, but relevant to this PR, it can be called by `grade_gateway` or `can_submit_LMS_score`.
* Relevant to this PR, the only thing that calls `grade_gateway`  is `can_submit_LMS_score`. So now we are down to `can_submit_LMS_score` being the only thing that matters. It will call `grade_set` once, either directly or via `grade_gateway`.
* `can_submit_LMS_score` can be called by `grade_all_sets` or `submit_set_grade`. The only thing that calls `grade_all_sets` is `submit_course_grade`. So effectively it is either `submit_set_grade` (calling `can_submit_LMS_score` once) or `submit_course_grade` (calling `can_submit_LMS_score` n times as it loops over all sets).
* Additionally, the only other time `can_submit_LMS_score` may be called is within `Utils/ProblemProcessing.pm` and `ContentGenerator/GatewayQuiz.pm`. These might call `can_submit_LMS_score` but only in "course" grade mode, as a check that might allow us to skip calling `grade_all_sets`.

Additional observations:

- for grading all sets to get the "course" score, it would be faster if that could be one database call to the problem_user table instead of looping over all sets. But I think looping is necessary since we have to merge sets and consider the critical date and threshold on a set by set basis.
- this is possibly still inefficient with multiple calls to `earliest_gateway_date`. Each call loops through all versions of a test, but it's not the same order of magnitude as looping through the long lists you get from problem_user.

2024-11-18 14:39 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +		# achievement item has awarded credit for one exercise somewhere in the test
Please fix comments added in this pull request with capitalization and proper punctuation.  This currently reads "if there is one version, check for an attempted problem there could also be no actual attempted problems, but something like an achievement item has awarded credit for one exercise somewhere in the test" which is a run on sentence.  It should be "If there is one version, check for an attempted problem.  There could also be no actual attempted problems, but something like an achievement has awarded credit for one exercise somewhere in the test."

Although, I don't believe that your comment about achievements is actually possible.  The achievement items that change single problem scores are not available for tests.  This is because this isn't actually possible for tests.  If there is no test version, then there aren't actual problem records in the database for this set and user, and so you can't set scores (the `status`) for problems.

2024-11-18 15:05 UTC, drgrice1 commented on lib/WeBWorK/Utils/ProblemProcessing.pm
> +					{
This check really needs to not be done here (and also not in GatewayQuiz.pm).  As I mentioned before, this needs to be revamped so that the only check is if `LTIGradeMode` and `LTIGradeOnSubmit` are set.  I mentioned in another comment the only time that the return values of `submit_set_grade` and `submit_course_grade` are used are here and in GatewayQuiz.pm when `LTIGradeOnSubmit` is true.  When a grade pass back occurs via the job queue (a mass grade pass back if you will), the return result is completely ignored.  So make those methods return the appropriate message for the user instead of returning 0 or 1.  Then here and in GatewayQuiz.pm it just uses the message that is returned.

If this is done, then all processing that determines when grades are submitted and the appropriate message to show can be done in the `SubmitGrades.pm` modules (and utility methods called from there).  Furthermore, then the messages are assured to be uniform between tests and non-tests.

In addition with this change, the messages can be made more appropriate.  With the current setup if `LTIGradeMode` is `homework` and the grade is not submitted because the new criteria are not met, then the message will be message will be "Your score was not successfully sent to ...".  That isn't correct in that case.  It isn't that there was a lack of success, it is that WeBWorK chose not to send it.

Is the current message even correct in the case that `LTIGradeMode` is `course` and the criteria is not met?  If `can_submit_LMS_score` returns false in that case, then the user will be shown the message `Scores are sent to ... every ...`.  That doesn't seem right, because in this case when the mass grade pass back occurs, the `can_submit_LMS_score` will also return false, and even then the grade will not be submitted to the LMS.  So the user was told it would be sent after some time, but then it isn't, and the user might go look for the score in the LMS after that time has passed and it still won't be there.

2024-11-18 15:14 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +	}
This should be
```suggestion
	my $earliest_date = -1;
	for my $i (@versionNums) {
		my $versionedSetDate =
			get_LTISendScoresAfterDate($db->getSetVersion($userSet->user_id, $userSet->set_id, $i), $ce);
		$earliest_date = $versionedSetDate if $earliest_date == -1 || $versionedSetDate < $earliest_date;
	}
```

The current code will always get the zero indexed set from the database twice.  That is unnecessary.

2024-11-18 15:17 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +sub can_submit_LMS_score ($db, $ce, $userID, $setID) {
This should take a database set record object instead of the `$setID`.  That has already been obtained from the database (or will be immediately after this is called in one case, but that call can be moved up) every time this is called and can be passed in and used without the need to obtain it from the database again.

2024-11-18 21:16 UTC, Alex-Jordan commented
Thanks for your review of this. I will make some changes to address what I can for now.

2024-11-18 21:33 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
I looked closer at this now, and I see that you are checking attempted for the first problem and the status for all problems.  In lieu of my previous comment regarding achievements, I don't think the for loop is even needed.  Checking any problem for `attempted` is sufficient.  All of the achievement rewards that change problem scores are hard coded to apply only to sets with `assignment_type` set to `default`, and so student's won't be able to use them for gateway quizzes.

2024-11-18 21:52 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
Did you see that the initial check is about the `attempted` status, while the checks in the loop are about the score?

Here it checks the `attempted` attribute for the 0th problem. In most cases where a test has been attempted, this will immediately trigger the `return 1` and the loop that follows will not be run. Note that it would be wasteful to also examine the 0th problem's score here. Whether that score is 0 or higher, we don't care at this point. We are just checking the `attempted` attribute.

Now If the test was never submitted, the code continues. It may be that some problem score has been manually overridden, and we are looking for that. We have to loop through all of the problems and look at the score. Now looking at the `attempted` attribute would be unnecessary and we only look at the score.

I could delete line 164 and move line 65 into the loop, but only conditioned on the index being 0 for the sake of efficiency. And then the 0th problem database call would only happen once. The cost would be all the checks for whether or not the index is 0 as we go through the loop. Is that better than it is now?

2024-11-18 21:57 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
Yes.  That is what I just said.  I am saying that I do not believe your comment about achievements is possible for problems in a test.  It simply isn't implemented.  So the only way I can think of that the status for a problem could possibly be greater than 0 with no attempts is if the instructor used the problem grader to change the score before the student has even attempted the problem.  That doesn't make sense to do, and isn't something that we should support.

2024-11-18 22:01 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
Sorry, messages crossing. When I had this page open to post replies, it wasn't updating with the newer comments.

I already changed the comment about achievements. But I disagree about the instructor manually overriding the score. Just spitballing a scenario, you have a student who must use pencil an paper because of accommodations. You manually score their paper test, but you want to put the grades into WeBWorK so you can manage grades consistently for your whole class. You would then initialize a test for that student and manually enter scores.

2024-11-18 22:18 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
Then you can also submit the test first so that you have valid problems to work with.  Furthermore, you can add comments to problems if that is done.  Comments can not be added if the test is not submitted.  So I don't see that scenario as valid either.

2024-11-18 22:33 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
It really doesn't seem that it requires any knowledge of how it works under the hood to think that you need to submit a test to grade it.

Even in the proctoring case, if you want a grade, then you need to submit it.

Really, it is more natural to think that a submission is needed to grade a test than you are claiming.

You are covering rather rare circumstances that are really out there.  This is just something that doesn't make sense.  Sometimes it seems to really stretch to find some reason to implement something that really doesn't make sense.  This is one of those situations.

2024-11-18 22:35 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
Also that scenario is just one scenario I rattled off. One more that comes to mind quickly is a student takes a test but the time runs out before they submit it. They have paper work they give the instructor, and the instructor accepts that it was an honest mistake and it's not a concern that too much time was available. They go in and manually override the scores.

We have pathways that will let an instructor manually edit scores. As long as we have those, I think we have to consider those. If you truly mean this is not something we should support, then we should disable the instructor's ability to override scores on an unsubmitted test.

2024-11-18 22:37 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
I completely agree that we should disable the capability of an instructor to override scores on an unsubmitted test.

2024-11-18 22:41 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
> The instructor can still do that if the test is overtime.

Is this apparent to a test-using instructor? I don't use them and I didn't know you could do this.

2024-11-18 22:47 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
I use tests in numerous scenarios. None of your suggestions have come up in a way that makes sense for the code that you are adding here.

If a student does not submit an exam because it went overtime, then the instructor can enter the answers for the student and submit it.  That is better than what you are suggesting, because then the answers are saved too.  If the instructor is doing things right, the test would be designed with multiple pages.  Then the answers are already in the system, and all the instructor needs to do is submit the test for it to be graded.

To submit a test, the instructor has to go the course configuration, and change the `Can submit answers for a student` permission to `professor`.  It is not entirely apparent, but can be done.  Much of webwork2's design is not as intuitive as it should be.

Let me go on record as saying that the headache that you are talking about is caused by this pull request.  What you are attempting to do with the "threshold" and such really doesn't entirely make sense to me.  It is something that I have never seen in any other system ever.

2024-11-18 22:47 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +sub can_submit_LMS_score ($db, $ce, $userID, $setID) {
I'm just getting to this comment. Should I stop putting time into addressing this and that? Are you restructuring things either at the level of this PR or deeper?

2024-11-18 22:56 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +sub can_submit_LMS_score ($db, $ce, $userID, $setID) {
Generally deeper.  Currently, the grades page loads rather slowly if a course has a lot of sets.  The same improvements that would speed this up would also speed that up.  The issue is that when multiple sets are being graded, the `grade_set` method gets the problems for each set one set at a time.  There is a way to get all problems with one query, and is massively faster.  If `grade_set` is called, then those could be passed in and used if provided instead of the method needing to get them from the database.  The point is that the `grade_all_sets` method would do this, as well as getting all sets from the database in one query.

Although ignore all of that for now.  I see now that the `grade_all_sets` method should have the set.  It is this pull request that changed that.  My first comment is valid, and my second comment is not.  Get the sets in the `grade_all_sets` method the way it is in develop, and pass the set record with the method call instead of the set id.  Don't keep getting the set record from the database each time.

2024-11-18 23:01 UTC, somiaj commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
I agree that this logic is not needed, if a past due test version has not been submitted at least once, there has been some error. As a side note, I would like an easier way to submit a test version that is overtime and hasn't been submitted (for some reason) using the students saved answers.

2024-11-18 23:04 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
>  It is something that I have never seen in any other system ever.

And?  Should I start listing all the nice things that WW does that other systems do not do? Our standards are higher than just "do what other systems do".

I don't understand why people would want or use several features of WeBWorK/PG. I get it if you do not understand the threshold feature. But actually, I don't get that... Maybe it has to do with my student population thoguh.

I've pushed the changes I've made from your feedback today, excluding the parts about `lib/WeBWorK/Utils/ProblemProcessing.pm` and `GatewayQuiz.pm`. (Which are not forgotten or overlooked, just returning to my day job for now.) Thanks as always for your time and attention to detail.

2024-11-18 23:05 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
I agree that submitting a test for a student should be easier.  Particularly in the case of the test going overtime.  This used to happen all of the time with MWSU's placement exam, and I had to go change the permission to allow myself to submit the exam and then change it back afterward (because it can be dangerous -- if you want to check answers for a student test you can't do that when you have the permission).

2024-11-18 23:10 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
> > It is something that I have never seen in any other system ever.
> 
> And? Should I start listing all the nice things that WW does that other systems do not do? Our standards are higher than just "do what other systems do".

I agree.  I am just getting a bit frustrated with the structure of this pull request and all of the redundant database queries.  I am concerned about the stress that all of this is going to put on the server when a grade pass back occurs.  I apologize for the backlash.

2024-11-18 23:11 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +sub can_submit_LMS_score ($db, $ce, $userID, $setID) {
> There is a way to get all problems with one query, and is massively faster.

I thought about this while working on this PR. If the database call is done in that way, the issue will be how do you exclude problems that come from sets that have not yet passed the critical date and have not met their threshold (be it an 'attempted' or numerical threshold)?  I'm not saying there is no solution to that, but I kept finding problems with potential solutions.

2024-11-18 23:15 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			return 1 if defined $problem && $problem->attempted;
I should point out that currently when a mass grade pass back occurs on my system for a single course it often takes three or four minutes for the job to complete.  That of course is with the current grade pass back code.  Some of that of course is due to network latency as the server communicates with the LMS, but a large part of it is the database queries already occurring in addition to the grade computations.

2024-11-18 23:16 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +sub can_submit_LMS_score ($db, $ce, $userID, $setID) {
You don't need to exclude those sets in the database query.  It is more efficient to get them from the database even if you don't need them.

2024-11-18 23:25 UTC, Alex-Jordan commented
That's what I mean though. Now that you have all those problem records, how
are going to exclude some from the overall course grade calculation?

On Mon, Nov 18, 2024, 3:16 PM Glenn Rice ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In lib/WeBWorK/Utils/Sets.pm
> <https://urldefense.com/v3/__https://github.com/openwebwork/webwork2/pull/2617*discussion_r1847413404__;Iw!!Ka_JY85zDv0FFw!g15562BPYd_SpaW8RzXPrugjMy8IUgEo54DjwVZ9vCaJSe9PC6CYTif_VyBXmLop6K4qCHiEyQHpMvvb27vUrMeD0c8$>
> :
>
> > +		return $set->open_date;
> +	} elsif ($ce->{LTISendScoresAfterDate} eq 'reduced_scoring_date') {
> +		return ($ce->{pg}{ansEvalDefaults}{enableReducedScoring}
> +				&& $set->enable_reduced_scoring
> +				&& $set->reduced_scoring_date) ? $set->reduced_scoring_date : $set->due_date;
> +	} elsif ($ce->{LTISendScoresAfterDate} eq 'due_date') {
> +		return $set->due_date;
> +	} elsif ($ce->{LTISendScoresAfterDate} eq 'answer_date') {
> +		return $set->answer_date;
> +	}
> +}
> +
> +# Checks if the set is past the LTISendScoresAfterDate or has met the LTISendGradesEarlyThreshold
> +# Returns a reference to hash with keys totalRight, total, score, criticalDate if the set has met
> +# either condition and undef if not.
> +sub can_submit_LMS_score ($db, $ce, $userID, $setID) {
>
> You don't need to exclude those sets in the database query. It is more
> efficient to get them from the database even if you don't need them.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/openwebwork/webwork2/pull/2617*discussion_r1847413404__;Iw!!Ka_JY85zDv0FFw!g15562BPYd_SpaW8RzXPrugjMy8IUgEo54DjwVZ9vCaJSe9PC6CYTif_VyBXmLop6K4qCHiEyQHpMvvb27vUrMeD0c8$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ABEDOADT7BQA2FYQDXIB7NT2BJYOTAVCNFSM6AAAAABROOJ5SCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINBTHE3DENJRG4__;!!Ka_JY85zDv0FFw!g15562BPYd_SpaW8RzXPrugjMy8IUgEo54DjwVZ9vCaJSe9PC6CYTif_VyBXmLop6K4qCHiEyQHpMvvb27vUqqGa7H4$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-18 23:27 UTC, drgrice1 commented
> That's what I mean though. Now that you have all those problem records, how are going to exclude some from the overall course grade calculation?

I don't understand.  You just don't use them.  You have all of the data including sets and dates.  You only use the problems for the set you are working on at one time.

2024-11-18 23:42 UTC, drgrice1 reviewed
This is what I meant by the set has already been obtained from the database every time that the `can_submit_LMS_score` method is called.

2024-11-18 23:42 UTC, drgrice1 commented on lib/WeBWorK/Utils/ProblemProcessing.pm
> +							$db, $ce, $problem->user_id, $db->getMergedSet($problem->user_id, $problem->set_id)
This should be
```suggestion
							$db, $ce, $problem->user_id, $c->{set}
```

2024-11-18 23:42 UTC, drgrice1 commented on lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
> +				&& can_submit_LMS_score($db, $ce, $effectiveUserID, $db->getMergedSet($effectiveUserID, $setID)))
This should be
```suggestion
				&& can_submit_LMS_score($db, $ce, $effectiveUserID, $c->{set}))l
```

2024-11-18 23:44 UTC, Alex-Jordan commented
So the big set of problem records is an array. And that array will be partitioned into subarrays corresponding to the sets. And then the looping still happens, but all in perl without database calls. And that partitioning process to subdivide the initial big array of problem records is cheaper than multiple database calls one for each set.

Do I have that right?

2024-11-18 23:50 UTC, drgrice1 commented
Yes, that is correct.

2024-11-19 01:11 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +	my $score  = $total > 1 ? $totalRight / $total : 1;
This isn't correct.  It should be
```suggestion
	my $score  = $total ? $totalRight / $total : 0;
```
If a set has one problem with a value of 1, then with `$total > 1` this will always give a score of 1 even if the student does not have a score of 1 for the problem.  It will never consider the actual student score.

`1` cannot be used in the case that `$total` is 0.  If the total is zero that either means there are no problems in the set, or all problems in the set have a value of 0, and for gateway tests it could also just mean that no versions of the test have been taken (`grade_gateway` will return `(0, 0)` in this case).  So this would submit a score of 1 for the case that a student has not taken a gateway test.

2024-11-19 01:53 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +	my $score  = $total > 1 ? $totalRight / $total : 1;
Oops, I must have meant `>=`. I understand what you are saying about Gateway. If not for that, I was thinking it would be nice to let 0/0 mean 100%.

2024-11-19 02:03 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +	my $score  = $total > 1 ? $totalRight / $total : 1;
Why even use a numeric comparison though?  The value of a problem must be an integer (it is type INT in the database).  That is a restriction that we will remove for webwork3 (I already brought this up when @pstaabp originally implemented it as an INT for webwork3 and it was changed).  It can't be between 0 and 1.  So just using `$total ? ...` will give the same end result as `$total >= 1 ? ...` and is a more efficient comparison.

Yeah, I am not sure what to do about the cases where there are no problems in a set, or all problems have a value of 0.

2024-11-19 02:59 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +	my $score  = $total > 1 ? $totalRight / $total : 1;
I'm not arguing to make it a numerical comparison, but just to answer this question:
> Why even use a numeric comparison though? 
If a person were to write their code that way, they may be in good faith just trying to make it more readable, as in closer to grammatically correct English. Trading away some negligible efficiency for what they see as code readability. But yes, I'll make it the way you suggested here.

2024-11-19 03:12 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +	my $score  = $total > 1 ? $totalRight / $total : 1;
`x >= 1` really doesn't add clarity when you really want `x > 0`.  Note that `x > 0` is a more efficient comparison than `x >= 1` also.  I would accept that here.

2024-11-19 03:14 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +	my $score  = $total > 1 ? $totalRight / $total : 1;
The point is that we want to avoid by 0.  So generally if this were not guaranteed to be positive, then `if (x) ...` would be better.  It is perfectly clear also.  Really adding `> 0` doesn't add clarity for something that occurs so frequently in coding.

2024-11-19 03:22 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +			my @problemNums = $db->listUserProblems($userID, $setID);
This should be
```suggestion
			my @problemNums = $db->listProblemVersions($userID, $setID, $versionNums[0]);
```
`listProblemVersion` is the versioned equivalent of `listUserProblems`.

2024-11-19 03:30 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +		$return->{critical_date} = $critical_date;
This should be
```suggestion
		$return->{criticalDate} = $critical_date;
```
Otherwise the code that checks this in `grade_all_sets` will fail.

2024-11-19 03:47 UTC, Alex-Jordan commented on lib/WeBWorK/ConfigValues.pm
> +			doc  => x('When to send scores to the LMS regardless of status'),
I changed the wording on the `doc` here.

2024-11-19 04:22 UTC, Alex-Jordan commented
The last commit (https://github.com/openwebwork/webwork2/pull/2617/commits/46bc5169e3c3a1c5fd35bd2b8bc99d0cb5d393cf) is one possible way to handle "0/0" scores. I can repeal that commit if this sounds bad, but what do you think?

2024-11-19 04:25 UTC, Alex-Jordan commented
Wait, there is an obvious problem with what I did, I will change it.

2024-11-19 04:33 UTC, Alex-Jordan commented
OK, now does the idea expressed in https://github.com/openwebwork/webwork2/pull/2617/commits/00c7234730e4b7f9606c909679cab7f036182a6a at lines 247-249 seem reasonable for handling scores of the form "0/0"?

2024-11-19 11:44 UTC, drgrice1 commented
Something isn't right with the changes in 00c7234.  On line 272 you check that `$ce->{LTISendScoresAfterDate} eq 'never'` inside a section of code where `$ce->{LTISendScoresAfterDate}` is guaranteed not to ever be `'never'`.  Clearly that is a problem.

This highlights the issue with the `never` setting.  In the documentation you have added in `authen_LTI.conf.dist` and `ConfigValues.pm` nowhere does it say what that setting really does or why it makes any sense to use it.  Looking at the code it seems to really mean to ignore dates and use the threshold only for determining when to pass grades back.  It seems confusing for the word "never" to mean that for the `LTISendScoresAfterDate`, and the setting is not well documented.

2024-11-19 12:00 UTC, drgrice1 commented
Another thing that bothers me on this pull request is the "attempted" setting for the `LTISendScoresEarlyThreshold`.  If `LTIGradeOnSubmit` is 1 and `LTISendScoresEarlyThreshold` is "attempted", then there is no need to do all of this extra processing in all of these utility methods you have added to determine that an attempt has been made.  When the grade is submitted you know even before any of the LTI methods have been called that the set has been attempted because that just happened.  This is true regardless of the type of assignment.

2024-11-19 12:16 UTC, drgrice1 commented
Also, on the `0/0` handling.  What if the assignment is a gateway test, but the test has the value of all problems set to 0.  This code will not distinguish between this case and the case that there are no test versions for the user.

2024-11-19 12:27 UTC, drgrice1 commented on lib/WeBWorK/Authen/LTIAdvanced/SubmitGrade.pm
> +	return await $self->submit_grade($userSet->lis_source_did, $score->{score},
The `$score->{score}` usage here will always throw an exception in the case that `$score` is undefined which will happen if `!$self->{post_processing_mode} && $ce->{LTIGradeOnSubmit} eq 'homework_always'` is true and the remainder of the settings are such that `can_submit_LMS_score` returns undef.

2024-11-19 14:15 UTC, drgrice1 commented on lib/WeBWorK/Authen/LTIAdvanced/SubmitGrade.pm
> +				{
This is still not right.  If `$oldScore eq ''` then this gives a warning because the first check that `$oldScore ne ''` is false and so the `abs($score - $oldScore) < 0.001` is computed but `$oldScore` is not numeric.

2024-11-19 17:14 UTC, Alex-Jordan commented
I've made changes based on this morning's feedback but not yet pushed. Except for:

> Also, on the 0/0 handling. What if the assignment is a gateway test, but the test has the value of all problems set to 0. This code will not distinguish between this case and the case that there are no test versions for the user.

I'd like to hear thoughts on doing this at all regarding "0/0" (sometimes it's 0, sometimes it's 1). If it's good to do that, I'll add code to distinguish the cases you describe. If not, I'll just remove the commit that has this.

> The $score->{score} usage here will always throw an exception in the case that $score is undefined which will happen if !$self->{post_processing_mode} && $ce->{LTIGradeOnSubmit} eq 'homework_always' is true and the remainder of the settings are such that can_submit_LMS_score returns undef.

If `can_submit_LMS_score` returns `undef`, I believe we have already exited this code block a few lines up:
``` 
        my $score = can_submit_LMS_score($db, $ce, $userID, $userSet, !$self->{post_processing_mode});
        return 0 unless ($score || !$self->{post_processing_mode} && $ce->{LTIGradeOnSubmit} eq 'homework_always');
```
and so there will be no exception thrown. Apologies if I'm misunderstanding something about how that plays out.

2024-11-19 17:19 UTC, Alex-Jordan commented
> If can_submit_LMS_score returns undef, I believe we have already exited this code block a few lines up:

Nevermind, I see my error. No need to explain further, thanks for seeing that.

2024-11-19 17:23 UTC, drgrice1 commented
Sorry, cross posting.

2024-11-19 17:40 UTC, Alex-Jordan commented
In code I haven't pushed, I added an optional parameter to `can_submit_LMS_score` that I called `$force_submit`, with default value 0. (Maybe that name is not best.)

If `can_submit_LMS_score` is called with 1 for `$force_submit`, you are saying that you want to get the score data provided by `can_submit_LMS_score` because you are going to submit scores to the LMS regardless (although possibly not if `LTICheckPrior` stops it). And so 1 can be used for situations you have described. If `$force_submit` is 1:
* there will be no date checking
* there will be no check using `set_attempted`

Also I believe this gets around the issue with `$score->{score}` when `$score` is `undef`, because with `$force_submit` we would never be in that situation. This is why I thought there would be no exception thrown a few comments ago. However I recognize the code is pretty fragile here, and I'll return later to do better.

2024-11-20 13:41 UTC, drgrice1 commented on lib/WeBWorK/Authen/LTIAdvanced/SubmitGrade.pm
> +				{
Lines 295-305 need to be changed to
```perl

				# Blackboard seems to return this when there is no prior grade.
				# See: https://webwork.maa.org/moodle/mod/forum/discuss.php?d=5002
				$priorScore = '' if $priorScore eq 'success';

				# Do not update the score if there is no significant change. Note that the cases where the webwork score
				# is exactly 1 and the LMS score is not exactly 1, and the case where the webwork score is 0 and the LMS
				# score is not set are considered significant changes.
				if (abs($score - ($priorScore || 0)) < 0.001
					&& ($score != 1 || $priorScore == 1)
					&& ($score != 0 || $priorScore ne ''))
				{
```

and the `$nullEqualsZero` optional parameter to the `submit_grade` method eliminated.

First, this makes the handling for Blackboard consistent with the handling for other LMS's (assuming that special case is even valid anymore).

Second, if the LMS does not have a score set, but webwork has a score of 0, then that should be considered a significant change, and the score should be updated.  If a 0 score should not be submitted because the criteria are not met, then the code should never come here.  In that case the `can_submit_LMS_score` should return undef, and this should never happen.  Currently this is preventing a score of 0 from being submitted in several of the cases that it should be.  For example, if it is after the critical date and the score is 0, then the current code will still NOT send the score.

Note that there is no need to check that `$priorScore ne ''` in the second condition.  In the case that the `$score` is 1 and the `$priorScore` is the empty string, the check that `$priorScore == 1` will never occur.

2024-11-20 13:41 UTC, drgrice1 commented on lib/WeBWorK/Authen/LTIAdvantage/SubmitGrade.pm
> +		{
This needs to be
```perl
		if (abs($score - $priorScore) < 0.001
			&& ($score != 1 || $priorScore == 1)
			&& ($score != 0 || (@$priorData && defined $priorData->[0]{resultScore})))
		{
```
and the `$nullEqualsZero` parameter for this `submit_grade` method eliminated.

The reasoning is the same as for the LTI 1.1 code.

2024-11-20 22:04 UTC, Alex-Jordan commented
It was a complication to add the 'homework_always' option for `$LTIGradeOnSubmit` and I think I am at the point where I can remove it. I want to check that @drgrice1 and @somiaj can still have a configuration that they want. I believe that you both want:

- `$LTIGradeMode` is 'homework'.
- `$LTISendGradesEarlyThreshold` is 'attempted'.
- When a mass passback happens, unattempted sets that have not reached their critical date are excluded.
- When a user submits a problem or a test, that set's scores are passed (assuming `$LTICheckPrior` is not a factor).

Do I have that right? If so then things have reached the point where 
```
$LTIGradeMode = 'homework';
$LTISendGradesEarlyThreshold = 'attempted';
$LTISendScoresAfterDate = 'due_date';   # assuming that you want that one
$LTIGradeOnSubmit = 1;
```
should do all that. And I can remove 'homework_always' from the code and documentation. It will remove some configuration possibilities, but I think I understand better now the specific configurations that you are each wanting and removing 'homework_always' will not hurt those.

2024-11-20 22:11 UTC, somiaj commented
That is the configuration I would use, though I'd use reduced scoring date, but minor difference.

I really don't see a use case for `homework_always` right now (I'd have to think more about that to see if it really adds that much, since I can achieve what I would like without it). You could also not try to go for every possible use case, and add it if the need arises.

2024-11-20 22:16 UTC, drgrice1 commented
Yes, that seems to describe what I want also.  I would probably actually use the current `reduced_scoring_date`setup.  That is, use that if enabled, and fall back to the reduced scoring date.  I do not use reduced scoring in my classes, but some of the other faculty do.

2024-11-20 22:23 UTC, somiaj commented
I haven't been closely following the code changes, but when using `$LTIGradeOnSubmit`, you could probably avoid a lot of the testing if the configuration is `attempted` since we know there is an attempt with the submit. If you can track that, you could bypass further testing in that case.

2024-11-20 23:00 UTC, Alex-Jordan commented
Thanks, 'honework_always' is going away.

I've been hyper focused on minimizing computational expenses with things
like what you just mentioned.


On Wed, Nov 20, 2024, 2:24 PM Jaimos Skriletz ***@***.***>
wrote:

> I haven't been closely following the code changes, but when using
> $LTIGradeOnSubmit, you could probably avoid a lot of the testing if the
> configuration is attempted since we know there is an attempt with the
> submit. If you can track that, you could bypass further testing in that
> case.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/openwebwork/webwork2/pull/2617*issuecomment-2489658508__;Iw!!Ka_JY85zDv0FFw!i3MGstEe4DUmz6BauYVueScXd-Pvb1d0UpsFPXi7yRsUFCK0f1tDtZSlFpOvu7x3f3HPPY_8PCr4oL2AohiPNColmRA$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ABEDOAAB45KYWUJ23MQ4NS32BUDY7AVCNFSM6AAAAABROOJ5SCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBZGY2TQNJQHA__;!!Ka_JY85zDv0FFw!i3MGstEe4DUmz6BauYVueScXd-Pvb1d0UpsFPXi7yRsUFCK0f1tDtZSlFpOvu7x3f3HPPY_8PCr4oL2AohiPmfHpQ5c$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-21 04:27 UTC, Alex-Jordan commented
I pushed all the changes that I've kept local and tweaked the past couple days. I may have missed something that was commented on, especially if my local code had already changed in that place.

* This no longer changes the files `Utils/ProblemProcessing.pm` and `ContentGenerator/GatewayQuiz.pm`, which I think was requested.
* As mentioned recently, the "homework_always" option for `$LTIGradeOnSubmit` is gone.
* In the case of a problem or test submission starting grade passback while in "course" grade mode, there is a check if the current set would be included in a course grade calculation. So that if not, we can skip the course grade calculation. But if that check passes, we do end up checking this set twice, calculating its score twice. This is a small inefficiency raising N set grade calculations to N+1, and it's worth it for the times when the N grade calculations get to be skipped and you only do the 1. Probably some more coding could be done to bring N+1 back down to N. At the moment it does not seem worth the complications it would add to the code.
* The logic tree in `can_submit_LMS_score` is a bit complicated, but that is all in the name of making sure we don't do database calls that we do not need given the configuration settings in effect and the status of the set (has it passed its critical date yet or met the threshold). Perhaps you will see ways to condense that without adding to the computational cost.

I tested a variety of configuration settings with LTI 1.1 (but not all possible combinations). Only with regular sets, not tests though. Things worked as expected.

2024-11-21 14:20 UTC, drgrice1 reviewed
First, thank you for your efforts in trying to improve the efficiency of this, and your work on this pull request in general.

Unfortunately, the efficiency of this is still really quite bad in many cases.  You improved the efficiency when the "attempted" setting is used with the "grade on submit" setting.  However, the efficiency of a mass grade pass back with the "attempted" setting is still really quite bad, and generally efficiency is quite bad in most other cases as well.  There is a way to do this that requires zero additional database queries than before, and less in many cases.

Another thing that I don't like is that these methods are being added to the general sets utility file that are specific to an optional authentication module.

You mentioned in your comment about your last changes that there are now no changes to the `Utils/ProblemProcessing.pm` and `ContentGenerator/GatewayQuiz.pm`, and that you believed that was requested.  I actually said the opposite.  I want those rather dramatically changed so that there is a utility method that is called, and that method should return the message to be shown to the user.  The point is that the messages for regular sets and tests are not in sync right now.  Part of this is because of the code duplication, and the fact that one location doesn't always get updated when the other is changed.

I have included some comments on a few things that I observed in your latest changes, but please do not act on those.  I am going to put in a pull request to this branch that improves the efficiency tremendously.  It is even more efficient that before even with all of the new conditions for determining when a grade pass back will occur being checked.

In my pull request the file `lib/WeBWorK/Authen/LTI/MassUpdate.pm` is renamed to `lib/WeBWorK/Authen/LTI/GradePassback.pm` and that file is a general utility file for grade pass back that is shared between the two LTI authentication modules.  All of the methods you added in `lib/WeBWorK/Utils/Sets.pm` are moved there.  Furthermore the `grade_sets`, `grade_gateway, and `grade_all_sets` methods that are still in that file are modified to accommodate the needs of LTI grade pass back.  Those changes will conflict with @somiaj's #2584, but will work for what he needs for that.  The `lib/WeBWorK/Authen/LTI/GradePassback.pm` file also has a `passbackGradeOnSubmit` method that is called by `ProblemProcessing.pm` and `GatewayQuiz.pm`, and handles calling the appropriate grade submission method, and returns the appropriate method for the user.

The efficiency comes from having the grading methods be called first, and those methods return the database objects they obtain for further processing to determine the conditions.  So after that there is literally no additional database access.

The handling of the zero values sets is removed and deferred for later discussion on this matter.

2024-11-21 14:22 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +					. 'configurable.</li></ul>'
Note my pull request does not change this.  I left this for you to think about.

2024-11-21 17:00 UTC, Alex-Jordan commented on lib/WeBWorK/ConfigValues.pm
> +			type => 'popuplist'
Not that it matters to me, but I was just aiming for scores that seemed like they might actually be used, and otherwise keeping the list short. I agree that 0.6 would be something to add. And I don't object to just adding all that you added.

2024-11-21 17:09 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +					. 'configurable.</li></ul>'
Okay, I took a stab at it.  I went with
`<li>If the LMS score is not 100%, but the WeBWorK score is, then even if the LMS score is only insignificantly less than 100%, it will be updated anyway.</li><li>If the LMS score is not set and the WeBWorK score is 0, this is considered a significant difference and the LMS score will updated to 0. However, the constraints of the $LTISendScoresAfterDate and the $LTISendGradesEarlyThreshold variables (described below) might apply, and the score may still not be updated in this case.</li>`
I think that is sufficiently generic, and not to wordy.

2024-11-21 17:10 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +					. 'exercise or there is one version with a graded submission.</p>'
Yeah, I have had issues like that when trying to format these long strings in the code also.

2024-11-21 17:13 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +		}
OK, and stop me if we should discuss this elsewhere later. My thoughts:

- Historically, some faculty do build a set where they make all weights 0. This would normally happen when it's some sort of orientation set. They would want the weights to be 0 if (a) they are using "course" grade passback mode and feel the orientation should be excluded from a grade. [Personally, I would just toss it in the mix though.]  And/or (b) they don't want the set contributing to the overall grade shown to a student in Grades, regardless of any LMS consideration. (Speaking to your point about grading in general, LTI aside.)
- If the above is not a legitimate case, and there are no legitimate other reasons to set the weights all equal to 0, we should prevent instructors from making a set with all weights being zero in the first place.
- If it is legitimate to make all weights be zero, then what next? What makes sense to me (in an ideal world that we may not have structure for) is that the set would have a score that is based on whether a user has visited the problems and seen the text on the screen. Like if they've seen 8 out of 10, their score is 8/10. And personally, for this purpose I would not care whether a problem was seen before/after the due date.
- Note that for LTI 1.3 score passback, this question does not matter. We will send the data (0, 0) to the LMS and it is the LMS's problem to deal with interpreting that. The question matters for LTI 1.1 score passback and for non-LTI scoring purposes.

2024-11-21 17:13 UTC, drgrice1 commented on lib/WeBWorK/ConfigValues.pm
> +			type => 'popuplist'
I also agree that many of the low values might not be used much, but someone might want to.  The setting can be set to anything between 0 and 1 if editing the config files, but from the UI it needs to be limited at this point.  I think that we need to beef up the "number" config value type so that number inputs are actually used, and there can be options for max, min, and increment.  Then that would be more suitable  for this.  That can wait until another pull request though.

2024-11-21 17:27 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +		}
> OK, and stop me if we should discuss this elsewhere later. My thoughts:

I think that this generally should be discussed in a developer meeting.  But we can share ideas on this here for now.  On the other hand, this pull request conversation is getting rather long.  So maybe we should discuss it elsewhere.

I just think that this should be removed from this pull request for now, until the discussion is had, and a decision on this made.  Certainly what is submitted needs to be consistent for both LTI 1.1 and LTI 1.3 as much as possible.

I think that the case of a set with no problems that is actually assigned to students is one that we need not consider.  I don't see any point in that being done, nothing could ever be submitted for the set, and I think that would only be done really by accident.  You haven't really mentioned this case, but it in theory could happen.

So the only case to really consider is that of a set with problems all of value zero.  I don't really see the point of this either, and don't think this is something that many (if any) would ever do.  So I really think that we shouldn't think to hard on this, and perhaps should just ignore the case.  Just make sure no exceptions are thrown for it.  I am not sure that it is really possible to prevent someone from creating such a set as you suggest.  But again, I don't think anyone really would.

2024-11-21 17:29 UTC, Alex-Jordan commented on lib/WeBWorK/Utils/Sets.pm
> +		}
> Note that for LTI 1.3 score passback, this question does not matter. We will send the data (0, 0) to the LMS and it is the LMS's problem to deal with interpreting that.

Well, I suppose if my suggestion to make the score be based on how many exercises were seen was good and viable, then we could send a score like (8, 10) after all.

2024-11-21 19:35 UTC, drgrice1 commented
It looks like you fixed the merge conflict correctly.

I have tested this with Moodle, but I haven't gotten around to testing with Canvas yet.  I will do that as soon as I can.

2024-11-21 22:19 UTC, drgrice1 approved these changes
I have now tested this with Canvas.  Everything seems to be working well.  If you feel like it you could add debugging messages as suggested in my comments.

2024-11-21 22:19 UTC, drgrice1 commented on lib/WeBWorK/Authen/LTIAdvantage/SubmitGrade.pm
> +	return -1 unless $score;
We might want to add a debug message here.  I was just testing this with Canvas, and found it useful to determine that a grade was not sent due to it not meeting the requirements.  Something like
```suggestion
	if ($submittedSet && !getSetPassbackScore($db, $ce, $userID, $submittedSet, 1)) {
		$self->warning('It is not after the $LTISendScoresAfterDate and the $LTISendGradesEarlyThreshold was not met. '
				. 'Not updating grade.');
		return -1;
	}
```
I am not sold on using the variable names in the message, although this is just a debugging message.  Perhaps just use words?

Also a similar message above for the `submit_course_grade` case would be good.

2024-11-21 22:19 UTC, drgrice1 commented on lib/WeBWorK/Authen/LTIAdvanced/SubmitGrade.pm
> +	return -1 unless $score;
For the debugging messages in this file make sure to check the `$ce->{debug_lti_grade_passback}` or `$self->{post_processing_mode}` variables.  So this could be
```suggestion
	return -1 unless $score;
```
```suggestion
	unless ($score) {
		$self->warning('It is not after the $LTISendScoresAfterDate and the $LTISendGradesEarlyThreshold was not met. '
				. 'Not updating grade for this set.')
			if $ce->{debug_lti_grade_passback} || $self->{post_processing_mode};
		return -1;
	}
```
I need to rework the `warning` message method in this file like I did in the `LTIAdvantage.pm` module to reduce the need for all of this checking (and it automatically calls `debug` for the messages as well).

Of course a similar message for the `submit_course_grade` in this file also.

2024-11-24 18:51 UTC, somiaj commented
This looks like it is about ready to go to me. I can't fully test this as I don't have a development system using LTI, but the defaults and ideas look good to me. @Alex-Jordan do you want to update the final debugging suggestions?

2024-11-24 21:23 UTC, Alex-Jordan commented
I'm out of today, but I wanted to do a last round of D2L testing. If we
merge now I'll get lazy and not do that :)

On Sun, Nov 24, 2024, 10:51 AM Jaimos Skriletz ***@***.***>
wrote:

> This looks like it is about ready to go to me. I can't fully test this as
> I don't have a development system using LTI, but the defaults and ideas
> look good to me. @Alex-Jordan
> <https://urldefense.com/v3/__https://github.com/Alex-Jordan__;!!Ka_JY85zDv0FFw!mMRp1vb9rNQF-zxde64NPoApql2YB0lTkwuqRFvXYRQXZukpcCRmglkPd1FxWDgWuQeHJ8z5hEzZL9_IuN9VvxbKuxA$>
> do you want to update the final debugging suggestions?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.com/v3/__https://github.com/openwebwork/webwork2/pull/2617*issuecomment-2496168904__;Iw!!Ka_JY85zDv0FFw!mMRp1vb9rNQF-zxde64NPoApql2YB0lTkwuqRFvXYRQXZukpcCRmglkPd1FxWDgWuQeHJ8z5hEzZL9_IuN9V_PDrA3g$>,
> or unsubscribe
> <https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ABEDOAATM2V475MLD6NHIA32CIN4TAVCNFSM6AAAAABROOJ5SCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJWGE3DQOJQGQ__;!!Ka_JY85zDv0FFw!mMRp1vb9rNQF-zxde64NPoApql2YB0lTkwuqRFvXYRQXZukpcCRmglkPd1FxWDgWuQeHJ8z5hEzZL9_IuN9VZE8YkBY$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-25 13:26 UTC, drgrice1 commented
I am wandering if the `submit_course_grade` method (with the setting `$LTIGradeMode = 'course';`) is working the way you really want with this pull request.  The case in question is the case that the `$LTISendGradesEarlyThreshold` setting is numeric, say it is set to `0.7`.

For the following, I assume that LTI 1.3 is in use.

Assume that it is the beginning of the semester, and a student enters webwork via a link in the LMS, but doesn't submit any answers for anything.  So now webwork has everything it needs to pass grades back for this student.  Now assume that a mass grade pass back occurs.  The `grade_all_sets` method will return `(0, 0)` for this student when called in list context because no sets meet the `0.7` threshold.  This is not a submission, so there isn't a user set that is initially checked in the `submit_course_grade` method, and so the `submit_grade` method is called with the `(0, 0)` score for this student.  The LMS returns no grade, and so the check for a prior score doesn't stop a grade submission, and that `(0, 0)` score is submitted.  I tested this with Moodle, and Moodle just takes that as a grade of `0`.  Is that what is desired?  Or should the course grade be checked to ensure it satisfies the threshold also?  If that is the case, then in the `submit_course_grade` method the `grade_all_sets` method should be called outside of the parameters for the `submit_grade` method, and its return value checked to ensure it meets the pass back criteria, and if it does then that return value should be passed on to the `submit_grade` method.  Otherwise, no grade should be submitted.

2024-11-25 20:22 UTC, Alex-Jordan commented
I would not want to check the course grade against the numerical threshold. The score could be lower than the threshold and you may still want that course score to go to the LMS simply because various critical dates have passed.

Here is an idea I have not thought through yet (and I have to leave for the day soon for PT conferences). What if `grade_all_sets` returns three things (when `wantarray` is true). The two things it currently returns, plus a count of how many sets were included.

Getting `(0,0)` can happen because no sets were included in the calculation. Or because a nonzero number of sets were included but each had a "0/0" score. The point is to distinguish these. And in the scenario you described, we would have `(0,0,0)` and we could just not send anything to the LMS in that case and I think that would be fine. Getting something like `(0,0,1)` is something I have not thought through yet. Just like all the situations in "homework" grade mode where there could be a "0/0" score.

2024-11-25 20:33 UTC, drgrice1 commented
That sounds like a reasonable solution.

2024-11-25 23:44 UTC, Alex-Jordan commented
As long as I'm changing that, is there any reason to make it more than a simple count? An alternative is that it could be an array reference with references to each of the included user set objects.

2024-11-25 23:58 UTC, Alex-Jordan commented
One reason I see where that may be helpful is that I can add a log message listing the sets that were included in the calculation when the overall course score is sent to the LMS. It could be a bit of a long log message. What do you think?

2024-11-26 00:00 UTC, drgrice1 commented
Sounds fine to me.  Certainly, the list of included user set objects would generally be more useful, and provide much more information.

2024-11-26 01:19 UTC, Alex-Jordan commented
OK, I added a commit that does that. Hopefully it is easy to just review that commit. Also I caught an error during testing that is fixed in a separate commit. Thirdly, I notices that in "homework" mode, the log would have entries like `Submitting grade for user alex.jordan and set Demo.` even under conditions when WeBWorK was not going to send the LMS a score. I moved those log entries in the code so they only are used if we are indeed going to try to send the LMS a score.

I did a fairly thorough round of testing with LTI 1.1. Things with LTI 1.3 are not really different now, as far as how this PR goes now. I haven't tested with LTI 1.3, but I feel OK that if it works for LTI 1.1, it will work for LTI 1.3. The necessary differences in the two `SubmitGrade.pm` look right to me.

2024-11-26 02:18 UTC, drgrice1 reviewed
I am not sure that I like that the messages `Submitting score for $userID...` to be moved down.  For debugging purposes it is good to have a message in any case.  Furthermore, there are now messages that occur earlier then this message that refer to the user.   For example, the message "LMS user id is not available for this user" in the `submit_set_grade` method for LTI 1.3 now occurs with no reference to which user the message regards.  So if this message is moved down, then the messages before that need to now include the `$userID`.

I think moving the message down also makes the messages I previously suggested for when a grade is not submitted necessary.

2024-11-26 02:18 UTC, drgrice1 commented on lib/WeBWorK/Utils/Sets.pm
> +	return ($courseTotalRight, $courseTotal, $includedSets);
It would be better to leave the `wantarray` case to be inconsistent with the other grading utility methods that all do that.  That will work fine with how the method is called in the LTI grade pass back modules.  I realize that with the additional return element in the list it makes the line long enough to need wrapping, but that isn't really a reason to remove it.  The following doesn't look that bad.
```suggestion
	return
		wantarray
		? ($courseTotalRight, $courseTotal, $includedSets)
		: ($courseTotal ? $courseTotalRight / $courseTotal : 0);

```

2024-11-26 04:44 UTC, drgrice1 commented
I agree, but that is why I had previously suggested adding messages in the case that grades were not sent.  You don't need to move the messages back, but the other messages need to be updated to accommodate the change.  The messages that say there is missing pass back data for the student need to include the `$userID` in the message to indicate which user the pass back data is missing for.

2024-11-26 04:47 UTC, drgrice1 commented
You could also move the message back, but change it to say something like "Considering submitting grade for $userID", although perhaps better wording.  Hopefully you get the idea from that poorly chosen wording though.

2024-11-26 07:14 UTC, Alex-Jordan commented on lib/WeBWorK/Authen/LTIAdvantage/SubmitGrade.pm
> +	return -1 unless $score;
I'm just checking if there was importance behind the condition in the `if` in your comment here. I have something like this now but it's just `if (!$score)`.

2024-11-26 07:39 UTC, Alex-Jordan commented
OK, take a look now at the debug messages. Sorry, before I had not seen your comments about those from Nov 21.

Also I reverted to letting `grade_all_sets` have a scalar context return. But nothing is using it at this time.

2024-11-26 11:16 UTC, drgrice1 commented on lib/WeBWorK/Authen/LTIAdvantage/SubmitGrade.pm
> +	return -1 unless $score;
I think this was inside the `submit_course_grade` method.  Currently line 136 in `LTIAdvanced/SubmitGrade.pm` and line 218 of `LTIAdvantage/SubmitGrade.pm` which is `return -1 if $submittedSet && !getSetPassbackScore($db, $ce, $userID, $submittedSet, 1);` there is no  message.

2024-11-26 11:30 UTC, drgrice1 commented
Yeah, since nothing is using the `grade_all_sets` method except LTI grade pass back, I almost moved it into the `WeBWorK::Authen::LTI::GradePassback` package.  But then I came up with the callback approach that made it more versatile (and was kind of fun to implement with the default signature parameter that is an anonymous sub).

Now all of the `sub grade...` methods in the file are consistent in their return behavior though.

2024-12-03 19:19 UTC, drgrice1 commented on lib/WeBWorK/Authen/LTIAdvanced/SubmitGrade.pm
> +		return 0;
This should be `return -1`.  A return value of 0 generally means that something went wrong with the grade pass back process.   A return value of 1 means success (not sending a grade because it was unchanged with `$LTICheckPrior` is considered success).  A return value of -1 means that the grade was not passed back because the criteria were not met which is what is happening in this case.

The different return values give a different type of messaged in the `passbackGradeOnSubmit` method.  For a return value of -1, the message is just "'Your score will be sent to the LMS at a later time." It isn't appropriate to say that the grade will be passed back in some specified amount of time, because at that time the criteria may not be met still, and so the grade may still not be passed back.

The same change of course is needed at this place in the LTI 1.3 method.

2024-12-03 19:55 UTC, merged